### ISSUE TITLE
Unable to start leader election, server does not allow access...

### ISSUE THREAD

**Issue by Yantrio** [jcmoraisjr/haproxy-ingress#10]
Whilst following the steps [here](https://github.com/kubernetes/ingress/tree/master/examples/scaling-deployment/haproxy) to set up an HAProxy ingress, I hit an issue where the pod will not come online due to not being able to post an endpoint. 

Currently using ubuntu 16.04 + kubeadm/kubectl 1.6.1 + kubernetes 1.6.0

Logs : 
```
[] ➜  ~ kubectl logs haproxy-ingress-564356010-cl6s5
I0407 12:19:31.909095       6 launch.go:96] &{HAProxy v0.2 git-cd17319 https://github.com/jcmoraisjr/haproxy-ingress}
I0407 12:19:31.910060       6 launch.go:232] Creating API server client for https://10.96.0.1:443
I0407 12:19:31.969977       6 launch.go:115] validated default/ingress-default-backend as the default backend
F0407 12:19:31.985231       6 status.go:188] unexpected error starting leader election: the server does not allow access to the requested resource (post endpoints)
```

**Comment by jcmoraisjr** [comment]
This sounds something related with RBAC. Did you configure access permission? Perhaps the DN of your certificate isn't allowed to query endpoints?

**Comment by Yantrio** [comment]
Yes, this was RBAC related, creating a permissive role let me use this :) sorry for the issue.
