### ISSUE TITLE
ignoring invalid cors headers on Ingress "*" 

### ISSUE THREAD

**Issue by a180285** [jcmoraisjr/haproxy-ingress#1014]
**Description of the problem**

I want to set CORS access-control-allow-headers to "*". but I got this errror.

`ignoring invalid cors headers on Ingress "xx/xx" * `

base on description [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers). "*" should be valid headers.

```
* (wildcard)
The value "*" only counts as a special wildcard value for requests without credentials (requests without [HTTP cookies]

(https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) or HTTP authentication information). In requests with credentials, it is

 treated as the literal header name "*" without special semantics. Note that the [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header can't be wildcarded and always needs to be listed explicitly.


```

**Expected behavior**

**Steps to reproduce the problem**

1.  add annotation of `haproxy-ingress.github.io/cors-allow-headers: '*'` to ingress

**Environment information**

HAProxy Ingress version: `v0.xx`
image version: quay.io/jcmoraisjr/haproxy-ingress:v0.14.2

# Root cause

Code [corsHeadersRegex](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/pkg/converters/ingress/annotations/validator.go#L38) are hard coded. and without "*".

**Comment by a180285** [comment]
@jcmoraisjr Thanks for quick fix.

**Comment by jcmoraisjr** [comment]
You're welcome. Closing.
