### ISSUE TITLE
[Help Needed]::HAProxy Ingress controller rete-limit

### ISSUE THREAD

**Issue by UPADHYA28** [jcmoraisjr/haproxy-ingress#1025]
Hi Team,

I was exploring the capabilities of HAProxy ingress controller.

I wanted to achieve (for now) limit the number of request to 1 in 1sec.. So i made following configuration haproxy-kubernetes-ingress configmap

<pre><code>
apiVersion: v1
data:
  frontend-config-snippet: |
    stick-table  type ipv4  size 100k  expire 30s  store http_req_rate(1s)
    http-request track-sc0 src
    http-request deny deny_status 500 if { sc_http_req_rate(0) gt 0 }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-kubernetes-ingress
    meta.helm.sh/release-namespace: haproxy-controller
  creationTimestamp: "2023-09-13T08:54:25Z"
  labels:
    app.kubernetes.io/instance: haproxy-kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.7.6
    helm.sh/chart: kubernetes-ingress-1.20.0
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
  resourceVersion: "1301337"
</code></pre>

**Comment by jcmoraisjr** [comment]
What about using [limit-rps](https://haproxy-ingress.github.io/docs/configuration/keys/#limit) instead? Please consider asking for help in the Slack channel, this issue tracker is exclusive for bugs and feature requests.
