### ISSUE TITLE
Flawed logic in ingress controller pod discovery

### ISSUE THREAD

**Issue by avmnu-sng** [jcmoraisjr/haproxy-ingress#1047]
I feel https://github.com/kubernetes/ingress-nginx/issues/7047 applies to HAProxy ingress. Can you take a look?

As pointed out in the https://github.com/kubernetes/ingress-nginx/issues/7047#issuecomment-930559124 comment, we also use all the labels https://github.com/jcmoraisjr/haproxy-ingress/blob/master/pkg/common/ingress/controller/status.go#L262-L271.

**Comment by jcmoraisjr** [comment]
Hi, thanks for pointing this issue to our attention! Just created #1116 which I hope fixes this on our codebase.

**Comment by avmnu-sng** [comment]
@jcmoraisjr Thanks. It will fix the issue.

**Comment by jcmoraisjr** [comment]
Merged and will be available in the next `v0.12`, `v0.13`, `v0.14` and `v0.15` versions.
