### ISSUE TITLE
Support md5/bcrypt/sha1 auth instead of "crypt"?

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#105]
The CRYPT password format is a bit outdated, it would be nice to support both.  The file format you are using is compatible with `htpasswd` if you pass `-d` for the `CRYPT` algorithm.  It would be nice, though, if you also supported more advanced hashes for better security.

**Comment by jcmoraisjr** [comment]
Hi, this is a HAProxy feature described [here](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.4-user), there is nothing ingress controller can do without first evolving the HAProxy itself.

Out of curiosity, or perhaps I misunderstood your question - why a plain sha256 hash would be better than the crypt passwd format using sha256 hash?

**Comment by dobesv** [comment]
Hmm maybe I just don't understand how it works.  Are you saying I can use
an sha256 hash with haproxy as they are right now?  How does it know what
algorithm was used?

**Comment by jcmoraisjr** [comment]
Using `mkpasswd` - found on any Alpine box:

```
/ # mkpasswd -m sha
Password: <type "admin">
$5$ZK7CFoA45WzuMNCy$sB2vS0jT/Zrhqd8kjNqgYHHYb/x7x76QwEr5zvk6308
```

Crypt [manpage](http://man7.org/linux/man-pages/man3/crypt.3.html) has some useful info about the crypt format, see eg `$5` means `sha256` hash.

**Comment by dobesv** [comment]
Ah okay great, just my confusion.  I think you can close this unless you
just want to add that to the docs.

**Comment by jcmoraisjr** [comment]
Reopening so I'll remember to revisit the docs.

**Comment by rikatz** [comment]
Opening a PR here to improve the docs
