### ISSUE TITLE
upstream-vhost support

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#106]
In the nginx ingress you can specify "upstream-vhost" which forces the Host: header on the upstream request.  I was using this to add TLS termination to a third-party service.

**Comment by jcmoraisjr** [comment]
Hi @dobesv , this is now supported since v0.6 (still beta) configuring [config-backend](https://github.com/jcmoraisjr/haproxy-ingress#configuration-snippet) with [http-request](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-http-request) set-header statement.
