### ISSUE TITLE
Set balance algorithm separately for each ingress

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#109]
For services that use websockets, leastconn is required.  But other services might want to use a different algorithm.  Currently the algorithm is specified globally instead of on a per-ingress basis, but in the actual haproxy.cfg file this option is specified separately for each backend.

**Comment by jcmoraisjr** [comment]
Added in the current snapshot of v0.6. Doc also updated. Closing.
