### ISSUE TITLE
Support for Kube Lego

### ISSUE THREAD

**Issue by thekalinga** [jcmoraisjr/haproxy-ingress#11]
Formally keeping a ticket open so that this can tracked

**Comment by thekalinga** [comment]
Just wanted to check whether this item is at all there on your roadmap?

If it is, any idea when we can see some movement on this.

Thanks

**Comment by jcmoraisjr** [comment]
Yes, already on the roadmap and probably to be implemented just after the next tag.

**Comment by thekalinga** [comment]
Thanks

**Comment by thekalinga** [comment]
@jcmoraisjr Thanks for letting me know :)

**Comment by jcmoraisjr** [comment]
Closing this issue since there is nothing to be done in the HAProxy Ingress code. Please follow https://github.com/jetstack/kube-lego/pull/228 .
