### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#111]
This ingress doesn't currently seem to support injecting CORS headers.

**Comment by dcowden** [comment]
@jcmoraisjr we need this as well.  

The annotation we'd expect to work is  `ingress.kubernetes.io/enable-cors`  We use it today in the nginx-ingress controller.

**Comment by jcmoraisjr** [comment]
Added in the current snapshot of v0.6. Closing. Please update this same issue if you have any problem.
