### ISSUE TITLE
Different Response Code for Non-SSL Traffic

### ISSUE THREAD

**Issue by colinjfw** [jcmoraisjr/haproxy-ingress#115]
I'm running into a case where I would like to return 403 or a 400 status code instead of returning a 302 when the backend requires a secure connection. This especially makes sense for an API where a 302 response code doesn't make sense if the API is being accessed primarily programmatically.

I'm wondering if this could be configured inside haproxy-ingress. Something like the `ssl-redirect` configuration but that allowed the user to select the response code. I'd be open to submitting a PR for this behaviour.

**Comment by dobesv** [comment]
When you setup the haproxy controller you specify which ports are exposed to the internet.  You could run two haproxy controllers, one which listens on port 80 and one on port 443.  Then one on port 80 could return whatever error or status code you want to.  In fact, you might not need haproxy at all on port 80, maybe some really simple http server that returns the error you want on that port.

Of course, this only works if you need all of your HTTP connections to be treated the same.  If you need to split behavior based on the hostname or path you might need to actually create two sets of ingresses, one http and one https.  Might get complicated.

If you need different behavior in the backend maybe you can detect it in the app server by checking the `X-Forwarded-Proto` header and returning an error if it isn't `https` (assuming HAProxy sets `X-Forwarded-Proto` reliably).

Anyway, just a couple of idea that don't require changing the ingress.  I think there might be some more support coming to inject some custom rules into the config which might do the trick as well.

**Comment by jcmoraisjr** [comment]
This sounds to me as an uncommon scenario and, on top of this, I cannot see a config option that looks fine.

Besides the options @dobesv had pointed out you can also override the template using a configmap volume.

I'll leave this issue open while thinking on an approach. Feel free to share your ideas on how you'd implement - annotation/configmap options.
