### ISSUE TITLE
Options to capture headers into access logs

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#118]
HAProxy has an option to capture certain headers in the access logs.  We would like to use this option, so it would be great to be able to specify those options using an annotation or command line flag.

e.g.

`capture request header X-User-Id len 32`

**Comment by jcmoraisjr** [comment]
Hi, a few months later ... `v0.7-snapshot.1` was just tagged with `config-frontend` configmap option. Is this good enough to the capture request keyword?

**Comment by dobesv** [comment]
Hi!  If it works as documented, then yes it should do the trick.  I'll try it sometime and open a new issue if it doesn't work.

**Comment by WillMoverley** [comment]
Hi @dobesv did you try this, and if so did it work ?

Many thanks,

**Comment by dobesv** [comment]
Hi, no I haven't tried it yet, sorry about that.
