### ISSUE TITLE
TLS on TCP ports

### ISSUE THREAD

**Issue by jsrolon** [jcmoraisjr/haproxy-ingress#126]
Hi,
We recently moved our configuration from haproxy-ingress 0.4 to 0.5-beta.2. We enabled one TCP port using the `tcp-services-configmap`, but we noticed that there's no documentation for TLS on TCP ports through ingress controller configuration.

We need to receive secure TCP traffic on our HAProxy, is there a way to enable this in the current version?

**Comment by jcmoraisjr** [comment]
The tcp-services-configmap just proxy layer 4 plain tcp requests to your backends, which means HAProxy have no idea if you have a PostgreSQL, ssh-server, plain http or https in the backend. If you need ssl offload you can either: use tcp-service and do this in the backend service; or use the ordinary ingress where HAProxy will do ssl offload for you on port 443.

... or perhaps I didn't understand what you need.

**Comment by lumeche** [comment]
Hello @jcmoraisjr . Our problem is that we use a TCP traffic (not http) and that's  why we cannot use regular ingress to configure haproxy in this case.

What we would like to do being able to perform the tls termination inside haproxy for our TCP traffic.

**Comment by jcmoraisjr** [comment]
This is not supported. HAProxy only support tls termination on http mode which is only used on regular ingress configuration.

**Comment by lumeche** [comment]
Do you know if this support can be added to HA-PROXY ingress controller? We already had done in haproxy outside of ingress-controller. 

We are willing to help by doing the development of the feature if required

**Comment by lumeche** [comment]
This is something what is working for us.  
Basically what we do is receive the connection to a port, perform the tls termination agains the cert.pem and then we fordward to a service called gateway. 


`
frontend nmsp-sfend
    bind *:8943 ssl crt /cert/cert.pem
	mode tcp
	default_backend nmsp-bend

frontend nmsp-fend
    bind *:8911 
	mode tcp
	default_backend nmsp-bend
	
######################################      BACKENDS       ################################
backend nmsp-bend
	balance roundrobin
	mode tcp
	server gw gateway:8911 check port 8911 inter 2s
`

**Comment by jcmoraisjr** [comment]
Wow, I was definitely ignoring bind+ssl on tcp mode! This is currently not supported but will give it a try.

**Comment by jcmoraisjr** [comment]
Hi there, `v0.7-snapshot.1` was just tagged and built with SSL over TCP services. Please have a look at the [doc](https://github.com/jcmoraisjr/haproxy-ingress#tcp-services-configmap) and any help on testing this feature is very much appreciated.
