### ISSUE TITLE
Option to have "maxconn" property to be configured per ingress resource as a new annotation 

### ISSUE THREAD

**Issue by swapnil1988** [jcmoraisjr/haproxy-ingress#128]
Currently there are configurations that can be set at ingress resource level in form of various annotations. But one important property of maxconn per backend server which is supported by haproxy but not available as an option to set as an annotation at ingress resource level.

Annotation can be something like

`ingress.kubernetes.io/max-connections : 1 `

**example expected haproxy configuration with maxconn:**
```
backend exampleAppBackEnd
    balance roundrobin
   server app1 10.0.0.1:8080  maxconn 1
   server app2 10.0.0.2:8080  maxconn 1
   server app3 10.0.0.3:8080  maxconn 1
```

**Comment by jcmoraisjr** [comment]
Hi, sure, already a v0.6 backlog.

**Comment by swapnil1988** [comment]
Thanks @jcmoraisjr

**Comment by jcmoraisjr** [comment]
Added in the current snapshot of v0.6. Closing. Doc [here](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/README.md#connection). Let me know if you have any problem updating this same issue.

**Comment by swapnil1988** [comment]
Thanks @jcmoraisjr it worked for me :)
