### ISSUE TITLE
Support for converters through haproxy.tmpl?

### ISSUE THREAD

**Issue by cinupina** [jcmoraisjr/haproxy-ingress#13]
I'm trying to do client certificate fingerprint extraction and forwarding by creating my own `haproxy.tmpl`, and adding a single line: ```http-request set-header X-SSL-Client-SHA1 %[ssl_c_sha1,hex]```, which works in the plain haproxy:1.7-alpine image. I found out that the `,hex` part is breaking the functionality when using `haproxy-ingress`. If I just did ```http-request set-header X-SSL-Client-SHA1 %[ssl_c_sha1]```, it works as expected -- but I want the string representation of the value, not binary. Any ideas on how to work around this problem?

**Comment by jcmoraisjr** [comment]
I deployed echoserver as of [deployment doc](https://github.com/kubernetes/ingress/tree/master/examples/deployment/haproxy), followed the [TLS auth doc](https://github.com/kubernetes/ingress/tree/master/examples/auth/client-certs/haproxy) and added this line to haproxy.tmpl:

```
frontend httpsfront-{{ $host }}
    ...
    bind unix@/var/run/haproxy-host-...
    http-request set-header X-SSL-Client-SHA1 %[ssl_c_sha1,hex]
```

From a Linux box I made this request (`31692` is the svc port which redirect to `ingress:443`, `/etc/hosts` has an entry to `foo.bar`):

```
$ curl -kiL --cert client.crt --key client.key https://foo.bar:31692/web
...
HEADERS RECEIVED:
accept=*/*
host=foo.bar:31692
user-agent=curl/7.50.2
x-forwarded-for=10.2.80.1
x-ssl-client-sha1=9D2E51C2B86612203C4147B070C4B9151AF95728
```

Let me know if I can help.

**Comment by cinupina** [comment]
@jcmoraisjr thanks for the reply. Interesting. Could you let me know which image version (https://quay.io/repository/jcmoraisjr/haproxy-ingress) and which version of haproxy.tmpl (https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/haproxy.tmpl) you were using?

**Comment by jcmoraisjr** [comment]
@cinupina I used current repo which doesn't have a tag yet, and now I have just updated my dev env to 0.2 (current latest version) and it does work as well.

Please let me know if you have progress here. I'll include this configuration in my own tests and will notify this same issue if I find what's going on here.

**Comment by cinupina** [comment]
@jcmoraisjr I used a brand new kube cluster just now, and did the exact steps I've been doing, and it works in here. I don't know what was causing the problem in the old cluster. Anyway, thanks for looking into this. Great work on the repo!
