### ISSUE TITLE
cpu-map in context of running from within the pod

### ISSUE THREAD

**Issue by styk-tv** [jcmoraisjr/haproxy-ingress#132]
On a dedicated ingress node, is it possible to utilize all cpu cores by binding processes to cores? Or how is that done if we were to efficiency. On bare its a bit easier to visualize.

```
global
    nbproc 4
    cpu-map 1 0
    cpu-map 2 1
    cpu-map 3 2
    cpu-map 4 3

frontend access_http
   bind 0.0.0.0:80
   bind-process 1
frontend access_https
   bind 0.0.0.0:443 ssl crt /etc/yourdomain.pem
   bind-process 2 3 4
```
Based on this: https://blog.onefellow.com/post/82478335338/haproxy-mapping-process-to-cpu-core-for-maximum

And latest doc:
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#cpu-map

**Comment by jcmoraisjr** [comment]
Hi, my current todo list has already backlog items related with configmap options that targets nbproc, nbthread, cpu-map and bind-process configs, but this should only be done after the next fork, targeting v0.7.

Your option right now is to edit the current template, create a configmap with it and create a configmap volume at /etc/haproxy/template on haproxy-ingress deploy or daemonset.

**Comment by jcmoraisjr** [comment]
Hi, `v0.7-snapshot.1` was just tagged and built with nbproc and nbthread configmap options. Any help testing this functionality is very much appreciated.
