### ISSUE TITLE
No affinity cookie provided by haproxy

### ISSUE THREAD

**Issue by RolandOtta** [jcmoraisjr/haproxy-ingress#134]
Hi,

i defined the following ingress:

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mweb
  annotations:
    kubernetes.io/ingress.class: external
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: route
  namespace: dev
spec:
  backend:
    serviceName: myservice
    servicePort: 80
```

but when sending a curl request to the application, i don't receive the proper route cookie for the session affinity.

when looking at the haproxy config i also don't see the proper configuration for session affinity. here is the backend part of the generated haproxy config

```
######
###### Backends
######
backend dev-myservice-80
    mode http
    balance roundrobin
    server 10.32.0.13:8100 10.32.0.13:8100 check port 8100 inter 2s
    server 10.38.0.14:8100 10.38.0.14:8100 check port 8100 inter 2s
    server 10.40.0.4:8100 10.40.0.4:8100 check port 8100 inter 2s
backend upstream-default-backend
    mode http
    balance roundrobin
    server 10.38.0.15:8080 10.38.0.15:8080 check port 8080 inter 2s
```

what am i missing?

btw i am using the image quay.io/jcmoraisjr/haproxy-ingress:v0.6-a80d2c6

**Comment by jcmoraisjr** [comment]
Hi, at this moment HAProxy Ingress doesn't support spec/backend. Adding to the backlog.

**Comment by jcmoraisjr** [comment]
Hi, this spec/backend support was just pushed to the current snapshot tag. Closing, just update this issue if you have any problem.
