### ISSUE TITLE
Memory leak on reload required

### ISSUE THREAD

**Issue by teotwaki** [jcmoraisjr/haproxy-ingress#135]
Hi,

First of all, thanks a ton for this project. It's fantastic. I recently switched to using this ingress-controller in a new cluster, but have been running into some issues. I can probably work around most of it, but I believe this one is noteworthy.

I seem to be running into a memory leak, whenever my cluster scales up, or whenever a pod gets HPA'd. For example, a node was added around 10:50:20 (CEST)

![2018-04-06-111136_1262x259_scrot](https://user-images.githubusercontent.com/1420434/38413187-4d1f6c82-398b-11e8-9dd6-3642b6ab9b62.png)

And the ingress-controller decided it needed to reload the configuration. Fair enough:

```
I0406 08:50:23.941173       7 controller.go:312] backend reload required
I0406 08:50:24.031249       7 controller.go:321] ingress backend successfully reloaded...
I0406 08:53:18.010282       7 controller.go:312] backend reload required
I0406 08:53:18.082892       7 controller.go:321] ingress backend successfully reloaded...
```

I'm guessing that second reload was triggered by a pod being added or something; I haven't looked into that. However, if we look at the pod's memory usage:

![2018-04-06-111559_843x318_scrot](https://user-images.githubusercontent.com/1420434/38413476-09fd6db8-398c-11e8-9dfd-652a8335bd12.png)

We see that there's a notable increase in memory usage reported at 10:50:39 (CEST), and another one at 10:54:10, after the second reload.

Another symptom of this is that the session counters all drop to 0, even though the connections are still established:

![2018-04-06-112151_208x283_scrot](https://user-images.githubusercontent.com/1420434/38413704-bd2f72d2-398c-11e8-99e8-aa2256388eb4.png)

If left unchecked, this trend will continue up until each replica uses gigabytes of memory (even though in normal operations, only megabytes are necessary for our workload).

I haven't been able to check whether it was the HAproxy processes or the Go process that was using the extra memory. I'll have to do that next time I see a memory spike. Right now, things look like this:

```
for pid in $(pgrep haproxy | sort -n); do grep -E 'Vm(Size|Data|Exe)' "/proc/$pid/status"; echo; done
VmSize:	   46372 kB
VmData:	   19252 kB
VmExe:	   15016 kB

VmSize:	   26784 kB
VmData:	   13424 kB
VmExe:	    1380 kB

VmSize:	   29816 kB
VmData:	   16456 kB
VmExe:	    1380 kB

VmSize:	   23456 kB
VmData:	   10096 kB
VmExe:	    1380 kB

VmSize:	   25888 kB
VmData:	   12528 kB
VmExe:	    1380 kB
```

(the first block being the Go process, and the other ones being HAproxy)

I'm currently running `latest` with the following params:

```
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --update-status=false
```

I also have the following configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
data:
  ssl-redirect: "true"
  use-proxy-protocol: "true"
```

**Comment by ausmith** [comment]
You had mentioned the "session counters all drop to 0", which I believe matches with the behavior described in #116. Out of curiosity, have/are you willing to do these same measurements with other reload strategies than the default `native` one? I am curious if you get the same behavior with the others. If so, that would indicate it is not the reload strategy displaying your described symptoms, but another part of the code.

**Comment by teotwaki** [comment]
Update: My HAproxies are caught in a memory increasing loop again:

![2018-04-09-114842_625x322_scrot](https://user-images.githubusercontent.com/1420434/38491381-f94b5504-3beb-11e8-8bb3-8f82d4f68ffb.png)

Checking the memory usage, I see that HAproxy has spawned a very large number of workers now:

```
/ # for pid in $(pgrep haproxy | sort -n); do grep -E 'Vm(Size|Data|Exe)' "/proc/$pid/status"; echo; done
VmSize:	   47944 kB
VmData:	   20824 kB
VmExe:	   15016 kB

VmSize:	   26784 kB
VmData:	   13424 kB
VmExe:	    1380 kB

VmSize:	   29816 kB
VmData:	   16456 kB
VmExe:	    1380 kB

VmSize:	   30592 kB
VmData:	   17232 kB
VmExe:	    1380 kB

VmSize:	   23448 kB
VmData:	   10088 kB
VmExe:	    1380 kB

VmSize:	   27652 kB
VmData:	   14292 kB
VmExe:	    1380 kB

VmSize:	   26652 kB
VmData:	   13292 kB
VmExe:	    1380 kB

VmSize:	   23124 kB
VmData:	    9764 kB
VmExe:	    1380 kB

VmSize:	   25204 kB
VmData:	   11844 kB
VmExe:	    1380 kB

VmSize:	   24168 kB
VmData:	   10808 kB
VmExe:	    1380 kB

VmSize:	   24264 kB
VmData:	   10904 kB
VmExe:	    1380 kB

VmSize:	   23400 kB
VmData:	   10040 kB
VmExe:	    1380 kB

VmSize:	   23584 kB
VmData:	   10224 kB
VmExe:	    1380 kB

VmSize:	   22932 kB
VmData:	    9572 kB
VmExe:	    1380 kB

VmSize:	   22944 kB
VmData:	    9584 kB
VmExe:	    1380 kB

VmSize:	   25896 kB
VmData:	   12536 kB
VmExe:	    1380 kB

VmSize:	   23988 kB
VmData:	   10628 kB
VmExe:	    1380 kB

VmSize:	   25316 kB
VmData:	   11956 kB
VmExe:	    1380 kB

VmSize:	   23960 kB
VmData:	   10600 kB
VmExe:	    1380 kB

VmSize:	   25036 kB
VmData:	   11676 kB
VmExe:	    1380 kB

VmSize:	   24084 kB
VmData:	   10724 kB
VmExe:	    1380 kB

VmSize:	   24800 kB
VmData:	   11440 kB
VmExe:	    1380 kB

VmSize:	   24160 kB
VmData:	   10800 kB
VmExe:	    1380 kB

VmSize:	   24908 kB
VmData:	   11548 kB
VmExe:	    1380 kB

VmSize:	   24172 kB
VmData:	   10812 kB
VmExe:	    1380 kB

VmSize:	   25180 kB
VmData:	   11820 kB
VmExe:	    1380 kB
```

```
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /dumb-init -- /start.sh --default-backend-service=ingress-controller/ingress-default-backend --default-
    7 root      11:41 /haproxy-ingress-controller --default-backend-service=ingress-controller/ingress-default-backend --defa
   30 root       3:49 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf
   87 root      10:25 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 80
  101 root      33:17 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 94
  152 root       0:23 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 101
  159 root       4:17 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 152
  173 root       1:57 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 166
  187 root       0:08 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 180
  201 root       0:24 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 194
  215 root       0:12 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 208
  222 root       0:13 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 215
  229 root       0:06 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 222
  236 root       0:10 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 229
  243 root       0:04 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 236
  257 root       0:04 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 250
  271 root       0:26 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 264
  278 root       0:07 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 271
  285 root       0:16 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 278
  292 root       0:07 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 285
  299 root       0:12 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 292
  306 root       0:05 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 299
  313 root       0:11 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 306
  320 root       0:05 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 313
  327 root       0:10 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 320
  334 root       0:05 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 327
  341 root       0:13 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf 334
```

```
I0409 06:35:12.990311       7 controller.go:312] backend reload required
I0409 06:35:13.061896       7 controller.go:321] ingress backend successfully reloaded...
I0409 06:35:14.053412       7 controller.go:312] backend reload required
I0409 06:35:14.101219       7 controller.go:321] ingress backend successfully reloaded...
I0409 06:40:21.133444       7 controller.go:312] backend reload required
I0409 06:40:21.193205       7 controller.go:321] ingress backend successfully reloaded...
I0409 06:40:24.056462       7 controller.go:312] backend reload required
I0409 06:40:24.102758       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:04:07.472286       7 controller.go:312] backend reload required
I0409 07:04:07.539872       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:04:10.720540       7 controller.go:312] backend reload required
I0409 07:04:10.778081       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:13:20.049511       7 controller.go:312] backend reload required
I0409 07:13:20.115400       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:25:20.006321       7 controller.go:312] backend reload required
I0409 07:25:20.074008       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:29:45.165373       7 controller.go:312] backend reload required
I0409 07:29:45.244642       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:37:14.718654       7 controller.go:312] backend reload required
I0409 07:37:14.784347       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:39:42.958307       7 controller.go:312] backend reload required
I0409 07:39:43.024191       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:40:02.719565       7 controller.go:312] backend reload required
I0409 07:40:02.783178       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:42:21.331713       7 controller.go:312] backend reload required
I0409 07:42:21.410938       7 controller.go:321] ingress backend successfully reloaded...
I0409 07:42:24.059079       7 controller.go:312] backend reload required
I0409 07:42:24.108543       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:08:41.004285       7 controller.go:312] backend reload required
I0409 08:08:41.070432       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:14:21.368098       7 controller.go:312] backend reload required
I0409 08:14:21.444604       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:29:13.215539       7 controller.go:312] backend reload required
I0409 08:29:13.267779       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:36:21.035815       7 controller.go:312] backend reload required
I0409 08:36:21.110643       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:48:14.892433       7 controller.go:312] backend reload required
I0409 08:48:14.972596       7 controller.go:321] ingress backend successfully reloaded...
I0409 08:53:21.116153       7 controller.go:312] backend reload required
I0409 08:53:21.203156       7 controller.go:321] ingress backend successfully reloaded...
I0409 09:05:42.617505       7 controller.go:312] backend reload required
I0409 09:05:42.690562       7 controller.go:321] ingress backend successfully reloaded...
I0409 09:11:21.394138       7 controller.go:312] backend reload required
I0409 09:11:21.465109       7 controller.go:321] ingress backend successfully reloaded...
I0409 09:22:38.073239       7 controller.go:312] backend reload required
I0409 09:22:38.126431       7 controller.go:321] ingress backend successfully reloaded...
I0409 09:29:50.277756       7 controller.go:312] backend reload required
I0409 09:29:50.359069       7 controller.go:321] ingress backend successfully reloaded...
```

I did not have any cluster scaling events. I also did not have any new deployments in this time period, which makes it a bit weird.

**Comment by teotwaki** [comment]
> You had mentioned the "session counters all drop to 0", which I believe matches with the behavior described in #116. Out of curiosity, have/are you willing to do these same measurements with other reload strategies than the default native one? I am curious if you get the same behavior with the others. If so, that would indicate it is not the reload strategy displaying your described symptoms, but another part of the code.

OK, so digging into this a bit more. The native reload strategy just spawns a new process, signaling to the old one to give up the listening socket but finish handling its connections. I'm mainly dealing with very long-lived websocket connections, so the "old" HAProxy processes can potentially end up sticking around for hours or days.

This is consistent with the logs above. 

This is also consistent with "connection counts dropping to 0". If a new HAproxy starts running and inherits the listen socket, but the old instance is wrapping things up, then it goes to reason that this new, fresh instance of HAProxy isn't managing any connections.

@ausmith, I'm happy to test the multibinder. Just to clear my curiosity, as I can't figure it out from reading the code/docs; would the same behaviour exist with multibinder? I'm unsure what is meant in the docs when they say:

> When a bind is requested, the LISTEN socket is sent over the UNIX domain socket using ancillary data.

From what I understand, I would end up in the exact scenario.

Maybe, a better route is figuring out why the controller thinks it needs to reconfigure itself every few minutes?

**Comment by ausmith** [comment]
👍 to your theory and 👎 to mine. I do not think multibinder will improve things for you, just be a different way to switch which process has the socket. We have not run into, yet, processes needing to keep the haproxy instance around for extended periods of time beyond the reload for long-lived connections. I unfortunately am unsure I have more advice to add here, but am extremely interested to see how this plays out.

**Comment by jcmoraisjr** [comment]
Do you have long lived connections? This should explain the big amount of haproxy procs. Perhaps you could give dynamic scaling a try.

What version are you using? There are some improvements regarding restart on newer versions.

Anyway this big amount of changing notifications doesn't sound right. Please try `--v=3` command line param (this is rather verbose) and paste the lines between two consecutive restarts where nothing should be changed.

**Comment by teotwaki** [comment]
Hi @jcmoraisjr,

Here is an excerpt from the log after a memory increase event: https://gist.github.com/teotwaki/c4d906b09d0fb45de353048f45d704f4

**Comment by teotwaki** [comment]
Right, so looking through the logs, it hadn't clicked in my mind that this ingress controller was actually keeping track of each pod inside a service individually. I assumed it would just speak to the Service endpoint. Even though we're talking about a tiny cluster (10-15 nodes or so), there's a lot of activity (HPA, cluster auto-scaling, dozens of new deployments per day).

Our baseline is about 4k permanent WebSocket connections, at rest. This obviously goes up massively when each region wakes up and becomes active.

**Comment by jcmoraisjr** [comment]
There is an undocumented `ingress.kubernetes.io/service-upstream` boolean annotation you can add to your ingress resources that make haproxy to be configured with service ip instead of individual endpoints. You'll have less reloads when the replicas change but you'll also have less loadbalancing features.

Dynamic scaling docs are on the [readme](https://github.com/jcmoraisjr/haproxy-ingress#dynamic-scaling).

Any of the two options above should give you a lot less reloads. Current development version will have a max amount of time haproxy should wait before closing long lived connections (eg websocket) after a reload. Perhaps this would also be useful to avoid some zombies. Docs [here](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.1-hard-stop-after) and plans to release the first snapshot version within one or two weeks.

**Comment by teotwaki** [comment]
Thanks a lot. I'm probably going to try out the dynamic scaling feature before going with the service IP. Although the max reaping time feature seems very useful as well.

I'm not exactly sure I understand the `backend-server-slots-increment`, however. Does this hint that HAProxy will itself decide to increase how many servers should be running, or is this based on the number of backend pods?

**Comment by jcmoraisjr** [comment]
> I'm not exactly sure I understand the `backend-server-slots-increment`

HAProxy cannot dynamically increment the number of backend servers, the actual configuration should have empty servers to be dynamically updated with a valid one. `backend-server-slots-increment` says how many servers should be added if the backend need to be expanded. If you use eg 16, you'll have 16 servers even if in fact using 2 or 3, and 32 if you are using 18 or 25. Unused servers stay in a maintenance mode and doesn't participate in load balancing.

**Comment by dobesv** [comment]
To clarify the comment above, HAProxy cannot dynamically adjust the size of its of backend server configuration/status information.  This isn't about the actual number of backend servers.  So with the haproxy-ingress it pre-allocates a bunch of backend server slots in the configuraiton and then dynamically changes their settings in response to scaling activities.  So if you have 50 slots but only 2 backends, 48 slots are marked as down in the haproxy config in memory.  As you add actual backends, the slots are updated via an API to point to the new backends that have come online.  Once all the configured slots are used up, though, a full config reload is needed with a new number of slots, which restarts all the workers, clears the stats, and allow.  So basically you want to set that dynamic increment to the maximum number of backends you expect to have.  Having the number of backends hovering around the increment would result in a full reload each time you add/remove a backend.

**Comment by jcmoraisjr** [comment]
>  Having the number of backends hovering around the increment would result in a full reload each time you add/remove a backend

... which #133 should fix on v0.6.

**Comment by jcmoraisjr** [comment]
> How is 0.6 coming along?

Most of the code is done, this weekend I'll push most of the pending PRs and tag the first snapshot. Planning to start beta within about three weeks.

> Anything I can do to help?

Tests and feedback are very helpful.

**Comment by teotwaki** [comment]
For the record, I'm using the following script to keeps thing in check:

```bash
#!/usr/bin/env bash

kctl() {
  kubectl -n "ingress-controller" $*
}

kexec() {
  local pod_name="$1"
  shift
  kctl exec "$pod_name" -c "haproxy-ingress" -- $*
}

get_pods() {
  kctl get pods -o name -l app=haproxy-ingress | cut -f2 -d/
}

get_small_proxies() {
  local pod_name="$1"
  kexec "$pod_name" netstat -lapten \
    | awk '$4 ~/:443$/ && $6 == "ESTABLISHED" && $7 ~ /^[0-9]+\/haproxy$/ { print $7 }' \
    | cut -f1 -d/ | sort -n | uniq -c \
    | awk '$1 < 10 {print}'
}

main() {
  for pod in $(get_pods); do
    get_small_proxies "$pod" | while read count pid; do
      echo "[pod=$pod] Killing pid=$pid as it only handles $count connections (sleeping $count s)"
      kexec "$pod" kill "$pid"
      sleep "$count"
    done
  done
}

main $*
```

@jcmoraisjr I see that you released beta 3 a few weeks ago. Would you assume it is stable/bug-free enough?

**Comment by jcmoraisjr** [comment]
Hi, yes, v0.6-beta.3 sounds stable enough to be promoted to latest/stable. I'm probably tagging v0.6 stable this or in the next weekend, or perhaps just after HAProxy 1.8.14 is tagged. The only difference between beta.3 and latest will be a `mkdir` in the Dockerfile in order to fix an issue when deploying on Openshift and the HAProxy version.

Note however that there are some major changes from v0.5: haproxy 1.7 -> 1.8 and a big template refactor. Regarding HAProxy, 1.8 was heavily tested and the current status is a very robust codebase. Regarding the template, this refactor was done very early in the v0.6 version and the community helped us to improve it's quality. Have a look at the [changelog](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/CHANGELOG.md#v06-beta1) in order to see known compatibility issues. Let us know if you have any problem in the upgrade.

**Comment by teotwaki** [comment]
Hey there @jcmoraisjr. We finally upgraded to 0.6 and enabled dynamic scaling. This has made me very happy. We no longer have any full reloads with new processes due to scaling events.

One note though, our development environment doesn't use rolling updates, and this seems to still require a full reload with new process. I'm guessing that this is due to the fact that the number of pods reaches 0 for a few seconds, and then when the pod count goes back up to 1, there is an assumption that we need to allocate a new backend increment?

**Comment by teotwaki** [comment]
Actually, I figured out where this was coming from. The issue came from the fact that we use annotations to lock some microservices in our development environment. When using an annotation on a service, this causes HAProxy to do a full reload & fork processes.

However, by switching to annotating the deployments, this no longer happens.

Thanks a lot for all your hard work @jcmoraisjr. Please let me know if I can ever buy you a beer or something.

**Comment by jcmoraisjr** [comment]
Hi, sorry the late reply. Great that everything is working now. Which annotation were you using and which value - if you can share? I've no idea what was happening.

No need to buy a beer but the _something_ would be great. Usage of latest, evaluate of betas or snapshots on dev/staging envs, report of issues and promote is an invaluable help to any free and open source software.
