### ISSUE TITLE
When more than one replica of haproxy, dynamic scale up is not consistent

### ISSUE THREAD

**Issue by anilarora** [jcmoraisjr/haproxy-ingress#146]
Recently ran into an issue where I had 2 replicas of the haproxy ingress controller and an Ingress for my service. I updated the replica count of my ingress controller from 1 to 10. What happens is that the ingress controller ends up generating two different mappings from the node name (dynamically generated) to the underlying IP address of the services. So, the prefix of the node wasn't consistently generated.

In replica 1, I get the following mapping...

```
    mode http
    balance roundrobin
    cookie JSESSIONID prefix  dynamic
    dynamic-cookie-key "Ingress"
    server server0002 10.244.0.41:8080 weight 1 check port 8080 inter 2s
    server server0005 10.244.1.38:8080 weight 1 check port 8080 inter 2s
    server server0007 10.244.2.48:8080 weight 1 check port 8080 inter 2s
    server server0009 10.244.2.51:8080 weight 1 check port 8080 inter 2s
    server server0000 10.244.2.52:8080 weight 1 check port 8080 inter 2s
    server server0001 127.0.0.1:81 check disabled inter 2s
    server server0003 127.0.0.1:81 check disabled inter 2s
    server server0004 127.0.0.1:81 check disabled inter 2s
    server server0006 127.0.0.1:81 check disabled inter 2s
    server server0008 127.0.0.1:81 check disabled inter 2s
    server server0010 127.0.0.1:81 check disabled inter 2s
    server server0011 127.0.0.1:81 check disabled inter 2s
```

In replica 2, I get the following mapping

```
    server server0001 10.244.0.41:8080 weight 1 check port 8080 inter 2s
    server server0004 10.244.1.38:8080 weight 1 check port 8080 inter 2s
    server server0009 10.244.2.48:8080 weight 1 check port 8080 inter 2s
    server server0000 10.244.2.51:8080 weight 1 check port 8080 inter 2s
    server server0006 10.244.2.52:8080 weight 1 check port 8080 inter 2s
    server server0002 127.0.0.1:81 check disabled inter 2s
    server server0003 127.0.0.1:81 check disabled inter 2s
    server server0005 127.0.0.1:81 check disabled inter 2s
    server server0007 127.0.0.1:81 check disabled inter 2s
    server server0008 127.0.0.1:81 check disabled inter 2s
    server server0010 127.0.0.1:81 check disabled inter 2s
    server server0011 127.0.0.1:81 check disabled inter 2s
```

Unless sticky load balancing is provided by the cloud provider loadbalancer, this breaks stickiness for the app because the node prefixes aren't consistent.

I am using the latest snapshot of the ingress controller. (I cannot find any identifying characteristics of the image in the log file).

**Comment by anilarora** [comment]
I was using the dynamic-scaling configuration parameter.

**Comment by jcmoraisjr** [comment]
Since v0.6 (current snapshot) cookie based sticky session uses HAProxy [dynamic configuration](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-cookie) which uses IP:port and a key (`"Ingress"` by default) to create the value. The server name isn't used here. Based on the config provided, you are using v0.6 (`weight` config was just added) so you shouldn't have any issue with stickyness. Please double check and let me know if sticky sessions aren't working.
