### ISSUE TITLE
Include modern scripting language (e.g. ruby) ?

### ISSUE THREAD

**Issue by westse** [jcmoraisjr/haproxy-ingress#152]
e7442870e4f1be2664b3e7364259a8772300dd16 dropped Ruby support, which makes sense because the original need for it was for the now-removed multibinder. But unfortunately our Kubernetes liveness script was written in Ruby and now breaks.

Should the haproxy-ingress image include a modern script language interpreter, like Ruby or Python, to support scenarios like Kubernetes readiness/liveness probes? My vote is yes. I don't care which language as long as it is more readable than Bash for semi-sophisticated code. If there are no strong preferences, restoring Ruby would make existing scripts (like ours) work again.

**Comment by Scukerman** [comment]
What stops you from creating and using your own image?

**Comment by westse** [comment]
@Scukerman Nothing, but I see value in including a scripting language in the base image and this issue is to see if others agree. I'm fine if the consensus is to create my own image.

I think it would be ideal if most people did not have to create their own image, and wonder what percentage would need to do so for reasons like mine (liveness probe scripts, etc).

**Comment by jcmoraisjr** [comment]
Hi, this would be nice, I'd add python but this sounds a very specific usecase which opens a precedent I wouldn't like to have. I have a similar usecase where a sidecar container was used instead of the ingress container itself - two containers, high cohesion, deployed together. This is the beauty of the Kubernetes' pod.

**Comment by westse** [comment]
Fair enough, thanks for the discussion.
