### ISSUE TITLE
Help with tcp connection

### ISSUE THREAD

**Issue by mccricardo** [jcmoraisjr/haproxy-ingress#16]
I currently have a PostgreSQL database running in a Pod and would like to be able to access it via `psql` with something like:

`psql -h postgres.domain.whatever -p 443`

I'm having some trouble getting the tcp connection to work.

**Comment by jcmoraisjr** [comment]
This need to be configured as a TCP proxy, but haproxy-ingress doesn't have such option yet. Already in the roadmap.

**Comment by mccricardo** [comment]
Cool. I'll close this one since it isn't really an issue. Thank you!

**Comment by rahulmr** [comment]
> I currently have a PostgreSQL database running in a Pod and would like to be able to access it via `psql` with something like:
> 
> `psql -h postgres.domain.whatever -p 443`
> 
> I'm having some trouble getting the tcp connection to work.

Did you get any solution for this? I am looking something like this for mongodb. I have exactly same scenario.
I was looking at haproxy ingress controller, kong, etc.
