### ISSUE TITLE
Support of cert-manager/letsencrypt without disabled TLS redirect

### ISSUE THREAD

**Issue by remoe** [jcmoraisjr/haproxy-ingress#160]
The letsencrypt domain validation fails because haproxy-ingress (and others) has enabled TLS redirect (ingress.kubernetes.io/ssl-redirect). The nginx ingress controller has the following implementation for it:

https://github.com/kubernetes/ingress-nginx/pull/2203

**Comment by jcmoraisjr** [comment]
Thanks for pointing this. This issue was already discussed in #131 and there is a fix almost being merged which is very close to that one.

**Comment by jcmoraisjr** [comment]
First v0.6 beta was just released and should fix acme challenge. Closing.

**Comment by remoe** [comment]
Tested it and it works ;)
