### ISSUE TITLE
Bug when services share the same TLS certificate

### ISSUE THREAD

**Issue by dobesv** [jcmoraisjr/haproxy-ingress#165]
I had a letsencrypt certificate with two hosts in it - one for the dashboard and one for grafana.  They have separate ingress resources and backend but using the same TLS key and certificate.

When I connect to the dashboard first, and then grafana, it sends the traffic to the dashboard backend instead of grafana.  It seems like because the two domains are using the same cert they are sent to the same backend.

On a hunch I changed the backends to use different certificates for each domain, and that seemed to resolve the problem.

**Comment by jcmoraisjr** [comment]
Couldn't reproduce this. My steps was:

* Create a valid Lets Encrypt cert. CN is grafana.mydomain and SAN has both grafana.mydomain and dashboard.mydomain.
* Create two deployments and its services. It isn't grafana and k8s dashboard but nginx:alpine (as "dashboard") and echoserver (as "grafana")
* Create one secret tls
* Create two ingress resources referencing the same secret/cert. Changed also to one single ingress resource with two hosts, no difference
* Same test with Safari, Firefox and Chrome
* Opened grafana.mydomain first, echoserver was shown. Opened dashboard.mydomain, nginx was shown.
* Using v0.6-beta.1

**Comment by dobesv** [comment]
OK, perhaps we can close this until someone else runs into it.  Whatever issues it was, I have a fix.  Perhaps it had something to do with AWS or something else going on in my environment.
