### ISSUE TITLE
Socket reconnection timing on pod deletion 

### ISSUE THREAD

**Issue by pmwebster** [jcmoraisjr/haproxy-ingress#167]
We've been using this for a while in production and we've noticed that if an ingress pod gets a SIGTERM for some reason, the leader election doesn't catch that the pod has died and we our customers sit disconnected for about 30-60 seconds waiting for the websocket to reroute elsewhere. 

Is there a way to make a configurable time duration to check leader death? 

I see that there's a check every 60 seconds for pod ips, but as I just recently found out, the k8s api has the ability to subscribe to pod updates (including ips) so it *could* in theory be almost instant upon random pod death.

I'm happy to help write this btw, but I was more curious if we were missing something by this seemingly being hardcoded to check every 60 seconds.

**Comment by jcmoraisjr** [comment]
Hi, leader election iirc is only used to update status of the ingress resources and shouldn't have any relation with the load balancer or your application availability.

This controller already watch endpoint events, which means as soon as a pod is available or unavailable, the controller is notified. You can check this behavior following the controller logs while you kubectl delete a pod.
