### ISSUE TITLE
Don't crash the whole ingress controller with syntax error in an ingress annotation.

### ISSUE THREAD

**Issue by dcowden** [jcmoraisjr/haproxy-ingress#170]
Using quay.io/jcmoraisjr/haproxy-ingress:v0.6-beta.1

We found out today that if you use an invalid value in an ingress annotation,the entire ingress controller will crashloop due to a syntax error parsing the file.

This is not the desired behavior. I'd rather reject just this ingress.

In the below example, note that  "unlimited" is not a valid value for ingress.kubernetes.io/proxy-body-size, but used to be I think ):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: ptplace
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    billing: ecom
    dr: mission-critical
    heritage: {{ .Release.Service }}
    affiliation: colinx
  annotations:
    ingress.kubernetes.io/affinity : "cookie"
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/ssl-redirect : "false"
    ingress.kubernetes.io/session-cookie-name : "PTPR_SESSION"
    ingress.kubernetes.io/proxy-body-size: "unlimited"
    ingress.kubernetes.io/hsts: "false"
```
This will generate an haproxy config file that has a line like this:

`  use_backend error413 if host-ptplace-bff.ecom.dev.colinx.com { var(txn.path) -m beg / } { req.body_size gt unlimited }`

This will produce a crashloop with an error similar to:

```
W0604 19:34:12.970956       5 controller.go:262] Error validating config file:
[ALERT] 154/193412 (23) : parsing [/etc/haproxy/haproxy.cfg:383] : error detected while parsing switching rule : 'unlimited' is neither a number nor a supported operator.
[ALERT] 154/193412 (23) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 154/193412 (23) : Fatal errors found in configuration.
E0604 19:34:12.970976       5 controller.go:316] unexpected failure restarting the backend: 
```

I'm not actually really sure it is possible to do what we really want here ( ignore the whole offending ingress).  it is possible to validate a file using something like:

`/usr/local/sbin/haproxy -c -V -f /etc/haproxy/haproxy.cfg`

But then i'm not sure its even possible to validate each portion of the file contributed by each ingress.

**Comment by jcmoraisjr** [comment]
Hi, check configuration is already done but it's really hard to identify what annotation or configmap option crashed the cfg file. Some annotations are almost impossible to validate before being used, eg snippet configuration. However some other annotations like proxy-body-size are quite simple to validate. I'll have a look at such improvement, thanks for sharing.

**Comment by dcowden** [comment]
Awesome thanks for looking into it. As of last week, we are using this ingress in our development environment with issues (other than above, which is minor). We should have it in production with about 30 days

**Comment by jcmoraisjr** [comment]
Hi, this isn't currently as rock solid as we'd like and expect it could be, but it's better than before. Closing. Please add new issue if you find other configs that crash haproxy config and sounds to be simple to check/validate.

**Comment by iamdempa** [comment]
Hi, I am having the similar issue, is there a fix already?

**Comment by jcmoraisjr** [comment]
In fact there are a number of validations we are missing, but also, another number of configurations we cannot properly validate like e.g. config snippets and some bind options. We already have #1407 that should fully solve this, and also we should revisit the "free text" configurations to improve or implement their validations along with that effort. Feel free to raise a new issue on the findings you have, this way we won't forget them.
