### ISSUE TITLE
HSTS is not set for default-backend-service

### ISSUE THREAD

**Issue by scurrility** [jcmoraisjr/haproxy-ingress#171]
Even though HSTS is set to true as default with 15768000 max age, the default-backend-service (e.g. default-http-backend) does not return the Strict-Transport-Security header.

**Comment by jcmoraisjr** [comment]
Indeed, thanks for pointing this. The fix need a rework on the template so I cannot schedule to the v0.6.

**Comment by jcmoraisjr** [comment]
Hi, now the current snapshot tag configures HSTS on default backend. Just update this same issue if you have any problem.
