### ISSUE TITLE
Allow to configure timeouts per ingress resource e.g. timeout-client

### ISSUE THREAD

**Issue by fortuneFelix** [jcmoraisjr/haproxy-ingress#176]
Hello,

It would be very useful to be able to control the various timeouts e.g. timeout-client per ingress resource via the annotations.
At the moment I can only see that it be done by using the ingress.kubernetes.io/config-backend annotation or suppling a custom haproxy template.

Thanks!

**Comment by jcmoraisjr** [comment]
This sounds to be a bit tricky since timeouts are frontend configurations, they don't accept acl, and the same frontend might be reused by several backends in order to save some sockets.

**Comment by jcmoraisjr** [comment]
Just to let you know v0.8 will have dynamic splitting of the frontend which will allow this configuration. Moving the milestone.

**Comment by jcmoraisjr** [comment]
Hi, this is already working as expected on v0.8 (currently beta). Note however that distinct client timeouts in the same cluster will generate more than one frontend, which will need to have another frontend (mode tcp) in front of them, slowing down your deployment a bit. Let me know if you have any problem.
