### ISSUE TITLE
support for client certificate when connecting to backend

### ISSUE THREAD

**Issue by xelalexv** [jcmoraisjr/haproxy-ingress#177]
I have a backend service that requires client certificates, but I would still like haproxy-ingress to do the TLS termination, then open a separate TLS connection to the backend service. Client authentication works, but I cannot find a way to make haproxy-ingress use a client certificate when connecting to the backend service. I was thinking that `ingress.kubernetes.io/config-backend` might help, but am not sure how to go about that.

Can this actually be done? If not, would it be feasible to add this feature?

**Comment by jcmoraisjr** [comment]
Hi, actually you can only ssl-passthrough if you want the backend to validate the client certificate. Client cert to connect to a backend is a nice feature to v0.7 - snapshot within the next weeks and beta in sep/18.

Perhaps you can also overwrite the template, add a `crt` in the `server` statement within `if backend.secure`, a crt/key file (secret/configmap), and configure annotations `ingress.kubernetes.io/secure-backends` as "true" and `ingress.kubernetes.io/secure-verify-ca-secret` with the name of the secret with CA bundle to validate server certificate.

**Comment by xelalexv** [comment]
> actually you can only ssl-passthrough if you want the backend to validate the client certificate.

Yes, that's as expected. haproxy-ingress does the client authentication, backend only accept the certificate of haproxy-ingress, and gets authenticated user from `X-SSL-Client` headers.

`ssl-passthrough` is what we're currently using. What prompted us to try and move termination to haproxy-ingress is that with passthrough, `ingress.kubernetes.io/whitelist-source-range` is ignored (possibly on purpose?). 

> Client cert to connect to a backend is a nice feature to v0.7 - snapshot within the next weeks and beta in sep/18.

Great! Looking forward to it. Meanwhile I'll look into overwriting the template.

**Comment by jcmoraisjr** [comment]
> What prompted us to try and move termination to haproxy-ingress is that with passthrough, ingress.kubernetes.io/whitelist-source-range is ignored (possibly on purpose?).

Whitelist is ignored because this check happens on http mode, which must be skipped on ssl-passthrough. There is a way to start the handshake on the HAProxy side and deny the request based on the source IP, I'll have a look into it.

> I'll look into overwriting the template

Create a configmap with `haproxy.tmpl` key and your new template, mount into `/etc/haproxy/template`. Create another configmap or a secret with crt+key, mount into anywhere in the container where the new `crt` statement is referencing and your are done. Let me know if you have any problem.

**Comment by xelalexv** [comment]
I tried with a customized `haproxy.tmpl` according to your suggestions, and it works like a charm. Thanks! Will move to the new feature once it's available.

**Comment by jcmoraisjr** [comment]
Hi, pushed a new annotation `ingress.kubernetes.io/secure-crt-secret` in the current snapshot tag. Closing. Update this same issue if you have any problem.
