### ISSUE TITLE
When both ssl-redirect and rewrite-target are used for a given location, client is redirected to the wrong location.

### ISSUE THREAD

**Issue by qwylz** [jcmoraisjr/haproxy-ingress#178]
When ssl-redirect is true and rewrite-target is set for a given location, the client is redirected to a wrong location.  Specifically, the client is redirected to https but with the rewritten path rather than the original path.  This is usually not the intended behavior.

For example:

Given:
- an ingress path of `/some/path/`;
- a rewrite-target of `/`;
- and ssl-redirect set to `true` (either globally or just for the specific ingress);

When a client attempts to get `http://hostname/some/path/with/deeper/components` the client will be redirected to `https://hostname/with/deeper/components`.  However, the client should have been redirected to `https://hostname/some/path/with/deeper/components`.

One way to get the correct redirection under these conditions is to include `from-https` in the `if` condition of the resulting `reqrep` line in the configuration.

For example:

```
reqrep ^([^\ :]*)\ /some/path//?(.*$) \1\ /\2 if host-hostname { var(txn.path) -m beg /some/path/ }
```

should be

```
reqrep ^([^\ :]*)\ /some/path//?(.*$) \1\ /\2 if from-https host-hostname { var(txn.path) -m beg /some/path/ }
```

Note that `from-https` should only be include when all of the above conditions are met.  If any of the conditions are not met, then `from-https` should not be included in the `reqrep` line.

**Comment by jcmoraisjr** [comment]
Nice catch, thanks for reporting. This happens because reqrep is processed before redirect - changing the order has no effect, HAProxy will always execute reqrep before. PR #179 should fix this.

**Comment by qwylz** [comment]
Thanks for quickly addressing this.  Please see my comment in PR #179.
