### ISSUE TITLE
FEATURE REQUEST:  Please allow enabling SSL for status URL.

### ISSUE THREAD

**Issue by qwylz** [jcmoraisjr/haproxy-ingress#180]
Thanks for a great haproxy-based ingress for kubernetes!

Would you please add the ability to configure SSL for the status URL, including the ability to specify the kubernetes secret name that has the SSL cert & key?

**Comment by dobesv** [comment]
I suppose you can always put your own SSL frontend in front of the status URL, using an ingress config with SSL on it.

**Comment by jcmoraisjr** [comment]
Hi, starting from `v0.7-snapshot.1` there is also an option to add a crt/key secret name in the `stats-ssl-cert` configmap option.

**Comment by qwylz** [comment]
@jcmoraisjr, thanks.  I'll try that.  I won't be able to get around to testing it for a few weeks, though, as I've got vacation coming up and need to get a bunch of stuff done before then, so I don't spend vacation working.  :-P

@dobesv, yes, that's possible, but violates our internal network security requirements (which are set by people who don't fully understand that what you propose could be done quite securely).

**Comment by qwylz** [comment]
Sorry for taking so long to get around to testing this.  The new `stats-ssl-cert` option in `v0.7-snapshot.1` works great.  It is exactly what I need.  Thank you!
