### ISSUE TITLE
support gzip compression?

### ISSUE THREAD

**Issue by dcowden** [jcmoraisjr/haproxy-ingress#182]
Is it possible to configure gzip compression?

haproxy supports it using something like:

```
 compression algo gzip
 compression type text/html text/plain text/css
```

It does appear that it is possible using `ingress.kubernetes.io/config-backend`, 
which works, but i wanted to make sure i wasnt missing another way.

BTW, the config-backend directive is genius. What a great way to make sure its possible to do what haproxy can do, without letting the ingress annotations list approach infinity!

**Comment by jcmoraisjr** [comment]
Hi, at this moment using config-backend is the only way. Config-backend is kind of a swiss knife: one can do a lot of personal config without the need to overwrite the whole template - which is btw a valid strategy as well.

**Comment by dcowden** [comment]
yes, it is an inspired approach.  many people make the mistake of either not providing that override, or making it all -or-nothing. Your implementation is perfect.

BTW, we are using 0.6.1-beta in production. :)
