### ISSUE TITLE
Feature Request: Add Frontend Bailout Configuration

### ISSUE THREAD

**Issue by dcowden** [jcmoraisjr/haproxy-ingress#188]
I've run into a limitation with the configuration.  I need to capture request headers, so that they can be put into the request logs. Doing this requires a custom log format ( no problem), but also requires capturing the request parameters in the front end:

`capture request header Referrer len 64`

Looking at the [template](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl), there appears to be no way to inject this into the frontend. 

The backend supports a 'bailout' configuration via a ingress annotation ingress.kubernetes.io/config-backend, which works well for cases that are not common enough to merit a first class configuration, yet are needed by certain use cases.

I think we need a similar 'bailout' for the frontend, which  should be in the configmap.  

This could be used to inject arbitrary haproxy things into the frontend stanza.

For now, the workaround is to simply bind our own copy of the template.tmpl file into the containers, which makes upgrades more painful

**Comment by jcmoraisjr** [comment]
Already an undocumented backlog, thanks for the doc =)

**Comment by dcowden** [comment]
10-4, its the _least_ i can do!

**Comment by jcmoraisjr** [comment]
Hi, just added `config-frontend` configmap option in the current snapshot.
