### ISSUE TITLE
haproxy ingress controller always redirects to https unless ingress.kubernetes.io/ssl-redirect is set to false.

### ISSUE THREAD

**Issue by dElogics** [jcmoraisjr/haproxy-ingress#198]
Since version v0.6-beta.2, all domains redirect to https unless ingress.kubernetes.io/ssl-redirect is set to false; this means option as specified in ssl-redirect does not work as expected.

**Comment by dElogics** [comment]
Ingress rule -- 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  creationTimestamp: 2018-05-08T20:52:52Z
  generation: 1
  labels:
    project: project
    purpose: purpose
    role: web
  name: site.domain.tld
  namespace: namespace
  resourceVersion: "116777248"
  selfLink: /apis/extensions/v1beta1/namespaces/namespace/ingresses/site.domain.tld
  uid: c67ee8c3-5301-11e8-8ede-0242c0a8c865
spec:
  backend:
    serviceName: ingress-default
    servicePort: 80
  rules:
  - host: site.domain.tld
    http:
      paths:
      - backend:
          serviceName: namespace-web
          servicePort: 80
        path: /

Another ingress rule (is not directly related) -- 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  creationTimestamp: 2018-01-13T03:40:36Z
  generation: 3
  labels:
    project: letsencrypt-verify
    purpose: project
    role: tls
  name: letsencrypt-verify
  namespace: default
  resourceVersion: "113305875"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/letsencrypt-verify
  uid: 844b5864-f813-11e7-8e3f-0242c0a8a808
spec:
   - host: namespace.site.domain.tld
    http:
      paths:
      - backend:
          serviceName: letsencrypt-verify
          servicePort: 80
        path: /.well-known/acme-challenge

Note the namespace.site.domain.tld, this's the same 'namespace' string as in the previous ingress rule.

Maybe this's because of the namespace segregation.

**Comment by jcmoraisjr** [comment]
What's your global `ssl-redirect` configmap option? What's the behavior of `site.domain.tld/` and `namespace.site.domain.tld/.well-known/acme-challenge` and what you were expecting?

**Comment by jcmoraisjr** [comment]
There are some improvements related with acme-challenge path and HAProxy Ingress itself can sign acme certs. Please file a new issue if this is still a problem with controller version and as much details as possible.
