### ISSUE TITLE
cannot validate certificate for 10.254.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by wangjianghuan** [jcmoraisjr/haproxy-ingress#2]
I'm trying to deploy haproxy-ingress .  According to the case of a website https://github.com/kubernetes/ingress/tree/master/examples/deployment/haproxy.
when I execute "kubectl create -f haproxy-ingress.yaml"  , The pod of haproxy-ingress status is "CrashLoopBackOff"   and the container logs 
"I0307 08:28:17.096877       5 launch.go:92] &{HAProxy v0.1 git-676b5a8 https://github.com/jcmoraisjr/haproxy-ingress}

I0307 08:28:17.097206       5 launch.go:221] Creating API server client for https://10.254.0.1:443

F0307 08:28:17.113124       5 launch.go:109] no service with name default/ingress-default-backend found: Get https://10.254.0.1:443/api/v1/namespaces/default/services/ingress-default-backend: x509: cannot validate certificate for 10.254.0.1 because it doesn't contain any IP SANs
"
How can I solve this error ?

**Comment by jcmoraisjr** [comment]
Hello, how do you create your cluster? How do you create your certificates? My guess is that the certificate used by kubeapi to build https connections doesn't include `10.254.0.1` as a valid IP address. Have a look as my [CA and certs builder](https://github.com/jcmoraisjr/simple-ca/blob/0.6/index.cgi#L59) and [CoreOS Kubernetes](https://github.com/coreos/coreos-kubernetes/blob/v0.8.5/lib/init-ssl#L65) implements this.

**Comment by wangjianghuan** [comment]
@jcmoraisjr Thank you for your reply , To make the certificate I try it on
