### ISSUE TITLE
No health check problem

### ISSUE THREAD

**Issue by RTBathula** [jcmoraisjr/haproxy-ingress#20]
Hi,
I followed this way created a haproxy-ingress rules and also mentioned 
`kubernetes.io/ingress.class: "haproxy"`
otherwise google loadbalancer getting created (as i am using GCE) even after i deploy (DaemonSet)haproxy-controller.
My haproxy-controller image is "quay.io/jcmoraisjr/haproxy-ingress:v0.3-beta.2"
where I am passing /etc/haproxy/template from configmaps.
And made a service for haproxy-controller with type: LoadBalancer.

The problem is i am seeing "This load balancer has no health check, so traffic will be sent to all instances regardless of their status" in red and also when i open my urls in browser it is showing
default backend - 404

my haproxy.tmpl
```
global

defaults
  mode    http
  timeout connect 5000
  timeout client  50000
  timeout server  50000

frontend localnodes
  bind *:80
  mode http
  default_backend servers

backend servers
  mode http
  balance roundrobin 
  server server1 mywebservicename:80 check

```
Could you help in this ?

**Comment by jcmoraisjr** [comment]
I use haproxy only on vm/baremetal installations and don't know how GCE work. I'll play with GCE next weekend and then update this issue. Let me know if you have any progress.

This controller doesn't have an URL for health check, will implement in the next release.

**Comment by RTBathula** [comment]
Thank you. That helps me. Currently Its working but seeing health check issues.

**Comment by jcmoraisjr** [comment]
@RTBathula FYI health check will probably be implemented in the `haproxy.cfg` file. You can create a monitoring frontend in the template and solve your issue right now. Have a look at HAProxy [docs](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-monitor-uri).

**Comment by jcmoraisjr** [comment]
Added a monitor URI in the default `haproxy.cfg` file which defaults to `:10253/healthz`. The `snapshot` tag already has this feature.
