### ISSUE TITLE
Feature request: Integrate haproxy-auth-request lua module

### ISSUE THREAD

**Issue by bcorijn** [jcmoraisjr/haproxy-ingress#200]
Hi,

I recently set up the bitly [oauth2-proxy](https://github.com/bitly/oauth2_proxy) in our kubernetes environment to control access to the kubernetes dashboard. Since this has improved our user-experience a lot, I want to implement the same on a few other services and set out to integrate it with HAProxy. 
I bumped into https://github.com/TimWolla/haproxy-auth-request, which I managed to get up and running quite smoothly using a self-built docker image that included the lua-socket library, a custom config that loaded the lua module and specified the authentication backend statically, and a backend code snippet to define the actual authentication.

Would there be any interest to integrate this functionality as a built-in feature? It use extends beyond the specific oauth2-proxy that we use imo. I see the Voyager ingress already integrated this and nginx has this out of the box, but I strongly prefer the customisation that this project offers.

**Comment by jcmoraisjr** [comment]
Hi, sure, this is already on the whish list and sounds to be simple enough to be released within the v0.7 version. I'll give it a try.

**Comment by bcorijn** [comment]
Awesome! 
The monkeypatched methods in the lua code are not even needed anymore with the version of HAProxy included in the 0.6-beta.1 release by the way.

I also tried to implement a fallback to HTTP basic auth if the auth-request failed, but that required a bit more ugly configurations as I had to specify a userlist outside of the ingress resources that used this. I know this is probably a very specific use-case though, so just the basic auth-request would already be great!

**Comment by bcorijn** [comment]
Let this slip for a moment, but testing it out now / next few days. First look through the PR looks very good, this is already a lot more advanced than I had expected! (probably also explains why it wasn't as easy as I had expected).

It took me a while to fully grasp the docs though, even after having already implemented this myself. Prefer me to give comments here or just do a PR with some additions/clarifications?

**Comment by jcmoraisjr** [comment]
Feel free to send PR if you have already the fix to a problem or if you want to improve the docs. Update this issue if you have any doubt or found a problem that's not clear how to fix.

**Comment by bcorijn** [comment]
@jcmoraisjr I just ran into a bit of a bit issue, which is not really caused by this implementation but by Ingress in general. I run my OAuth proxy in kube-system and wanted to authenticate from a different namespace. Since ingresses cant be cross-namespace this won't work without deploying another proxy. This scenario also comes up in the kubernetes issue discussing this: https://github.com/kubernetes/kubernetes/issues/17088

Only option I see to get around this, is to be able to split up the oauth-proxy ingress definition from the apps using it. I understand if you would not see any benefit in this kind of implementation at the moment though.

**Comment by jcmoraisjr** [comment]
You can create an [external name](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) service referencing `oproxysvc.kube-system.svc.cluster.local` if using kube-dns 1.7 or above. This actually doesn't work with coredns. I'll also add cross-namespace selector on ing.serviceName but this will only be added to v0.8.

**Comment by jcmoraisjr** [comment]
Closing, feel free to upgrade this same issue if you have any problem with oauth.
