### ISSUE TITLE
Is regex in HTTPIngressPath supported

### ISSUE THREAD

**Issue by git001** [jcmoraisjr/haproxy-ingress#207]
In the kubernetes-user slack channel was the question if the HTTPIngressPath supports regex.
The question was for nginx-ingress now my question is does the haproxy ingress supports regex in HTTPIngressPath or should this be solved with `rewrite-target`?

**Comment by jcmoraisjr** [comment]
Hi, do you mean `spec -> rules[] -> http -> paths[] -> path`? This is actually matching path with HAProxy's `path_beg`. There is a number of ways to improve this, eg flag via command-line or configmap option that if path sounds to be a regex then use `path_reg` instead; flag via annotation that path is a regex; use a CRD.

Moving to CRD or wait a possible major refactor of ingress resource is the right direction to follow imho, but drawing a workaround with configmap/annotation sounds fair enough to a short term solution.

**Comment by git001** [comment]
@jcmoraisjr Thank you
