### ISSUE TITLE
[Questions] Backend reload/timeout.

### ISSUE THREAD

**Issue by Zwordi** [jcmoraisjr/haproxy-ingress#209]
Hi Everyone,

I have a setup on a baremetal-cluster running with 6 VMS (3Worker-3Master). I'm using several deployment into several namespace without HTTPS.
I have a behavior that make me skeptical...
So i have several backend which are service definition within my namespace and to times to time i have backends which appears wrongly OFF. To have it right again i have to delete the pods.
This is a serious issue for me.

I read the wiki and didn't see (maybe not enough) a settings who could explain to me this behavior.
I'm aware that it may be an issue at one moment in time from the network but the health test should have it back automatically as it does on a traditional setup (without docker) .

I hope that i'm clear enough about my situation.

Have a nice day anyway.

Regards,
Zwordi

**Comment by jcmoraisjr** [comment]
Hi, #175 explains what you saw in your cluster? Which haproxy ingress are you using? Are you using dynamic scaling?

**Comment by Zwordi** [comment]
Hi,
Yes i'm using dynamic scaling. I'm gonna have a look on this topics and i will let you know.
Thanks,
Zwordi

**Comment by jcmoraisjr** [comment]
Hi, `v0.6-beta.5` was just released and should fix this issue. The problem was in the port number of the health check, which was configured in the template and wasn't configured in the CLI. The template config was removed.

**Comment by Zwordi** [comment]
Hi,
Many thanks for this feedback.
I'm gonna try it right now and will let you know.

**Comment by jcmoraisjr** [comment]
Hi, I hope this was properly addressed, closing.
