### ISSUE TITLE
Shared versus singleserver

### ISSUE THREAD

**Issue by bedis** [jcmoraisjr/haproxy-ingress#216]
Hi There,

In the template file, I can see that some service frontend can be either "shared" or "singleserver", but I don't understand the difference and I don't understand how to configure the singleserver mode (it seems by default, I'm using "shared")

Cheers

**Comment by jcmoraisjr** [comment]
Hi, shared frontend is the default whenever the controller can share the same `bind` keyword configuration between several hosts. At this moment a host has its own frontend (singleserver) if client cert authentication is used - bind would be incompatible between them.

Shared/singleserver is btw an internal feature only. 

The problem of having one frontend per host - the behavior up to v0.5 - is that every single host uses a socket, causing issues with `-x` hitless reloads.

There is a planned feature to v0.8 (feb/19 I hope) which gives more control of single/shared frontend.

**Comment by bedis** [comment]
Can you confirm what you mean by "host" ?

**Comment by bedis** [comment]
By the way, have you tried the master-worker mode with -x (or expose-fd's stats socket option) ?

**Comment by jcmoraisjr** [comment]
Host is the `spec.rules[].host` field of an ingress resource that should match the Header host of a request as well as the SNI extension used to choose a certificate on a TLS handshake.

`expose-fd` is already used, it's mandatory with `-x`.

What's the benefit of master-worker on an ingress controller? HAProxy always run as a daemon and reload use `-p` to save all the PIDs and `-sf` to reload all the processes.

**Comment by jcmoraisjr** [comment]
Hi, just for the sake of documenting the issue, the whole ingress parsing and the haproxy template was rewritten from scratch between v0.7 and v0.8, and now we have a lot smarter in-memory model since we decoupled from the k8s' ingress vendor. Now a http frontend is never fragmented and the fronting tcp proxy is only created if ssl-passthrough is used. Still looking for a way to avoid this as well.
