### ISSUE TITLE
Feature Request: Add Sprig template functions for Haproxy template

### ISSUE THREAD

**Issue by kobrinartem** [jcmoraisjr/haproxy-ingress#221]
Hi,

I am working on adding http://masterminds.github.io/sprig/ template functions for Haproxy template. I need template functions to work with lists and dictionaries. 

Would be possible to integrate this functionality as a pull request?

**Comment by jcmoraisjr** [comment]
Hi, sure, this is a welcome change provided that you maintain backward compatibility.
