### ISSUE TITLE
is it possible to configure "retries"?

### ISSUE THREAD

**Issue by mylittleweb** [jcmoraisjr/haproxy-ingress#245]
I would like to change the value of "retries" (https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#retries), but I couldn't find anything to configure by looking at haproxy.tmpl

**Comment by jcmoraisjr** [comment]
Hi, yes, since `retries` is a backend keyword you can use [config-backend](https://github.com/jcmoraisjr/haproxy-ingress#configuration-snippet) annotation.

**Comment by mylittleweb** [comment]
@jcmoraisjr  thank you!
