### ISSUE TITLE
dots in server-alias regex

### ISSUE THREAD

**Issue by nlighten** [jcmoraisjr/haproxy-ingress#246]
It seems that dots the regex for ingress.kubernetes.io/server-alias are always escaped disallowing the use dots in the regex expression, e.g. '(.*)'. Is this intended behavior?

**Comment by jcmoraisjr** [comment]
Hi, this annotation isn't as useful as it could be, I must admit. I'll have a look at this feature, perhaps creating another annotation so we don't need to break compatibility. I'll update this issue soon.

**Comment by jcmoraisjr** [comment]
Hi, current snapshot (v0.7-snapshot.4) has now server-alias-regex annotation, have a look at the [doc](https://github.com/jcmoraisjr/haproxy-ingress#server-alias).

**Comment by nlighten** [comment]
Thanks. Looking good to me. I am away for travel the coming two weeks but will try to find some time to test. Any timeline in mind for v0.7 release?

**Comment by jcmoraisjr** [comment]
v0.7 will move to beta and feature freeze this weekend and depending on the feedback from the community can be released between late dec/18 or early jan/19.

**Comment by nlighten** [comment]
Just tested with v0.7-snapshot.4 and generated config is as expected and functional.

**Comment by jcmoraisjr** [comment]
Hi, thanks for the feedback! Closing.
