### ISSUE TITLE
Sticky session on dynamic scaling configuration

### ISSUE THREAD

**Issue by jcmoraisjr** [jcmoraisjr/haproxy-ingress#25]
I'm implementing sticky session #18 and trying to create a reproducible hash to use on `server ... cookie <value>`. So I made a base64 of a partial hash of `<ip>:<port>` endpoint, which will always be the same regardless of haproxy.cfg updates.

The problem arises on the dynamic scaling configuration. If I create the hash when the slot is disabled, the hash will be the same on all servers because I don't have the endpoint yet. If I create the hash based on the server name, this can be changed when the number of slots changes. Afaics HAProxy doesn't have a `set server cookie <value>` to change this on the fly, because of that the `cookie <value>` of empty slots should be configured on the template.

I can see one strategy here: when using dynamic scaling, calc the hash based on the server name and never change it's name when scaling down the number of replicas. This sounds a hard but also a doable work once that we have the old config.

Ideas are very welcome.

cc @aiharos

**Comment by aiharos** [comment]
After HAProxy 1.8 we will have the dynamic option for server cookies, outlined here
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-cookie

This dynamic cookie is calculated from a static secret string and the currently active ip & port of a particular server. It will always be up-to-date with the ip & port (even after changing them through socket) and provide exactly what we need here - a particular endpoint (ip & port) will always have the same cookie regardless which backend server name it is assigned to.

Until that time though, I would suggest to:
- use server names to calculate cookie contents
- advise users to set a reasonably high `backend-server-slots-increment` to minimise reloads

Users are likely to want to tune `backend-server-slots-increment` to their needs anyways, we can optionally increase the default from 32 to something larger like 256. 

An improvement upon this would be, as you suggested, to not reorder and reassign endpoints to slots when needing to change the number of slots in `fillBackendServerSlots`, but to remove or add selectively while keeping existing entries unchanged until the target number of slots is reached.

If you want to go the latter route let me know and I'll rework `fillBackendServerSlots`.

**Comment by jcmoraisjr** [comment]
I don't think this rework worth the effort. I'll follow the servername based content, document the limitation and how to circumvent until we can upgrade this controller to HAProxy 1.8. Thanks for the comments.
