### ISSUE TITLE
Select backend pods based on label

### ISSUE THREAD

**Issue by nlighten** [jcmoraisjr/haproxy-ingress#254]
Hi,

We are migrating from Docker Swarm with a custom templated HAProxy 'ingress' using confd to K8S with haproxy-ingress. Almost all functionality (+ much more!!) is out of the box supported by haproxy-ingress except for 1 scenario which is similar to a/b deployment. We allow teams to deploy a new version of their application and allow to them to target this version by adding a specific header to their request. This is used to validate the application on the production environment without the need to already direct real user traffic to it like you would do in an a/b scenario.

I may have overlooked this in the documentation but I don't think this is currently possible. Basically I am looking something similar to the bluegreen example where if I would configure: 

`ingress.kubernetes.io/blue-green-balance=group=blue=1,group=green=0`

Sending a request with a special header like e.g.:

`X-Group-Selector=green`

would result in the request being send to green even though the weight is 0. Cookie affinity seems to allow me to do this, but requires the user to know valid cookie values and is awkward for api's.

**Comment by jcmoraisjr** [comment]
Hi, welcome to k8s and haproxy-ingress! You're right, this feature doesn't exist yet, I'd like to have this implemented in v0.7 but couldn't find the time to make this happen. v0.8 is already being developed and this will be one of the first improvements.

**Comment by groner** [comment]
I'm also interested in doing something like this, but with cookies.  As I understand it, the current cookie based affinity only allows a specific backend server to be targeted.

**Comment by jcmoraisjr** [comment]
Hi, this is implemented in v0.9-snapshot.1, perhaps you can give this version a try. [Doc](https://haproxy-ingress.github.io/docs/configuration/keys/#blue-green) updated.

**Comment by jcmoraisjr** [comment]
Feature released, doc updated. Closing.
