### ISSUE TITLE
Aliases don't work

### ISSUE THREAD

**Issue by Scukerman** [jcmoraisjr/haproxy-ingress#257]
I try to update to `v0.7-beta.1` from (v0.6-beta.2) and I'm getting this error:

```
E1127 10:18:51.973911       7 controller.go:337] unexpected failure restarting the backend:
template: haproxy.tmpl:650:14: executing "acl" at <$server.AliasHost>: can't evaluate field AliasHost in type *types.HAProxyPassthrough
```

I have even tried to rewrite `server-alias` annotations to `server-alias-regex`. No luck.

Basically, annotation looks like this:
`ingress.kubernetes.io/server-alias-regex: '[a-z0-9]{10}\.example\.com'`

Note: I haven't tried to remove these annotations at all.

**Comment by jcmoraisjr** [comment]
Hi @Scukerman beta.2 was just released. Thanks again for reporting.
