### ISSUE TITLE
FR: add liveness probe to daemonset 

### ISSUE THREAD

**Issue by antonmatsiuk** [jcmoraisjr/haproxy-ingress#263]
if the haproxy gets killed on the node (pkill -f haproxy), kubernetes won't  restart the corresponding pod. Adding liveness probe to haproxy daemonset solves the issue:

livenessProbe:
  httpGet:
    path: /healthz
    port: 10253

**Comment by jcmoraisjr** [comment]
Fixed since #277, closing.
