### ISSUE TITLE
Implement CORS Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by james-powis** [jcmoraisjr/haproxy-ingress#265]
Access-Control-Expose-Headers effectively hides all headers when default to nothing, many tools rely on these headers to when making AJAX calls to cross domain resources.

To better align with the full capabilitys of haproxy and CORS this should be implemented.

I will make an attempt at submitting a PR on this in the next week or so.

**Comment by james-powis** [comment]
For those following at home until this is PR'ed/merged/released, you can implement the missing COR Headers via the following ingress annotation:

```
      ingress.kubernetes.io/config-backend: |
        rspadd Access-Control-Expose-Headers:\ Location
```

**Comment by jcmoraisjr** [comment]
#268 addresses this issue, closing.
