### ISSUE TITLE
HAProxy 1.9 Has Arrived ,The latest version supports haproxy1.9

### ISSUE THREAD

**Issue by aland-zhang** [jcmoraisjr/haproxy-ingress#270]
HAProxy 1.9 Has Arrived ,The latest version supports haproxy1.9?
https://www.haproxy.com/blog/haproxy-1-9-has-arrived/

**Comment by jcmoraisjr** [comment]
Hi, haproxy 1.9 should be used on v0.8, perhaps we have a beta version about march/19.
