### ISSUE TITLE
matching domain instead of domain+port in acl

### ISSUE THREAD

**Issue by theonlydoo** [jcmoraisjr/haproxy-ingress#272]
I stumbled upon a (imho) impossible configuration:

```yaml
    config-frontend: |
      acl balance_ton_port var(txn.hdr_host) -i (.*):.*
      http-request replace-value Host (.*):.* \1 if balance_ton_port
```
it'd be nice to be able to just hit an ingress (for debug or internal service purposes) without having to pass a `-H 'Host: foo.bar'` to `curl` .

**Comment by jcmoraisjr** [comment]
Hi, have you tried a single service ingress? See [here](https://kubernetes.io/docs/concepts/services-networking/ingress/#types-of-ingress). You can also try an ingress resource without `host:` attribute.

**Comment by jcmoraisjr** [comment]
Closing due to the lack of feedback. Please find us on slack or any other [community](https://haproxy-ingress.github.io/community/) option if you have any problem.
