### ISSUE TITLE
modsecurity file not found on filesystem

### ISSUE THREAD

**Issue by jyaworski** [jcmoraisjr/haproxy-ingress#281]
I'm attempting to deploy modsecurity as a sidecar and I'm getting:

`[ALERT] 010/181430 (31) : parsing [/etc/haproxy/haproxy.cfg:125] : 'filter' : 'Could not open configuration file /etc/haproxy/spoe-modsecurity.conf : No such file or directory'`

Is there a condition where the template won't get laid down in the ingress controller container?

Please let me know if I can provide any more information.

**Comment by jcmoraisjr** [comment]
Hi, modsec config file is always built or updated from the template, despite of your global configuration, just before haproxy start/restart. However the file is used only if you configure `modsecurity-endpoints`. I couldn't reproduce this behavior myself, please provide as much information as possible about your environment and configurations.

**Comment by jyaworski** [comment]
I've created a gist with helm's debug output here for a full config:

https://gist.github.com/jyaworski/29d0b2bfc69d18b80acddcf5fa1fac00

It appears to happen when backend reloads are requested.

**Comment by jcmoraisjr** [comment]
Hi, sorry about taking so long to properly test this and figure out the problem. I'll tag a new version tomorrow and update this issue as soon as the new image is available.
