### ISSUE TITLE
How to configure backend servers health check by HTTP protocol 

### ISSUE THREAD

**Issue by toyoaki-k** [jcmoraisjr/haproxy-ingress#290]
I have one question.
I want to use uri-based healthcheck for backend servers.
(e.g. Loadbalancer regularly sends a request to ```/healthcheck``` on backend servers)

So I think [haproxy's httpchk option](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-option%20httpchk) is a goog way. 
But I can not find the way to configure. How can I configure it?

**Comment by jcmoraisjr** [comment]
Hi, this is indeed not implemented atm.

**Comment by toyoaki-k** [comment]
@jcmoraisjr 
Thank you for your prompt reply and adding this function to v0.8 milestone! I god it.

**Comment by jcmoraisjr** [comment]
Hi, sorry the long delay, v0.8 became a big and an almost unpredictable monster - which is finally finished. Please check if the current implementation fit your needs. Use a v0.8 tag.

https://github.com/jcmoraisjr/haproxy-ingress#health-check
