### ISSUE TITLE
Use snippet to add custom options 

### ISSUE THREAD

**Issue by AlexProfi** [jcmoraisjr/haproxy-ingress#294]
I use this config(part of them)
```
  log-format: https-log-format

  config-frontend: |
    option dontlog-normal
```
But in haproxy.cfg in container there is no rules from snippet

```
cat /etc/haproxy/haproxy.cfg |grep dontlog
    option dontlognull
```
How to fix this ?

**Comment by jcmoraisjr** [comment]
Hi, what version of the controller are you using? `config-frontend` configmap option was added on v0.7 which is still beta.

**Comment by AlexProfi** [comment]
> Hi, what version of the controller are you using? `config-frontend` configmap option was added on v0.7 which is still beta.

Hi.
I use  image: quay.io/jcmoraisjr/haproxy-ingress

**Comment by jcmoraisjr** [comment]
This is currently v0.6.1. Add the `:canary` version to the url.

**Comment by AlexProfi** [comment]
It works. Thanks

**Comment by AlexProfi** [comment]
> This is currently v0.6.1. Add the `:canary` version to the url.

It works. Thanks

**Comment by jcmoraisjr** [comment]
Snippets are not parsed, you can use any valid keyword there. If you are lucky haproxy will only warn that some keyword is being processed before another and you are ok. If you used an invalid keyword or an invalid syntax haproxy will let you know and will refuse to reload.

**Comment by AlexProfi** [comment]
Thanks a lot
