### ISSUE TITLE
Update Haproxy to 1.9.3

### ISSUE THREAD

**Issue by AlexProfi** [jcmoraisjr/haproxy-ingress#297]
Hello. I found haproxy 1.9.3 on docker hub in alpine mode
How to update current version in this package to 1.9.3
I want to try it because I get errors SSL Read failed(5) during multiple(4) ab test of haproxy working in tcp mode

**Comment by jcmoraisjr** [comment]
Hi, there is not a simple way to update haproxy version afaik, you'll have to build the controller yourself, changing the FROM clause of the Dockerfile. haproxy 1.9 is planned to v0.9 which is planned to jun/19, I hope we have the first snapshot about may/19.

**Comment by jcmoraisjr** [comment]
Just a minor update here, starting v0.12 haproxy can be configured to run on a sidecar container, so you can use any image version you want provided that it's 2.0 or above. Closing.
