### ISSUE TITLE
haproxy-ingress can be set via HTTP access kubeapi rather than HTTPS ?

### ISSUE THREAD

**Issue by wangjianghuan** [jcmoraisjr/haproxy-ingress#3]

**Comment by jcmoraisjr** [comment]
You can try `--kubeconfig` command-line parameter pointing to a config file. Syntax is the same used by kubectl (`~/.kube/config`)

**Comment by wangjianghuan** [comment]
I'm not understand。 I mean the "haproxy-ingress" container via HTTP access kubeapi,  how to set parameter --kubeconfig ?

**Comment by jcmoraisjr** [comment]
The [deployment instructions](https://github.com/kubernetes/ingress/tree/master/examples/deployment/haproxy) has a [deployment resource](https://github.com/kubernetes/ingress/blob/master/examples/deployment/haproxy/haproxy-ingress.yaml). Add a `--kubeconfig` parameter in the args array. You should mount your kubeconfig file as a hostPath or secret [volume](https://kubernetes.io/docs/user-guide/volumes/) inside haproxy-ingress controller or your configuration won't work.

**Comment by wangjianghuan** [comment]
Thank you very much !

**Comment by jcmoraisjr** [comment]
Closing this. Just add a new comment if you have any doubt
