### ISSUE TITLE
Support kubernetes.io/ingress.class

### ISSUE THREAD

**Issue by abh** [jcmoraisjr/haproxy-ingress#30]
It'd be nice to be able to run this next to other ingress'es in a cluster.

**Comment by jcmoraisjr** [comment]
This should be working since 0.3 (current latest/stable), let me know if you have any issue. I'll leave this open until docs are updated.

**Comment by jcmoraisjr** [comment]
[Doc](https://github.com/kubernetes/ingress/tree/master/examples/deployment/haproxy) updated.
