### ISSUE TITLE
Update haproxy-ingress to haproxy v1.8.19

### ISSUE THREAD

**Issue by pasikarkkainen** [jcmoraisjr/haproxy-ingress#300]
Upstream haproxy 1.8.19 has been released, with some regression and bugfixes:
http://www.haproxy.org/download/1.8/src/CHANGELOG

"[ANNOUNCE] haproxy-1.8.19": https://www.mail-archive.com/haproxy@formilux.org/msg32775.html
"[ANNOUNCE] haproxy-1.8.18": https://www.mail-archive.com/haproxy@formilux.org/msg32724.html

Sounds like both the haproxy-ingress v0.6 and v0.7beta should be updated to v1.8.19?

**Comment by jcmoraisjr** [comment]
Hi, yep, v0.7 is going to be released in a few days and will be on top of 1.8.19.

**Comment by pasikarkkainen** [comment]
@jcmoraisjr awesome! thanks a lot.

**Comment by pasikarkkainen** [comment]
haproxy-ingress v0.7.0 and v0.7.1 have been released, so we can close this issue. Thanks a lot!
