### ISSUE TITLE
haproxy daemonset pod fails to start, sometimes.

### ISSUE THREAD

**Issue by zapman449** [jcmoraisjr/haproxy-ingress#304]
Problem: approximately 1 in 3 pod invocations, the pod fails to start.  It remains in a `ContainerCreating 0/3` state when interrogated via kubectl.

Background info:
We run haproxy-ingress-controller as a daemonset.  In addition, we bundle two other containers into that daemonset: one for rsyslog to take logs and send them to stdout (enables the rest of the log pipeline) and another to handle AWS external healthchecking (dumb python app which receives the HTTP request, and formulates a correct query to localhost:443 with pycurl to hack the SNI headers, etc).

We have a work-around with an AWS Lifecycle policy that if the node isn't alive in 10 minutes, it's reaped, and another comes in it's place.  This is insufficient because other work could come onto this node, and the lifecycle policy could terminate it ungracefully.

We run kubernetes  v1.10.11.

Any ideas?

I've attached a anonymized daemonset config.

[haproxy_ds.yaml.txt](https://github.com/jcmoraisjr/haproxy-ingress/files/2894576/haproxy_ds.yaml.txt)

**Comment by zapman449** [comment]
For reference:
1. This problem has existed in kube 1.7 and 1.10, with haproxy versions 0.5.x, 0.6.x and 0.7.x
2. The "solution" to this is to delete the pod if it remains in `ContainerCreating` for 2 minutes.  The pod usually comes online within 10 seconds after that.
3. I haven't seen other daemonset or deployment pods affected by this

**Comment by zapman449** [comment]
Anyone?

**Comment by jcmoraisjr** [comment]
Hi, any useful information in events? eg `kubectl describe pod <haproxy-ingress-pod>`

**Comment by zapman449** [comment]
Events don't show anything out of the ordinary.

**Comment by jcmoraisjr** [comment]
Hello again, quite some time since the last ping. I don't have any useful idea since we're not big users of cloud providers. Hope that you could manage to fix or workaround what was happening here, and if so please share any useful info that we could add to a faq or a troubleshooting guide.
