### ISSUE TITLE
Change default certificate info

### ISSUE THREAD

**Issue by zapman449** [jcmoraisjr/haproxy-ingress#311]
By default, an erroneous query which would go to the default backend sees a certificate with the following subject: `subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate`

This was flagged as an information leak in a recent pen-test, and I'm trying to figure out how to plug it.

I thought the CLI flag of `--default-ssl-certificate` would allow me to override that with a self-signed certificate, however that doesn't seem to be the case.

How can I change the subject line on the default cert?

Using haproxy-ingress v0.7-beta.7

**Comment by jcmoraisjr** [comment]
Hi, this is the DN of a fake certificate generated by the controller and used if you don't provide your own. I couldn't reproduce this with v0.7-beta.8:

```
$ :|openssl s_client -connect 192.168.100.99:443 -servername blabla 2>/dev/null|openssl x509 -noout -issuer -subject
issuer= /CN=localhost
subject= /CN=localhost
```

where 192.168.100.99 is the ip address of my cluster and `/CN=localhost` is the DN of my self-signed certificate.

**Comment by zapman449** [comment]
ok.  I'll try to repro with more details.  To be clear, you're specifying `-default-ssl-certificate` as a secret?

**Comment by jcmoraisjr** [comment]
Hi, yep, here is the command-line option:

```
        - --default-ssl-certificate=ingress-controller/default-cert
```

and the secret:

```
$ kubectl -n ingress-controller get secret default-cert
NAME           TYPE                DATA      AGE
default-cert   kubernetes.io/tls   2         141d
```

**Comment by zapman449** [comment]
Confirmed, I was holding it wrong.  Thank you
