### ISSUE TITLE
handle multple ingress resources

### ISSUE THREAD

**Issue by dontreboot** [jcmoraisjr/haproxy-ingress#312]
How does haproxy-ingress handle multiple ingresses? Does it handle it similarly to how ingress-nginx does?
https://kubernetes.github.io/ingress-nginx/how-it-works/#building-the-nginx-model

> Order Ingress rules by CreationTimestamp field, i.e., old rules first.
If the same path for the same host is defined in more than one Ingress, the oldest rule wins.
If more than one Ingress contains a TLS section for the same host, the oldest rule wins.
If multiple Ingresses define different paths for the same host, the ingress controller will merge the definitions.
Annotations are applied to all the paths in the Ingress.
Multiple Ingresses can define different annotations. These definitions are not shared between Ingresses.

**Comment by jcmoraisjr** [comment]
Hi, yes, this is exactly like that: the controller merges the ingress objects and if an overlap happens, the older ingress wins.

**Comment by dontreboot** [comment]
Thanks for your confirmation!
