### ISSUE TITLE
Please expose `len X` in haproxy `log` lines.

### ISSUE THREAD

**Issue by zapman449** [jcmoraisjr/haproxy-ingress#314]
We leverage JSON logs to kick out structured values via haproxy -> rsyslog -> LOGGING_INFRA.  Recently we noticed haproxy truncating some log-entries.

Could we expose a configmap entry akin to `syslog-endpoint` and `syslog-format` to manage `syslog-length`, which would default to the standard default of 1024, but allow users to specify longer lines if required?

Current (GROSS) work-around:  specify `syslog-endpoint` as `127.0.0.1:514 len 2048` to shim the magic haproxy value in.

Upstream docs: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.1-log

**Comment by jcmoraisjr** [comment]
Sure we can - added to v0.8 backlog.

**Comment by jhohertz** [comment]
Looks like it was added in #396?

**Comment by jcmoraisjr** [comment]
Hi, yep, but v0.9 only which will have its first snapshot tag in a few days.

**Comment by jcmoraisjr** [comment]
v0.9-snapshot.1 now has `syslog-length` configmap option, updating doc soon.

**Comment by jcmoraisjr** [comment]
Doc also updated. Closing.
