### ISSUE TITLE
How is haproxy-ingress-controller handling shutdown of haproxy?

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#316]
A question: How does haproxy-ingress-controller handle shutdown of haproxy processes when it receives the SIGTERM signal, e.g. when kubernetes is stopping an haproxy-ingress-controller pod?

I'm investigating a case where I have deployed haproxy-ingress as a DaemonSet. When the cluster is scaled down, this means that the haproxy-ingress pod on the node to be removed  is stopped, and I would like to know if that is done gracefully. We have a strange situation where it seems that long-lived websocket connections to a server are not being closed properly. It could of course be a problem on the server side, but I would like to check how it is handled by haproxy-ingress-controller.

As I understand it, haproxy-ingress-controller is the main container process and therefore receives the SIGTERM signal from kubernetes. Then ideally it should send a SIGTERM to all haproxy processes in the container, so they can do a graceful shutdown (killall -TERM haproxy). This is the haproxy "hard stop":

> The hard stop is simple, when the SIGTERM signal is sent to the haproxy process, it immediately quits and all established connections are closed.

**Comment by mhyllander** [comment]
I've done some more testing. I don't think there's anything wrong with how haproxy is being terminated. I have tried sending both TERM and KILL signals to the haproxy process, as well as deleting the haproxy-ingress-controller pod, and in all cases the TCP connections are closed correctly on the server side.

No, the problem we have appears to occur only when our cluster is being scaled down. We are using cluster-autoscaler to scale the cluster up and down (using Azure VM scale sets). As I mentioned before, we have deployed haproxy-ingress-controller as a DaemonSet, so when the cluster is scaled down (a node removed), an haproxy-ingress-controller pod is removed at the same time. When this happens, the TCP connections on the server side are not closed. I don't know exactly why this happens, maybe the node's networking is being torn down before the daemonset pod processes are stopped, so that TCP resets cannot be sent to the servers?

Azure CNI is using host networking, so every pod has an IP address directly on the vnet, and TCP connections are directly between haproxy and server. When the cluster is scaled down, I can see that the servers still have established TCP connections with the IP address of the haproxy-ingress-controller pod that was deleted.

**Comment by jcmoraisjr** [comment]
Hi, the pid 1 of the haproxy-ingress-controller container is dumb-init, which receives the sigterm from the container runtime. Both haproxy and the controller are child process of dumb-init which gracefully stops both.

```
/ # pstree
dumb-init-+-haproxy
          `-haproxy-ingress
```

I'm afraid I cannot help here since we only use k8s on bare metal deployments. Please provide some feedback if you make any progress and let me know if anything could be improved on the controller.

**Comment by mhyllander** [comment]
An update: to handle this problem we have implemented detection of half-closed connections on the server side. As mentioned above, it seems that when the cluster-autoscaler scales down the cluster, connections to the upstream servers are not closed properly. It's possible that I have also seen this behavior when doing a rolling update of the DaemonSet, but not every time. Anyway, I will close this issue as I don't think the problem lies in haproxy-ingress.
