### ISSUE TITLE
Feature:  Consider config-defaults key for ConfigMap

### ISSUE THREAD

**Issue by RisingPhorce** [jcmoraisjr/haproxy-ingress#320]
Like config-frontend, and config-global the config-defaults would a a multi-line list that would be appended to defaults giving more flexibility without needing a custom the template.

**Comment by jcmoraisjr** [comment]
Hi, config-defaults added to v0.8, [doc](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet) updated. Closing.
