### ISSUE TITLE
Issue: Wildcard Certs and Cert Manager Duplicate Certs

### ISSUE THREAD

**Issue by RisingPhorce** [jcmoraisjr/haproxy-ingress#321]
1.  I have deployed the haproxy ingress to it's own name space. 
2.  I've deployed Jetstack Cert Manager to another namespace.  I'm using cert-manager to issue wildcard certs.  

If all deployments for a given wildcard cert are in a single namespace, everything works well.  

However, if we deploy apps in multiple name spaces and they share a wildcard certificate, the secret is copied from each namespace into a file name /ingress-controller/ssl/{namespace}-{secret-name}.pem in the haproxy container.  This causes duplication in the my second scenario because certs are keyed by namespace and name in backend_ssl.go:checkMissingSecrets().

It seems it would be better to hash on the thumbprint or cert contents.

Example:
```
  ns/cert-manager:
    po/cert-manager
  ns/app1
    deploy/app1
    po/app1-xyz
    certificates.certmanager.k8s.io/wild-test-example-com-le-acme (cert request)
    secret/wild-test-example-com-le-acme (*.test.example.com)
    ing/app1
      ...
      secretName:  wild-test-example-com-le-acme
  ns/app2
    deploy/app2
    po/app2-xyz
    certificates.certmanager.k8s.io/wild-test-example-com-le-acme (same request, cert is copied)
    secret/wild-test-example-com-le-acme (same *.test.example.com cert)
    ing/app2
      ...
      secretName:  wild-test-example-com-le-acme
  ns/ingress:
    po/haproxy-ingress
      /ingress-controller/ssl/app1-wild-test-example-com-le-acme.pem
      /ingress-controller/ssl/app2-wild-test-example-com-le-acme.pem

             ^--- same cert
```

**Comment by jcmoraisjr** [comment]
Hi, the problem is the duplication or is there any other side effect regarding duplicate the certs/keys?

**Comment by RisingPhorce** [comment]
My apologies.  Upon further inspection, cert manager is generating different certs/keys.  I will open the issue with them.  I will probably need to let cert-manager manage a set of wild card certs in a single location.  

However, I believe the design of haproxy-ingress (and nginx ingress) with a single merged configuration the  would mean that I will need to use something like https://github.com/mittwald/kubernetes-replicator to move the certs to the relevant namespaces.  When a wildcard cert updates and the secret replication copies to all other targeted namespaces, I imagine this will cause a number of haproxy reloads, 1 for each tls secret change.

I don't know if there is a Kubernetes object descriptor precident and what the design trade-offs would be, but would it be possible to support an ingress reading a tls secret from another namespace?  For example:

```
tls:
  secretName:  cert-manager/wild-test-example-com-le-acme
```

**Comment by jcmoraisjr** [comment]
Hi, sorry the long delay, vacation here these last weeks.

Regarding the updates, if the secret update is fast enough, HAProxy won't reload more than one time every 2 seconds (by default, can be changed via command-line option).

Regarding `tls/secretName` with namespace this is already in the v0.8 backlog.

**Comment by RisingPhorce** [comment]
@jcmoraisjr  Thanks for the information.

Can we link this issue to the v0.8 `tls/SecretName` issue?  This would address the concern on the haproxy operator side of things for me by eliminating the secret replicator and multiple reloads.

**Comment by jcmoraisjr** [comment]
Hi, missed this issue, sorry. `--allow-cross-namespace` command-line option should solve this, doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#allow-cross-namespace). Please let me know if you have any problem with this option.
