### ISSUE TITLE
A flag to add custom headers on requests

### ISSUE THREAD

**Issue by dnavre** [jcmoraisjr/haproxy-ingress#322]
I need to add X-Forwarded-Proto & X-Forwarded-Prefix headers to my end user originating requests. While the first one is quite popular and support for it can be built into the proxy itself via annotations the second is rarely used and doesn't deserve similar implementation.

What I suggest is allowing an ingress resource to either define a custom block of configuration to be injected via annotations, or to be able to just add hardcoded headers to the proxied requests. Something like the following:

```yaml
haproxy.ingress.kubernetes.io/add-headers: 
  - X-Forwarded-Prefix: /api
```

A bit more context for the curious ones:
The reasoning is that I'm using swagger API documentation generator and the damned thing requires absolute paths via Open API Specification v3. To generate an absolute path behind a proxy you need to know what path the original request that came to the proxy had.

**Comment by jcmoraisjr** [comment]
Hi, sorry about taking so long to have a proper look into this feature request.

Header manipulation is one of the features you can configure using config-backend, eg:

```yaml
    annotations:
      ingress.kubernetes.io/config-backend: |
        http-request set-header X-Forwarded-Prefix /api
```

Is there something else the feature request could make on behalf of the admin/dev?

**Comment by dnavre** [comment]
@jcmoraisjr I belive this fully satisfies my needs, thank you very much!

Also, I think the "ingress.kubernetes.io/config-backend" annotation was not available at the time I made the feature request. But it is now!
