### ISSUE TITLE
Default TLS settings too insecure

### ISSUE THREAD

**Issue by jpiper** [jcmoraisjr/haproxy-ingress#329]
I think it makes more sense to be more selective with the default cipherSuite - the [nginx ingress](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#ssl-ciphers) ones are a good starting point. Likewise, it makes sense to only enable TLS1.2+ by default as well.

**Comment by jcmoraisjr** [comment]
Thanks for reporting this, implemented in v0.9-snapshot.1. [doc](https://haproxy-ingress.github.io/docs/configuration/keys/#ssl-ciphers) updated. Closing.
