### ISSUE TITLE
Using multiple ingresses with rewrites causes parse error

### ISSUE THREAD

**Issue by alanpearce** [jcmoraisjr/haproxy-ingress#333]
We are using version 0.7.1

When we specify the annotation `ingress.kubernetes.io/rewrite-target: /` on multiple ingresses that share a hostname, haproxy fails to reload the configuration. This holds whether the reload strategy is `native` or `reusesocket`.

Logs:
```
W0503 14:09:02.816111       7 controller.go:283] Error validating config file:
[ALERT] 122/140902 (100) : parsing [/etc/haproxy/haproxy.cfg:233]: line too long, truncating at word 65, position 749: <} !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxx/ }>.
[ALERT] 122/140902 (100) : parsing [/etc/haproxy/haproxy.cfg:232] : error detected while parsing a 'reqrep' condition : missing closing '}' in condition.
[ALERT] 122/140902 (100) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 122/140902 (100) : Fatal errors found in configuration.
E0503 14:09:02.816160       7 controller.go:337] unexpected failure restarting the backend: 
exit status 1
W0503 14:09:02.816177       7 queue.go:113] requeuing snip/snip, err exit status 1
```

Relevant line in the config file:
```
    reqrep ^([^\ :]*)\ /xxxxx/xxxxxxxxx/xxxxxxx//?(.*$) \1\ /\2 if host-xxxxxxxxxxx.xxxxxxxxxx.xxxx { var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxx/xxxxxxxx } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxxxxx/ } !{ var(txn.path) -m beg /xxxxx/xxxxxxxxx/xxxxxxx/xxxxxxxxxxxxx/ }
```

It looks like the error caused by this line https://github.com/jcmoraisjr/haproxy-ingress/blob/v0.7.1/rootfs/etc/haproxy/template/haproxy.tmpl#L507-L509

The limits seem to be defined in haproxy https://github.com/haproxy/haproxy/blob/v1.9.0/include/common/defaults.h#L70-L75

I suppose we could try to recompile haproxy, but I wonder if there is a better solution that could be reached by writing the configuration file differently. Any ideas?

**Comment by jcmoraisjr** [comment]
Hi, it sounds [v0.7-beta.8](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/CHANGELOG.md#v07-beta8) broke your configuration, see PR 308. Please give v0.7-beta.7 a try and let me know if everything works fine. If so I'll do my best to fix this issue without breaking the other one.

Btw v0.8+ is smarter enough to build the HAProxy configuration in such a way that this won't be an issue anymore.

**Comment by alanpearce** [comment]
Yes, it works. Thanks for the reassurance that 0.8 will improve the situation!

I've been researching replacing Traefik with haproxy-ingress, this gives me some more confidence to recommend it.
