### ISSUE TITLE
Haproxy cannot verify issuer's authority

### ISSUE THREAD

**Issue by fdvieira** [jcmoraisjr/haproxy-ingress#337]
Hello,

I have configured our haproxy ingress for Kubernetes with an authentic certificate. I'm trying to do a wget to one of our backends services but when I try it, I get an error message saying that it's not possible to verify the issuer: "Unable to locally verify the issuer's authority."

Is there any option, annotation that I can use to avoid this? 

Just a note, if we use the option "--no-check-certificate" it works but I don't want to ignore the certificate.

Thanks in advance.

**Comment by jcmoraisjr** [comment]
Hi, there is no option to be turned on, you use a valid certificate and it should work.

Note that if the certificate's SAN doesn't have your domain, it will not work and the default certificate of the controller would be used instead.

Check the certificate being used with this openssl trick:

```
$ :|openssl s_client -connect <ip-controller>:443 -servername <host.domain> | \
  openssl x509 -noout -issuer -subject
```

**Comment by fdvieira** [comment]
Thanks for the answer, that got me to the conclusion that the certificate was missing some things. Thanks a lot. Solution for me was: fix the certificate on the haproxy.
