### ISSUE TITLE
IP Whitelisting for TCP mode 

### ISSUE THREAD

**Issue by KKlapper** [jcmoraisjr/haproxy-ingress#338]
I am using quay.io/jcmoraisjr/haproxy-ingress:v0.7.1 and was able to configure TCP backends with tcp routing and SNI. 

As next step I need to restrict access per configured ingress to certain IP addresses. I configured the documented annotations, but the annotation does not take effect on the haproxy configuration for the HTTP TCP frontend. It seems the whitelist annotation is only added to HTTP frontends (as defined in the haproxy.tmpl)

Is there a way to adjust the haproxy.tmpl and add the whitelist annotation at the end of the use_backend statement:
use_backend {{ $server.Backend }} if { req.ssl_sni -i {{ $server.Hostname }} src{{ $location.HAWhitelist }} }

Unfortunately it does not work with a custom template, as the variable $location.HAWhitelist is empty for SSLPassthrough Backends.

**Comment by jcmoraisjr** [comment]
Hi, whitelist takes the frontend's http route in the configuration while ssl-passthrough goes straight to the backend via L4 (tcp), which makes a bit difficult to whitelist a ssl-passthrough connection. v0.8 will fix some design flaws and will make this configuration work as expected.

**Comment by KKlapper** [comment]
Thanks for the answer. What’s the plan on the availability of v0.8?
