### ISSUE TITLE
TCP SNI not working in v0.8 snapshot

### ISSUE THREAD

**Issue by KKlapper** [jcmoraisjr/haproxy-ingress#341]
TCP SNI is not working in v0.8 snapshot. Filling variable req.backend needs to be done before tcp-request content accept (move line 247 up to 244)
https://github.com/jcmoraisjr/haproxy-ingress/blob/master/rootfs/etc/haproxy/template/haproxy.tmpl

The issue is similar to this one
https://discourse.haproxy.org/t/log-sni-in-tcp-mode/1534

**Comment by jcmoraisjr** [comment]
Hi, thanks for pointing this, I'll definitely have a look as soon as proper sni test starts.
