### ISSUE TITLE
Enabling dynamic-scaling causes back-end to freeze....

### ISSUE THREAD

**Issue by ddanboyle** [jcmoraisjr/haproxy-ingress#346]
I'm using 0.7

What is the relationship between the front end configmap with dynamic-scaling set to true, the backend-server-slots-increment to 60 (say), and the actual backend server?

I have an existing system setup that runs, but when I set the dynamic-scaling flag to true, my backend server goes into a crashloop backoff cycle, and kubectl get events doesn't show anything and the backend pod doesn't stay up long enough to get a log...

If I set backend-server-slots-increment to 60 in the haproxy-ingress, does that mean I should make 60 different back-end pods?  

I'm missing something basic here, so sorry for the stupid question

**Comment by jcmoraisjr** [comment]
Hi, have you configured liveness? Is your controller container issuing any log? A crash loop should leave some pieces of information out there.
