### ISSUE TITLE
haproxy does not respond after certain period of time and requires a restart of the pod

### ISSUE THREAD

**Issue by sarmak1179** [jcmoraisjr/haproxy-ingress#347]
Hi,

I have deployed the haproxy ingress controller daemonset to luanch 3 pods on 3 different nodes.

After certain period of time (~24 hours), the end points exposed on the ingresses are not reachable.

The pod logs do not show any errors. The pods are not restarted. But the connections to 1936 or the heatlthz port are not available.  The syslog is not giving any clue.

After I restart the pods then everything works fine. 

This is happening in one of our prod environment. Can anyone give me pointers to where to look into. 

The configmap snapshot (with the IP/services masked) is:

data:
  "4560": test/sample1:81
  "6001": test/sample2:8080
  balance-algorithm: roundrobin
  config-frontend: |
    backlog 10000
  max-connections: "100000"
  syslog-endpoint: x.x.x.x:514
  timeout-client: 60s
  timeout-connect: 7s
  timeout-http-request: 30s
  timeout-keep-alive: 1s
  timeout-queue: 60s
  timeout-server: 60s
  timeout-tunnel: 3600s

haproxy output on one of the containers is:

# haproxy -vv
HA-Proxy version 1.8.19 2019/02/11
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1a  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

**Comment by sarmak1179** [comment]
This happened again on prod environment. Can anyone help me out on where to start the troubleshooting?
Curl to localhost:1936 on the pod itself doesn’t work, though the pod is in running state.

**Comment by jcmoraisjr** [comment]
Hi, where are you deploying the controller - which cloud / on premisse? Something like this happened before on GKE, see #173 .

**Comment by sarmak1179** [comment]
I am running on AWS instances(not on EKS). And the OS is Ubuntu 16.04

**Comment by jcmoraisjr** [comment]
Sorry the quite long delay here. I saw a similar issue on deployments whose maxconn hasn't properly configured. I'd also suggest you upgrading to v0.10 and configure a proper monitoring dashboard in order to see what's happening internally and also help to debug the controller and haproxy. Metrics doc [here](https://haproxy-ingress.github.io/docs/examples/metrics/). Find us on slack or any other [community option](https://haproxy-ingress.github.io/community/) if this is still an issue.
