### ISSUE TITLE
jenkins slave connection to master, through HAproxy, in not reliable

### ISSUE THREAD

**Issue by tiagomiguelsousa** [jcmoraisjr/haproxy-ingress#348]
Hello.

I've a K8s Cluster, with several pods, one of them being Jenkins (master). My Ingress is HAProxy.
I'm trying to connect a jenkins slave, from outside the cluster, to the Jenkins master. I've open a port in HAProxy to connect this slave:
50000: "default/jenkins-svc:50000"
All the remain configuration is pretty straightforward.
My problem is that this connection is very unreliable, sometimes it works, sometimes it gives me connection refused and other times port not reachable.
I'm trying to migrate this solution to production but with these problems i can not do that. I believe, that this problem is related with the way HAProxy deals with those open TCP ports.
So my question is, why this is happening? Is there something i can do, in HAproxy, to ensure that the connection can be set up correctly in the first tentative?

Thanks a lot.

Tiago

**Comment by pasikarkkainen** [comment]
Hi. I'm afraid you forgot to mention which haproxy-ingress version you're using?

**Comment by tiagomiguelsousa** [comment]
Hi.
Sorry for that. I'm using the latest version of HAproxy ingress.
Thanks.

**Comment by jcmoraisjr** [comment]
Hi, please configure a syslog endpoint and provide some access logs from HAProxy.

**Comment by jcmoraisjr** [comment]
Closing due to the lack of feedback. Find us on slack or any other [community option](https://haproxy-ingress.github.io/community/) if this is still an issue.
