### ISSUE TITLE
Support multiple ingress resources with the same host

### ISSUE THREAD

**Issue by bcorijn** [jcmoraisjr/haproxy-ingress#35]
Hi,

I noticed that if you create multiple ingress resources which use the same host, but different path routing setups, only one will "win" and end up getting its config created (I would expect all to be created/merged).
My personal reason for splitting this in multiple resources is that I have an application living under a certain path that handles websockets, which need session affinity, however I don't want all my other apps under that hostname to be sticky.
Would there be support for implementing this, or are there technical limitations that would prevent this from working? I tried taking a look where in the code this would happen, but I don't immediately spot it (must say I'm not that experienced with Go)

**Comment by jcmoraisjr** [comment]
The merge does happen. There are however some known issues related with annotations that change the backend - you should not reuse the same backend eg sometimes with secure-backends true and sometimes false.

I couldn't reproduce here. Please provide some ingress resources that demonstrate this problem.

**Comment by bcorijn** [comment]
Your comment made me try again, and now it works indeed :/ I think I must have done something wrong in combination with the basic auth, but with both of those set up correctly it behaves as expected. Apologies for the false alarm!

**Comment by jcmoraisjr** [comment]
Perhaps you found a race condition. Please reopen this issue if you can provide a step by step sequence that makes ingress behaves unexpectedly.
