### ISSUE TITLE
[Question] How to ingrate haproxy-ingress with GCLB

### ISSUE THREAD

**Issue by rustyx** [jcmoraisjr/haproxy-ingress#353]
How much does haproxy-ingress integrate with GCE when running on GKE? Does it create GCE LB resources like the forwarding rules, target-http-proxies, backend-services, etc.? Doesn't look like it. So how does it work, really?

**Comment by rustyx** [comment]
Hello! Anyone out there!

**Comment by jcmoraisjr** [comment]
Hello, I'm right here but don't know enough about GCE and cloud deployment to help.

**Comment by rustyx** [comment]
Ok no problem, I guess that means the answer is... it doesn't.
