### ISSUE TITLE
[v0.8-snapshot.2] Backend Config Annotation does not show in generated haproxy.cfg 

### ISSUE THREAD

**Issue by KKlapper** [jcmoraisjr/haproxy-ingress#357]
Hello, not sure if this should already work in snapshot.2. Currently backend config annotations to an ingress do not show up in the generated haproxy.cfg file in the corresponding backend section. This worked in v0.7

ingress.kubernetes.io/config-backend: |
   multiline-config
   multiline-config
   multiline-config

**Comment by jcmoraisjr** [comment]
Hi, this is still a missing configuration which will be added before the first beta. Moving the easy part to the end =)

**Comment by jcmoraisjr** [comment]
Hi, already implemented since the first beta. Closing.
