### ISSUE TITLE
createFrontendCertsDir function exits on first cert that is not found, and skip all others that might be correct

### ISSUE THREAD

**Issue by l27-0-0-l** [jcmoraisjr/haproxy-ingress#358]
I had multiple namespaces with multiple ingress objects and various certificates.
Function createFrontendCertsDir copy certificates, but it returns error,  once it can not find some certificate. 

If I have 10 certificates and servers, and non existing certificate was checked 2nd, I'll be left with just one working certificate.

In this way any wrongly configured ingress object can leave other https services without certificate, thus defaulting to default cert. 

It would be great if this loop does not exit on first error, but continue working for certs that it can find.

**Comment by jcmoraisjr** [comment]
I missed the controller version of this issue. In the mean time, either the controller and also the certs listing evolved a lot and maybe this isn't an issue anymore. I'm closing this issue but feel free to fill a new one if such problem can be reproduced with v0.10 - current stable.
