### ISSUE TITLE
Enable OAuth on a per-path basis

### ISSUE THREAD

**Issue by speedst3r** [jcmoraisjr/haproxy-ingress#360]
I have OAuth working successfully with [pusher/oauth2_proxy](https://github.com/pusher/oauth2_proxy) and keycloak, however there are some paths on my domain I do not wish to have OAuth over.

As a feature enhancement, it would be useful to be able to configure OAuth support and then separately enable it on a path basis using an annotation on a path-specific ingress.

**Comment by jcmoraisjr** [comment]
Hi, there are some future plans to oauth config, which include choose protected paths and reuse a single oauth service.

**Comment by jcmoraisjr** [comment]
Added in `v0.12-snapshot.3`. Closing.
