### ISSUE TITLE
Cannot connect to API Server

### ISSUE THREAD

**Issue by nfarhadian** [jcmoraisjr/haproxy-ingress#37]
HAProxy cannot connect to api server and get ingress-default-backend service, because it doesn't have client certificate.

here is the error:
`launch.go:118] no service with name kube-system/ingress-default-backend found: the server has asked for the client to provide credentials (get services ingress-default-backend)`

I have checked ConfigMap parameters to set client certificate, but I haven't find anything relevant.

kubernetes version: 1.7.4

(By the way, it's my first time installing kubernetes and also first time creating an issue on GitHub, I'm really newbie)

**Comment by jcmoraisjr** [comment]
Welcome aboard and thanks for choosing HAProxy as your ingress implementation of choice!

It sounds that you need to authorize ingress in your cluster. Btw I'm working on this doc right now and will ping this same issue as soon as I can merge it.

The fastest way to get it working is adding ingress as a cluster admin.

**Note:** this is a testing environment configuration! Every single app deployed on default namespace will have admin access to the cluster when using the default service account.

```
$ kubectl edit clusterrolebinding/cluster:admin
```

At the end of the file, under `subjects`, add the following permission:

```
- kind: ServiceAccount
  namespace: default
  name: default
```

Change `namespace` to the namespace where HAProxy Ingress is deployed.

**Comment by jcmoraisjr** [comment]
Here is the doc: https://github.com/kubernetes/ingress/tree/master/examples/rbac/haproxy . Let me know if you have any problem updating this same issue.

**Comment by Bajix** [comment]
https://github.com/kubernetes/ingress-nginx/tree/master/examples/rbac/haproxy is broken

**Comment by jcmoraisjr** [comment]
All examples was moved to this same repo. Now rbac doc is [here](https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/rbac).
