### ISSUE TITLE
ingress stick session not working

### ISSUE THREAD

**Issue by asignorette** [jcmoraisjr/haproxy-ingress#373]
Hello friend, how you doing great work....

Could please help with stick session ingress ? I create an Ingress on kubernetes but the stick session isn't showed on google chrome cookie.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    **ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: sticksession**
  generation: 1
  name: my-ingress
  namespace: default
  resourceVersion: "27927012"
spec:
  rules:
  - host: pp.com.br
    http:
      paths:
      - backend:
          serviceName: my-ingress
          servicePort: 8888
status:
  loadBalancer: {}
---------------------------------------
My Service

apiVersion: v1
kind: Service
metadata:
  annotations:
    haproxy.org/check: enabled
    haproxy.org/forwarded-for: enabled
    haproxy.org/load-balance: roundrobin
  creationTimestamp: "2019-08-21T21:53:24Z"
  labels:
    run: pod
  name: my-ingress
  namespace: default
spec:
  clusterIP: 10.97.87.89
  ports:
  - name: port-pod
    port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    run: pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

-----------------------------------------
Controller Config

/ # cd /etc/haproxy/
/etc/haproxy # cat haproxy.cfg 

frontend healthz 
  mode http
  bind 0.0.0.0:1042 name healtz_1
  no log
  monitor-uri /healthz

frontend http 
  mode http
  bind 0.0.0.0:80 name bind_1
  bind :::80 v4v6 name bind_2
  use_backend default--ingress-8080 if { req.hdr(host) -i pp.com.br }
  default_backend haproxy-controller-ingress-default-backend-8080

frontend https 
  mode http
  bind 0.0.0.0:443 name bind_1 alpn h2,http/1.1
  bind :::443 v4v6 name bind_2 alpn h2,http/1.1
  use_backend default--ingress-8080 if { req.hdr(host) -i pp.com.br }
  default_backend haproxy-controller-ingress-default-backend-8080

frontend stats 
  mode http
  bind *:1024
  option http-use-htx
  http-request use-service prometheus-exporter if { path /metrics }
  stats enable
  stats uri /
  stats refresh 10s

backend default--ingress-8080 
  mode http
  balance roundrobin
  option forwardfor
  server SRV_ck0xO 127.0.0.1:8080 disabled check weight 128
  server SRV_MUgUH 10.244.2.215:8080 check weight 128
  server SRV_bDn4s 127.0.0.1:8080 disabled check weight 128
  server SRV_zOnB3 127.0.0.1:8080 disabled check weight 128
  server SRV_gytmv 127.0.0.1:8080 disabled check weight 128
  server SRV_kHZAJ 127.0.0.1:8080 disabled check weight 128
  server SRV_PWQUe 127.0.0.1:8080 disabled check weight 128
  server SRV_4dc9l 127.0.0.1:8080 disabled check weight 128
  server SRV_iRen9 127.0.0.1:8080 disabled check weight 128
  server SRV_xq0Zw 127.0.0.1:8080 disabled check weight 128
  server SRV_Dad33 127.0.0.1:8080 disabled check weight 128
  server SRV_qCozJ 127.0.0.1:8080 disabled check weight 128
  server SRV_oCPQF 127.0.0.1:8080 disabled check weight 128
  server SRV_eTYL5 127.0.0.1:8080 disabled check weight 128
  server SRV_TzCRq 127.0.0.1:8080 disabled check weight 128
  server SRV_u4V6H 127.0.0.1:8080 disabled check weight 128
  server SRV_DFx2t 127.0.0.1:8080 disabled check weight 128
  server SRV_RBP4A 127.0.0.1:8080 disabled check weight 128
  server SRV_LSxl2 127.0.0.1:8080 disabled check weight 128
  server SRV_oDr8E 10.244.3.220:8080 check weight 128
  server SRV_zMiu3 127.0.0.1:8080 disabled check weight 128
  server SRV_hk3iO 127.0.0.1:8080 disabled check weight 128
  server SRV_eUL7V 127.0.0.1:8080 disabled check weight 128
  server SRV_B2EBG 127.0.0.1:8080 disabled check weight 128
  server SRV_TBol5 127.0.0.1:8080 disabled check weight 128
  server SRV_nYmGG 127.0.0.1:8080 disabled check weight 128
  server SRV_qO4CX 127.0.0.1:8080 disabled check weight 128
  server SRV_8U6zf 127.0.0.1:8080 disabled check weight 128
  server SRV_kU754 127.0.0.1:8080 disabled check weight 128
  server SRV_2Glbv 127.0.0.1:8080 disabled check weight 128
  server SRV_iCG3Y 127.0.0.1:8080 disabled check weight 128
  server SRV_GGDLy 127.0.0.1:8080 disabled check weight 128
  server SRV_yrGRR 127.0.0.1:8080 disabled check weight 128
  server SRV_nsBQ6 127.0.0.1:8080 disabled check weight 128
  server SRV_vGAkk 127.0.0.1:8080 disabled check weight 128
  server SRV_Rh7ji 127.0.0.1:8080 disabled check weight 128
  server SRV_PwHrF 127.0.0.1:8080 disabled check weight 128
  server SRV_kaT30 127.0.0.1:8080 disabled check weight 128
  server SRV_JeO9I 127.0.0.1:8080 disabled check weight 128
  server SRV_BtqHx 127.0.0.1:8080 disabled check weight 128
  server SRV_hKewx 127.0.0.1:8080 disabled check weight 128
  server SRV_2Eyhd 127.0.0.1:8080 disabled check weight 128

backend haproxy-controller-ingress-default-backend-8080 
  mode http
  balance roundrobin
  option forwardfor
  server SRV_Ub8GH 127.0.0.1:8080 disabled check weight 128
  server SRV_Lfx3M 127.0.0.1:8080 disabled check weight 128
  server SRV_WoVAV 127.0.0.1:8080 disabled check weight 128
  server SRV_buKI8 127.0.0.1:8080 disabled check weight 128
  server SRV_FMgRd 127.0.0.1:8080 disabled check weight 128
  server SRV_LPvgv 127.0.0.1:8080 disabled check weight 128
  server SRV_5Rw8Q 127.0.0.1:8080 disabled check weight 128
  server SRV_snAlZ 127.0.0.1:8080 disabled check weight 128
  server SRV_gykLo 127.0.0.1:8080 disabled check weight 128
  server SRV_bEy6c 127.0.0.1:8080 disabled check weight 128
  server SRV_wczHk 127.0.0.1:8080 disabled check weight 128
  server SRV_AC5Gc 127.0.0.1:8080 disabled check weight 128
  server SRV_qEpFw 127.0.0.1:8080 disabled check weight 128
  server SRV_fxniV 127.0.0.1:8080 disabled check weight 128
  server SRV_06WaA 127.0.0.1:8080 disabled check weight 128
  server SRV_rDv9P 127.0.0.1:8080 disabled check weight 128
  server SRV_NmedE 127.0.0.1:8080 disabled check weight 128
  server SRV_CYETT 127.0.0.1:8080 disabled check weight 128
  server SRV_RURaT 127.0.0.1:8080 disabled check weight 128
  server SRV_iEh0N 127.0.0.1:8080 disabled check weight 128
  server SRV_EvK8u 127.0.0.1:8080 disabled check weight 128
  server SRV_sKzQa 127.0.0.1:8080 disabled check weight 128
  server SRV_DScHR 127.0.0.1:8080 disabled check weight 128
  server SRV_aioJ2 127.0.0.1:8080 disabled check weight 128
  server SRV_yifQr 127.0.0.1:8080 disabled check weight 128
  server SRV_6EPbH 127.0.0.1:8080 disabled check weight 128
  server SRV_vp2nR 127.0.0.1:8080 disabled check weight 128
  server SRV_syJMY 127.0.0.1:8080 disabled check weight 128
  server SRV_qv3Mi 127.0.0.1:8080 disabled check weight 128
  server SRV_ISqL7 127.0.0.1:8080 disabled check weight 128
  server SRV_k8Fe1 127.0.0.1:8080 disabled check weight 128
  server SRV_J1LSM 127.0.0.1:8080 disabled check weight 128
  server SRV_3RYet 127.0.0.1:8080 disabled check weight 128
  server SRV_aXuhu 127.0.0.1:8080 disabled check weight 128
  server SRV_zxTtG 127.0.0.1:8080 disabled check weight 128
  server SRV_n6M5k 10.244.1.88:8080 check weight 128
  server SRV_9s7Jx 127.0.0.1:8080 disabled check weight 128
  server SRV_TDHgD 127.0.0.1:8080 disabled check weight 128
  server SRV_WFROL 127.0.0.1:8080 disabled check weight 128
  server SRV_eI0i7 127.0.0.1:8080 disabled check weight 128
  server SRV_cMj57 127.0.0.1:8080 disabled check weight 128
  server SRV_fq1Os 127.0.0.1:8080 disabled check weight 128
/etc/haproxy #

**Comment by jcmoraisjr** [comment]
Hi, it sounds you're talking about the haproxytech ingress implementation?

**Comment by oktalz** [comment]
Hi @asignorette, and @jcmoraisjr 
configuration definitely looks like that.

@asignorette please see if possibly you forgot to change ingress controller settings to use this one,
if not, please open issue (and close this one) on haproxytech github.
