### ISSUE TITLE
Using modsecurity SPOE (modsecurity-endpoints configmap option) in 0.7.3 does not work

### ISSUE THREAD

**Issue by andrelop** [jcmoraisjr/haproxy-ingress#374]
Hello,

I'm trying to use modsecurity SPOE through haproxy-ingress.
I've been using it on previous haproxy-ingress versions (0.7.2) and it was working fine.

When updating to haproxy-ingress 0.7.3, it stopped working.
Took me a while to find out what was the real issue, but once I removed the 'modsecurity-endpoints' option from the haproxy-ingress configmap it (haproxy-ingress) started working again (but then I got no WAF).

When I tried version 0.7.2 again, with the exact same 'modsecurity-endpoints' value, everything resumed working again.

In both cases (using version 0.7.2 and 0.7.3) I'm using https://github.com/jcmoraisjr/modsecurity-spoa as the SPOE solution (as daemonset).

I only noticed this issue because I was testing haproxy-ingress options, I had its Pods configured to point to the 'latest' image (using 'image: quay.io/jcmoraisjr/haproxy-ingress' the the manifest) and made a 'kubectl rollout restart daemonset <daemonset_name>'.

I mean, there was no tag and then it fetched 0.7.3. Now it's pinned to 0.7.2 and it's working again.

**Comment by jcmoraisjr** [comment]
Hi, thanks for reporting! I can reproduce a segmentation fault with haproxy 1.8.21, even updating modsec-spoa to the same haproxy version. I'll save a bt and send to the developers.

**Comment by jcmoraisjr** [comment]
Thanks again for reporting this issue. HAProxy 1.8.21 causes a segfault spoe processing.

https://www.mail-archive.com/haproxy@formilux.org/msg34768.html

v0.7.3 was removed from latest and from releases page. Waiting now for haproxy 1.8.22.

**Comment by pasikarkkainen** [comment]
FYI: upstream haproxy 1.8.22 has been released now, with the SPOE fix.

**Comment by jcmoraisjr** [comment]
HI, 1.8.22 image took a couple of days to be created after the release, but now everything is done. v0.7.4 fixes the segfault. Thanks againg @andrelop for reporting! Closing.
