### ISSUE TITLE
fails without permission to read namespace

### ISSUE THREAD

**Issue by waldiTM** [jcmoraisjr/haproxy-ingress#376]
haproxy-ingress supports single-namespace operation, by specifying `--watch-namespace`. In this mode it tries to read the namespace object to verify the connection to the api server. If it lacks permissions to read the namespace object, it dies with the following message:

```
F0829 13:01:42.732416       7 launch.go:197] no watchNamespace with name example found: namespaces "example" is forbidden: User "system:serviceaccount:example:haproxy-ingress" cannot get resource "namespaces" in API group "" in the namespace "example"
```

Reading the namespace object requires a cluster wide permission. This makes it impossible to deploy haproxy-ingress without setting up cluster-wide objects, even if only one namespace should be looked at.

**Comment by jcmoraisjr** [comment]
Hi, finally fixed on v0.10-beta.1. Closing, let me know if you still have any problem.
