### ISSUE TITLE
ELB SSL termination with HSTS and HTTPS redirect?

### ISSUE THREAD

**Issue by idubrov** [jcmoraisjr/haproxy-ingress#38]
Essentially, the same situation as in https://github.com/kubernetes/ingress/issues/314 but with HAProxy Ingress controller.

If I'm terminating SSL on ELB and use HTTP (or PROXY), is there any way to configure this controller to do redirect to HTTPS and return HSTS header?

Seems like, it's not directly supported and the only option I have is to replace the haproxy.tmpl with one that sets up a separate port just for the HTTPS redirect (+ change http frontend to return HSTS). Am I right?

**Comment by jcmoraisjr** [comment]
Please let me know if 74783ec can help.

**Comment by idubrov** [comment]
It looks exactly what I need (though I haven't tried it myself).

Two minor things:

1) It looks to me that `acl is-https-to-http var(txn.hdr_proto) eq https` could be outside of `hasHTTPStoHTTP` condition since it can recognize request as `HTTPS` if it came with `X-Forwarded-Proto: https` no matter if `HTTPStoHTTPPort` is set or not.

2) I find readme a little bit confusing, especially this part:
> this configuration will not work and will either loop because of https redirect or HSTS header will not be added

**Comment by ColDog** [comment]
I tried this out, findings are below: 

I didn't have any issues with HSTS and all that worked well. I actually just ended up setting the `https-to-http` port to `80` which meant it triggered the acl rule on all' traffic for me. I'm not sure if this is how this is meant to be used, but it triggered the desired behaviour for me which is to set `HSTS` headers on both secure and insecure protocols.

HTTPS redirect did not work as I expected. I think this is because the redirect statements are nested under the `UseHTTPS` check: (https://github.com/jcmoraisjr/haproxy-ingress/commit/74783eccd5e7b7a1043cd332c03c31171597cfd1#diff-0aee42afd25a32b87c1c27ad8c705c40R134). I removed these checks on a local branch and everything works as expected.

**Comment by jcmoraisjr** [comment]
@idubrov 

> It looks to me that `acl is-https-to-http var(txn.hdr_proto) eq https` could be outside of `hasHTTPStoHTTP` condition since it can recognize request as HTTPS if it came with `X-Forwarded-Proto: https` no matter if `HTTPStoHTTPPort` is set or not.

The idea here is to declare only what is really needed. One that does ssl offload on HAProxy shouldn't have to know what this strange and unused acl means.

> I find readme a little bit confusing, especially this part:

>> this configuration will not work and will either loop because of https redirect or HSTS header will not be added

Agreed, will do my best rewriting the whole paragraph.

**Comment by jcmoraisjr** [comment]
@ColDog perhaps I missed something. This should be used only behind another load balancer that does the ssl offload for you. Is this your scenario?

**Comment by ColDog** [comment]
@jcmoraisjr Yes this is my scenario. I have an ELB terminating SSL and forwarding all traffic to port 80 where the haproxy-ingress takes over.

I'm running my own fork at the moment which gets the HTTPS redirect working for my use case. This fork is here: https://github.com/jcmoraisjr/haproxy-ingress/compare/master...ColDog:remove-https-checks. I can open a PR for this but admittedly I don't understand very well the consequences of this.

**Comment by jcmoraisjr** [comment]
@ColDog I hope 7083cad solves the redirect issue, let me know if you still have any problem.

**Comment by ColDog** [comment]
Awesome, a much better solution. I will try it out tomorrow!

**Comment by jcmoraisjr** [comment]
@ColDog @idubrov any pending here or this issue can be closed?

**Comment by ColDog** [comment]
This can be closed I can confirm that https://github.com/jcmoraisjr/haproxy-ingress/commit/7083cadb1ead97dcdf4ec1b82b8148a96921fef0 fixes my use case!

**Comment by jcmoraisjr** [comment]
Thank you helping to validate this impl!
