### ISSUE TITLE
Multiple SSL Certificates / SSL Termination does not work

### ISSUE THREAD

**Issue by btnguyen2k** [jcmoraisjr/haproxy-ingress#380]
I am following the example here: https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/tls-termination

However, when I access my foo.bar domain, it always show the default SSL certification. The one configured via "tls[...].secretName does not apply.

Regards,
Thanh Nguyen

**Comment by jcmoraisjr** [comment]
Hi, in the current implementation you need to issue a certificate whose CN or SAN references the domain/host you have configured in the ingress object. Check if your domain and CN/SAN matches.

**Comment by cu12** [comment]
@jcmoraisjr hmm, does that mean that wildcard certificates are not applying here either?

**Comment by ailenli** [comment]
> I am following the example here: https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/tls-termination
> 
> However, when I access my foo.bar domain, it always show the default SSL certification. The one configured via "tls[...].secretName does not apply.
> 
> Regards,
> Thanh Nguyen

If you follow this example，When creating the secret，you should get secret a namespace same with ingress,
kubectl create secret tls tls-secret --cert=tls.crt --key=tls.key -n haproxy-controller

kubectl get ing -n haproxy-controller
NAME   HOSTS     ADDRESS   PORTS     AGE
app    foo.bar             80, 443   2d16h
