### ISSUE TITLE
Specify headers and configuration per backend

### ISSUE THREAD

**Issue by ira-bryndzei** [jcmoraisjr/haproxy-ingress#386]
Is there a possibility to add  an option to specify custom headers and configuration options per backend? For example I have two backends and they have different headers.  Example:
```
backend backend1
    http-request set-header X-Forwarded-Port %[dst_port]
    option httpchk GET /actuator/health HTTP/1.1\r\nHost:\ healthcheck
backend backend2
    http-request del-header Types
    http-request del-header types
```
Current config-backend configmap adds configuration snippet to all backend sections.

**Comment by jcmoraisjr** [comment]
Hi, config-backend is actually an annotation config, you can declare it in the ingress object, or also in the service object if using v0.8. The configmap option if used will act as a default value to all the backends.

**Comment by ira-bryndzei** [comment]
I have multiply backends with different custom headers. How can I with annotation config specify different custom headers for each backend?

**Comment by jcmoraisjr** [comment]
Using the annotation `ingress.kubernetes.io/config-backend` in the ingress object that references the service that creates the backend. If using v0.8 you can also annotate the service itself.

**Comment by ira-bryndzei** [comment]
can't find in documentation how to provide reference to a service in annotation ingress.kubernetes.io/config-backend. Could you please provide an example?

**Comment by jcmoraisjr** [comment]
Hi, there is an example in the config-backend doc: https://github.com/jcmoraisjr/haproxy-ingress#configuration-snippet
