### ISSUE TITLE
Cloudflare and real client IP address

### ISSUE THREAD

**Issue by vitobotta** [jcmoraisjr/haproxy-ingress#398]
Hi, in haproxy's access logs I see Cloudflare IP addresses instead of the actual client IPs. How to fix? Thanks!

**Comment by jcmoraisjr** [comment]
Hi, you can enable proxy protocol on cloudflare and haproxy ingress.

**Comment by vitobotta** [comment]
Hi @jcmoraisjr, I tried that with haproxy and no requests worked. Do I have to do something similar with Cloudflare? I can't find a setting for that. In the meantime I managed to get the correct IP in the application, but it would be nice to see the real IP in haproxy's logs as well.

**Comment by jcmoraisjr** [comment]
Hi, perhaps you're looking for this? https://developers.cloudflare.com/spectrum/getting-started/proxy-protocol/

HAProxy supports proxy protocol v1 and v2.

**Comment by vitobotta** [comment]
Hi @jcmoraisjr , sorry I haven't replied before. I temporarily switched to another ingress while testing things. I am using haproxy again now and am having this problem again. Spectrum is available to Enterprise customers, and I cannot afford it... 

Cloudflare sets the actual client IP in two headers, CF-Connecting-IP and X-Forwarded-For. Is it possible to instruct haproxy so that it takes the IP from one of these headers if present? I am seeing some mentions of acl instructions and other stuff... how do I configure these with haproxy ingress?

Thanks!

**Comment by vitobotta** [comment]
Solved by mounting a config map with the Cloudflare IPs inside the controller containers, and adding this annotation to the ingresses:

```yaml
    ingress.kubernetes.io/config-backend: |
      acl from_cf src -f /etc/haproxy/cf-ips/cf-ips
      http-request set-src req.hdr(CF-Connecting-IP) if from_cf
```

Thanks.
