### ISSUE TITLE
Cross-NameSpace is accessible via Helm Chart installation of haproxy-ingress-controller

### ISSUE THREAD

**Issue by PatelRudra** [jcmoraisjr/haproxy-ingress#400]
Hello All,

I have configured the kubernetes cluster as per the setup guide. But still the haproxy-ingress-controller is trying to pull the ingress configured in different namespace. Let me elucidate my issue with an example.

- There are two namespace in my scenario ie. default and other is wifi
- I have created a ingress in both of this namespaces
- The haproxy-ingress helm is installed in the namespace "wifi"
- Still the controller pod is trying to pull the ingress from default namespace, and this is not allowing my application to work

=> Logs from the haproxy-ingress-controller pod.

[k8s@k8s-master ~]$ kubectl  -n wifi logs haproxy-haproxy-ingress-controller-6cc64dfb75-xchcd --container=haproxy-ingress
I0927 06:26:16.942324       8 launch.go:142] 
Name:       HAProxy
Release:    v0.7.2
Build:      git-94e0f4e
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I0927 06:26:16.942397       8 launch.go:145] Watching for ingress class: haproxy
I0927 06:26:16.942661       8 launch.go:345] Creating API client for https://10.96.0.1:443
I0927 06:26:24.025503       8 launch.go:357] Running in Kubernetes Cluster version v1.14 (v1.14.3) - git (clean) commit 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0 - platform linux/amd64
I0927 06:26:24.029372       8 launch.go:169] validated wifi/haproxy-haproxy-ingress-default-backend as the default backend
I0927 06:26:24.035837       8 controller.go:1528] starting Ingress controller
I0927 06:26:24.043872       8 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"elitesmp", UID:"e5363d22-e0ee-11e9-94d3-fa163e849019", APIVersion:"extensions", ResourceVersion:"11768806", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/elitesmp
I0927 06:26:24.044359       8 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"wifi", Name:"elitesmp", UID:"ac6fbc5a-e0ef-11e9-94d3-fa163e849019", APIVersion:"extensions", ResourceVersion:"11769373", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress wifi/elitesmp
I0927 06:26:29.593283       8 controller.go:1536] running initial sync of secrets
W0927 06:26:29.593898       8 controller.go:961] error obtaining service endpoints: error getting service default/elitesmp from the cache: service default/elitesmp was not found
I0927 06:26:29.613269       8 leaderelection.go:174] attempting to acquire leader lease...
I0927 06:26:29.613775       8 controller.go:332] backend reload required
I0927 06:26:29.622205       8 status.go:199] new leader elected: haproxy-haproxy-ingress-controller-6cc64dfb75-4895z
I0927 06:26:29.655937       8 controller.go:341] ingress backend successfully reloaded...

=> Ingress for both the namespaces.

[k8s@k8s-master ~]$ kubectl  -n wifi get ingresses.networking.k8s.io 
NAME       HOSTS   ADDRESS   PORTS   AGE
elitesmp   *                 80      2m20s
[k8s@k8s-master ~]$ kubectl  -n default get ingresses.networking.k8s.io 
NAME       HOSTS   ADDRESS   PORTS   AGE
elitesmp   *                 80      8m
[k8s@k8s-master ~]$ 

==> Expected output 

+> If I have installed the haproxy-ingress-controller in a specific namespace then it should fetch the ingress for that dedicated namespace only. If you can make it configurable then it would be best for me. like the command line output (allow-cross-namespace  https://github.com/jcmoraisjr/haproxy-ingress#allow-cross-namespace).

**Comment by jenil-shah135** [comment]
Hello PatelRudra,

I understand your use case that you want to limit HAProxy Ingress to watch for ingress of specific namespace.For that you need to use --force-namespace-isolation and --watchNamespace parameter instead of --allow-cross-namespace
