### ISSUE TITLE
Add support for cert manager

### ISSUE THREAD

**Issue by thekalinga** [jcmoraisjr/haproxy-ingress#41]
As per the [kube lego team](https://github.com/jetstack/kube-lego/issues/251#issuecomment-326255475), they are planning on moving away from kube lego to a more standardised way to automatically provision TLS certificates for Kubernetes.

This project is currently located [here](https://github.com/jetstack-experimental/cert-manager)

Would be great if the support for this new library can be added.

Thanks

**Comment by jcmoraisjr** [comment]
Imo this shouldn't even be necessary. The only thing I did on kube-lego was decoupling some hardcoded nginx confs.

Perhaps @munnerz could clarify?

**Comment by munnerz** [comment]
So cert-manager itself should work with any ingress controller that follows the ingress specification now.

There were a few issues that were preventing us doing this with kube-lego, that have all been resolved:

1. Differing path formats between ingress controllers - previously we set up a new path for the users domain like `/.well-known/acme-challenge/`, or `/.well-known/acme-challenge/*` for GCE. This meant that we had to explicitly understand the wildcard syntax for the target ingress controller as the ingress spec is currently lacking in this regard. In cert-manager, we set up an ingress with a route `/.well-known/acme-challenge/<acme-validation-token>`. This means we no longer need to use wildcards at all.

2. GCE binding one ingress <> one IP address, whereas nginx/haproxy (correctly) 'merging' ingress resources into one - this meant we had to treat GCE in a different way to other ingress controllers, again meaning we had to 'understand' each controller. Instead, we now have two fields in the acme configuration for domain validation. `ingressClass` and `ingressName`. Only one of these should be specified, and if `ingressClass` is specified, a *new* Ingress resource will be created just for that route (ie. in a way compatible with nginx & haproxy), and if `ingressName` is specified, the specified Ingress resource will be *modified* to include that route temporarily. This should allow users to decide how they want the validation to work depending on the Ingress controller in use.

I will try and test cert-manager out with the haproxy ingress controller at some point, but if you do have a chance to do it yourself then I've updated the README on cert-manager recently with a more complete quick start guide!

**Comment by munnerz** [comment]
An example of this config can be found here, by the way! https://github.com/jetstack-experimental/cert-manager/blob/master/docs/acme-cert.yaml#L19

**Comment by dobesv** [comment]
I set this up with cert-manager today and it worked great, this issue can probably be closed.

**Comment by jcmoraisjr** [comment]
Tks @dobesv, closing.
