### ISSUE TITLE
Whitelist ratelimit on UserAgent or Header? 

### ISSUE THREAD

**Issue by bcorijn** [jcmoraisjr/haproxy-ingress#410]
Not all client are that easily identifiable by IP address, sometimes I have to rely on UserAgents or Headers to whitelist clients from ratelimiting. I know these are very un-reliable mechanisms, but it would still be great to be able to whitelist on other ACL's than just IP CIDR. Maybe even passing in your own ACLs' could be a possibility?

**Comment by jcmoraisjr** [comment]
Hi, you can use a custom backend config with a http-request deny and an acl
with hdr() and the list of allowed values.

~jm


Em sex, 11 de out de 2019 03:39, Bruno <notifications@github.com> escreveu:

**Comment by bcorijn** [comment]
Doh, I clearly was a bit too distracted while posting this. I wanted to ask about whitelisting the ratelimiting based on these elements. I don't believe I can easily do this with a custom back- or front-end config? 
One of the usecases would be to whitelist known good bots/spiders.

**Comment by jcmoraisjr** [comment]
Hi, I was a bit distracted as well when was answering you. And yes, you can
place anything a haproxy backend supports in the custom backend config.
Have a look at the exemple in the doc, just use a multi line config.

~jm



Em sex, 11 de out de 2019 07:45, Bruno <notifications@github.com> escreveu:

**Comment by bcorijn** [comment]
Hey @jcmoraisjr, sorry for leaving this for so long. I didn't think about doing it in a backend config!
Only question I have is how to manage the stick-table name, as that gets automatically named to the back- or front-end it is named in. Should I "predict" the name of the backend in my multiline config? Should (can?) I define a frontend just for the stick table?

**Comment by jcmoraisjr** [comment]
Hi, perhaps you can have v0.8 a chance - all the rate limiting and its whitelist was moved to the backend without internal names - no need to predict anymore. Please give some feedback on this.

**Comment by bcorijn** [comment]
Managed to get it all up and running on the 0.9 snapshot! Forgot that you actually don't *need* to specify a backend name to refer to a stick table, so without that it worked perfectly.
