### ISSUE TITLE
add CF-Connecting-IP header

### ISSUE THREAD

**Issue by Justluckyg** [jcmoraisjr/haproxy-ingress#411]
Hi,

I am currently using haproxy-ingress as my ingress controller in my GKE kubernetes stack behind Cloudflare proxy.

My haproxy-ingress are being sent to my rsyslog endpoint but after putting the urls behind Cloudflare proxy, the real source ip showing cloudflare instead of the real ip.

Cloudflare recommend that i add  CF-Connecting-IP header

How do i add it in configmap?

Thanks

**Comment by jcmoraisjr** [comment]
Hi, you can choose between configure proxy-protocol both in Cloudflare and
haproxy-ingress, or use `capture header` in the config-frontend configmap
option and the captured value in a custom logging format.

hth

~jm




Em ter, 15 de out de 2019 09:12, Justluckyg <notifications@github.com>
escreveu:
