### ISSUE TITLE
Allow RegExp for hostnames

### ISSUE THREAD

**Issue by Scukerman** [jcmoraisjr/haproxy-ingress#43]
I need to have a possibility to set a hostname as a regular expression, e.g. `[a-z0-9]{10}.domain.com`

AFAIK, Ingress rules don't support it because it wasn't expected to use it that way:
```
The Ingress "test-frontend" is invalid: spec.rules[0].host: Invalid value: "[a-z0-9]{10}.domain.com": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

So I believe that it could be implemented via custom annotations.

**Comment by jcmoraisjr** [comment]
Perhaps this could be done inside [server-alias](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#server-alias) annotation. If your alias sounds like a regex, a regex acl would be used to match your domain.

Vacation in the next three weeks so this will take a while. Anyway I'll try to include in the current release cycle (0.4) if the implementation doesn't cause any side effect.
