### ISSUE TITLE
What happened to the docs?

### ISSUE THREAD

**Issue by dpedu** [jcmoraisjr/haproxy-ingress#432]
I see README.md was modified recently with the message `[docs] remove doc from the README`.

When I click the "See the documentation on haproxy-ingress.github.io/docs" link in the readme I am taken to some web page with links to what looks like it should be different types of documentation. If I click into subsection of the docs all the pages looks like placeholders.

Screenshots:

<img width="1010" alt="Screen Shot 2019-10-29 at 10 18 51 AM" src="https://user-images.githubusercontent.com/1266188/67791953-90240080-fa35-11e9-8ef3-3a62f2da4a39.png">

and

<img width="743" alt="Screen Shot 2019-10-29 at 10 19 02 AM" src="https://user-images.githubusercontent.com/1266188/67791959-92865a80-fa35-11e9-9234-c92cfc983b32.png">

This is pretty confusing since last time I looked at this project the documentation was readily available. But now, I'm not even sure if this is the same haproxy ingress implementation I installed in the past.

**Comment by jcmoraisjr** [comment]
Hi, thanks for reporting the not-so-clear approach, I'll describe a bit more what changed, where is what and so on.

I think you're looking for this: https://haproxy-ingress.github.io/docs/configuration/keys/

In the left side you have also the doc of the command-line options. In the right side you have links to an internal section inside that page.

Here is the doc in the old format: https://github.com/jcmoraisjr/haproxy-ingress/tree/release-0.8

Please let me know if there is anything else that could be improved.

**Comment by jcmoraisjr** [comment]
Thanks again for the hints, I've just updated the repo's readme file in order to references the most relevant links. Closing.
