### ISSUE TITLE
no ssl redirect for a specific path ？

### ISSUE THREAD

**Issue by cynial** [jcmoraisjr/haproxy-ingress#435]
Hi, is it possible to make this? I tried, but it didn't work out.

```
# For /app, do not redirect http to https automatically
http://xxx.com/app -> http://xxx.com/app
https://xxx.com/app -> https://xxx.com/app

# For others, redirect http to https automatically
http://xxx.com -> https://xxx.com
https://xxx.com -> https://xxx.com
http://xxx.com/hello -> https://xxx.com/hello
https://xxx.com/hello -> https://xxx.com/hello
````

**Comment by jcmoraisjr** [comment]
Hi, this should work if you create two distinct ingress, one with path `/` and `ssl-redirect` annotation `"true"`, another one with path `/app` and `ssl-redirect` annotation `"false"`.

**Comment by cynial** [comment]
Thanks, it should work. I also make it with `no-tls-redirect-locations: "/app"`, though it's global  configuration.
