### ISSUE TITLE
Routing to internal service loadbalanced by ingress

### ISSUE THREAD

**Issue by cjroebuck** [jcmoraisjr/haproxy-ingress#438]
I have two 'layers' of services in my app, the first one is a thin 'api' layer which is exposed via the ingress. It makes a call to a second service, let's call this the 'engine' service. This engine service is designed to be called privately via the api service:
```
+------> LB +---> INGRESS +---> API SVC +---> ENGINE SVC
```
The engine service is quite a heavy process and is backed by many pods, so efficient loadbalancing is really important to distribute the load evenly. If I send requests to the default kubernetes provided service e.g. 'http://engine.namespace.svc', it ends up not distributing the requests efficiently to the backend pods - one pod ends up taking the majority of the requests and the rest of the pods are sat empty. (For me this seems to defeat the point of the default k8s service and hpa but that is a separate point...!).

If I expose the engine service via ingress and route requests back out to the publicly addressable ingress e.g. engine.example.com, then haproxy loadbalances the requests a lot better than the default kube-proxy 'random' ip-tables implementation which k8s service uses.
```
                HOST: ENGINE.EG.COM
          +-----------------------+
          |                       |
          |                       +
          |                +---> API
          v                |
 +------> LB +---> INGRESS |
                           |
                           +---> ENGINE
```

But this 'feels' like a bit of a hack in order to get haproxy loadbalancing for an internal service. Is this the right way of doing what I want? I cannot find any docs that deal with using ingress to loadbalance internal services and how to route to them. 

PS I cannot switch to `ipvs` based routing as i'm using a hosted k8s implementation (digitalocean) and seemingly have little control over how kube-proxy is initialised.

**Comment by jcmoraisjr** [comment]
Hi, in fact haproxy ingress properly implements only the public network => published service routing, the internals should be done via kube-proxy, kube-router, etc. A service mesh implementation like linkerd or istio should help here to do it in the right way. Otoh I don't see your approach as a hack - it just isn't as nice as if you're using a service mesh. And you can also use whitelist to deny access from the world.
