### ISSUE TITLE
Upgrade kubernetes client to 1.15.5 (or the latest version)

### ISSUE THREAD

**Issue by rikatz** [jcmoraisjr/haproxy-ingress#441]
As far I've mapped to allow this migration:

* [x] Migrate ``pkg/common/net/ssl/ssl_test.go`` as it uses a 'triple' package which was removed from client-go. Need to rewrite this test, a suggestion is to copy it from ingress-nginx as it's almost the same thing (giving also the right credits to them)

* [x] Remove any reference to import 'k8s.io/kubernetes' and changed it to 'k8s.io/api' which is the right import. Mapped by now:  ``pkg/common/ingress/status/status_test.go`` and ``pkg/common/ingress/controller/backend_ssl_test.go``

* [x] In ``store/main.go`` remove k8s.io/kubernetes/pkg/util/node and add a const ``const nodeUnreachablePodReason = "NodeLost"`` to replace this call, as this was the only reference to node package which uses k8s.io/kubernetes, which should not be used (need to map the kubernetes client-go issue here)

* [x] In ``pkg/common/k8s/main.go`` replace all kubeClient.Core() to kubeClient.CoreV1()

* [x] In ``pkg/common/ingress/status/status.go`` replace all client.Extensions().Ingresses client.ExtensionsV1beta1().Ingresses

* [x] Change the leader election process from channels to context, as required by the new client-go (may the force be with us on this!)

**Comment by jcmoraisjr** [comment]
Hi, welcome again to haproxy ingress and thank you so much for the great job on the new PRs.

All `pkg/common/*` packages are pretty deprecated, about 80% of them should be removed on v0.10 which should also fix most of this backlog, if not all. Perhaps we can workaround on v0.9 on behalf of the client upgrade, I'll have a look as soon as the next and latest v0.8 beta is out.

**Comment by jcmoraisjr** [comment]
Hi, done in v0.9-snapshot.3, thanks! Closing.
