### ISSUE TITLE
Support for type LoadBalancer service

### ISSUE THREAD

**Issue by igoratencompass** [jcmoraisjr/haproxy-ingress#448]
Hi,

Just wonder if support for type LoadBalancer is possible or planned for the controller for convenient integration with cloud providers?

Thanks,

**Comment by jcmoraisjr** [comment]
Hi, is this related with #93 ? Let me know if I can help - perhaps evolving some doc.

**Comment by igoratencompass** [comment]
It certainly is! Thanks for the help and all the work invested in this awesome controller, very much appreciated!
