### ISSUE TITLE
Controller metrics

### ISSUE THREAD

**Issue by cu12** [jcmoraisjr/haproxy-ingress#449]
Recently I experienced an issue where a customer used a certificate in windows format line endings, which caused the controller bail out on parsing configuration.

```
[ALERT] 317/212427 (482) : parsing [/etc/haproxy/haproxy.cfg:27258] : 'bind unix@/var/run/haproxy-https.sock' : unable to load SSL private key from PEM file '/ingress-controller/ssl/shared-frontend/default-secret-32bc8.pem'.
[ALERT] 317/212427 (482) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 317/212427 (482) : Fatal errors found in configuration.
E1114 21:24:28.238389       8 controller.go:337] unexpected failure restarting the backend:
exit status 1
```

I'll make sure we convert the certificate to unix format on our system, although there might be different cases, where configuration parse fails.

My question is, if you plan to add a controller metric we could scrape in order to have alert upon failed backend reloads?

**Comment by jcmoraisjr** [comment]
Hi, sure, a couple of useful metrics are already in the backlog but I also agree that the succeeded restart is the most important one. Perhaps we start fast and only with this one.

**Comment by jcmoraisjr** [comment]
Hi, metrics had a big step forward on v0.10. There is an example [here](https://haproxy-ingress.github.io/docs/examples/metrics/) describing how it works. Closing.
