### ISSUE TITLE
Publish ELB FQDN instead of IP address

### ISSUE THREAD

**Issue by bcorijn** [jcmoraisjr/haproxy-ingress#450]
Hi Joao,

I'm trying to get haproxy-ingress to play nicely with external-dns but so far I'm not getting far. If I do a `kubectl get ing` and check the address column, it shows me the IP's of the nodes that run the containers that are being fronted by HAProxy instead of the ELB IPs. Getting the ELB IP's would work or even nicer if there was the option instead of publishing the ELB FQDN. This way external-dns could update my AWS Route53 records immediately as a CNAME/ALIAS record (but that is unrelated here, externaldns takes care of that) instead of A records. 

This can at this moment already be seen when checking the External-IP of the LoadBalancer service of the haproxy-service. [The Nginx ingress allows you to mark a service that is fronting the ingress controller as the address to achieve this functionality](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#why-is-externaldns-only-adding-a-single-ip-address-in-route-53-on-aws-when-using-the-nginx-ingress-controller-how-do-i-get-it-to-use-the-fqdn-of-the-elb-assigned-to-my-nginx-ingress-controller-service-instead). Would something similar be possible?

Thanks!

**Comment by jcmoraisjr** [comment]
Hi, did you try [publish-service](https://haproxy-ingress.github.io/docs/configuration/command-line/#publish-service) command-line arg? I'm not a cloud user/expert, so please let me know if this what you're looking for.

**Comment by bcorijn** [comment]
I must've been using the wrong search-terms in the docs as I swear I looked for it! But exactly what I needed, thanks!
