### ISSUE TITLE
panic reading endpoint data

### ISSUE THREAD

**Issue by rossbeazley** [jcmoraisjr/haproxy-ingress#454]
it crashes for me on startup

```
I1116 21:52:42.247572       6 launch.go:151] 
Name:       HAProxy
Release:    v0.9-snapshot.1
Build:      git-6e8fd1f
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I1116 21:52:42.247906       6 launch.go:154] Watching for ingress class: haproxy
I1116 21:52:42.248444       6 launch.go:368] Creating API client for https://10.96.0.1:443
I1116 21:52:44.748944       6 launch.go:380] Running in Kubernetes Cluster version v1.10 (v1.10.13) - git (clean) commit 954ff68d59e9dc62fa8252ffa9023a90ff8a358c - platform linux/arm
I1116 21:52:44.841879       6 launch.go:179] validated ingress-controller/ingress-default-backend as the default backend
I1116 21:52:46.637936       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"pydio-rossbeazley-co-uk-ingress", UID:"43d8b610-0710-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7043414", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/pydio-rossbeazley-co-uk-ingress
I1116 21:52:46.638012       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"trackmytrain-ingress", UID:"1fface82-04cf-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7043412", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/trackmytrain-ingress
I1116 21:52:46.638044       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"www-rossbeazley-co-uk-ingress", UID:"c6e5feef-0858-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7043413", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/www-rossbeazley-co-uk-ingress
I1116 21:52:46.638076       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"nas-web-ingress", UID:"371c58b6-0521-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7043415", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/nas-web-ingress
W1116 21:52:46.819661       6 controller.go:135] using auto generated fake certificate due to an error reading default TLS certificate: secret ingress-controller/tls-secret was not found
I1116 21:52:48.627807       6 controller.go:1576] starting Ingress controller
I1116 21:52:48.627943       6 controller.go:252] Starting HAProxy update id=1
E1116 21:52:48.628478       6 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/signal_unix.go:367
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:141
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:91
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:273
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:252
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:127
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:87
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:273
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:274
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:182
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfdd781]

goroutine 101 [running]:
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x116b6c0, 0x1b95180)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils.newEndpointAddr(0xc42087b138, 0x50, 0xc4202f70e0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:141 +0x51
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils.CreateEndpoints(0x1b34e80, 0xc4201fa560, 0xc42064ef00, 0xc4205becd0, 0xc420232000, 0x12d3b86, 0x10, 0x1bcb280, 0x0, 0xc420416736, ...)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:91 +0x1f0
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).addEndpoints(0xc42043c5b0, 0xc42064ef00, 0xc4205becd0, 0xc4201ed680, 0xc42046c9f0, 0xc42046d290)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:273 +0x85
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).addBackend(0xc42043c5b0, 0xc42046c870, 0xc420417e40, 0x19, 0xc420417de0, 0x13, 0x132a4ec, 0x2, 0xc42046c9f0, 0xc4201ecd80, ...)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:252 +0x54b
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).syncIngress(0xc42043c5b0, 0xc420476db0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:127 +0x661
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).Sync(0xc42043c5b0, 0xc4203f1680, 0x4, 0x4)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:87 +0x46
github.com/jcmoraisjr/haproxy-ingress/pkg/controller.(*HAProxyController).SyncIngress(0xc4201080e0, 0x11b16c0, 0xc42024a820, 0x5e4ce3e6b1124a57, 0xb80c6b36be03ca85)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:273 +0x3fb
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).syncIngress(0xc42039e0a0, 0x11b16c0, 0xc42024a820, 0xc4256d5920, 0x188148487)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:274 +0xf22
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.syncIngress)-fm(0x11b16c0, 0xc42024a820, 0xa, 0xc420871d68)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:182 +0x3e
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).worker(0xc4202a2810)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112 +0x35b
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.worker)-fm()
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x2a
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4201217a8)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42087bfa8, 0x3b9aca00, 0x0, 0xc420333e01, 0xc42005aa20)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4201217a8, 0x3b9aca00, 0xc42005aa20)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).Run(0xc4202a2810, 0x3b9aca00, 0xc42005aa20)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x55
created by github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).Start
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:1596 +0x3d9
```

**Comment by jcmoraisjr** [comment]
Hi, yes, of course! Any problem with any tagged code or untagged code from master is welcome.

Can you reproduce this always? Can you also reproduce with v0.8-beta.4 and v0.7.4?

**Comment by rossbeazley** [comment]
yup, spin up the deployment and boom.

my current stable deployment is 
Name:       HAProxy
Release:    v0.7.4
Build:      git-07754d6

and i use this (at home) with no problems. My reason for jumping ahead is in an attempt to get pydio-cells working, they have introduced a new sync client that uses grpc (h2) and currently i have to do ssl-offload to make this work.

Ive just tried this (once) with 0.8-beta.4 and get segfaults

Name:       HAProxy
Release:    v0.8-beta.4
Build:      git-3d265b2
Repository: https://github.com/jcmoraisjr/haproxy-ingress
I1117 09:20:34.554710       6 launch.go:154] Watching for ingress class: haproxy
I1117 09:20:34.555045       6 launch.go:364] Creating API client for https://10.96.0.1:443
I1117 09:20:34.756095       6 launch.go:376] Running in Kubernetes Cluster version v1.10 (v1.10.13) - git (clean) commit 954ff68d59e9dc62fa8252ffa9023a90ff8a358c - platform linux/arm
I1117 09:20:39.032671       6 launch.go:179] validated ingress-controller/ingress-default-backend as the default backend
I1117 09:20:44.940550       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"pydio-rossbeazley-co-uk-ingress", UID:"43d8b610-0710-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7149289", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/pydio-rossbeazley-co-uk-ingress
I1117 09:20:44.940677       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"trackmytrain-ingress", UID:"1fface82-04cf-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7149291", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/trackmytrain-ingress
I1117 09:20:44.940928       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"www-rossbeazley-co-uk-ingress", UID:"b3db00c5-08c4-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7149288", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/www-rossbeazley-co-uk-ingress
I1117 09:20:44.941118       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"nas-web-ingress", UID:"371c58b6-0521-11ea-89d8-b827eb8d801c", APIVersion:"extensions", ResourceVersion:"7149290", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/nas-web-ingress
W1117 09:20:45.074697       6 controller.go:135] using auto generated fake certificate due to an error reading default TLS certificate: secret ingress-controller/tls-secret was not found
I1117 09:20:45.535101       6 controller.go:1575] starting Ingress controller
I1117 09:20:45.535215       6 controller.go:274] Starting HAProxy update id=1
I1117 09:20:45.535571       6 leaderelection.go:174] attempting to acquire leader lease...
E1117 09:20:45.535789       6 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:509
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/signal_unix.go:367
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:141
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:91
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:273
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:252
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:127
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:87
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:300
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:274
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:182
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59
/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfdcfa1]

goroutine 103 [running]:
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x116a800, 0x1b94180)
	/home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:491 +0x283
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils.newEndpointAddr(0xc420783138, 0x50, 0xc42078b680)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:141 +0x51
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils.CreateEndpoints(0x1b33ea0, 0xc4204960a0, 0xc4206f0780, 0xc4205a31d0, 0xc420804bc0, 0x12d2dae, 0x10, 0x1bca260, 0x0, 0xc4202221f6, ...)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/utils/services.go:91 +0x1f0
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).addEndpoints(0xc420431730, 0xc4206f0780, 0xc4205a31d0, 0xc4206b6c00, 0xc4208061b0, 0xc420806330)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:273 +0x85
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).addBackend(0xc420431730, 0xc420806150, 0xc42039eea0, 0x19, 0xc42039ee80, 0x13, 0x1329427, 0x2, 0xc4208061b0, 0xc4206b6800, ...)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:252 +0x54b
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).syncIngress(0xc420431730, 0xc420594db0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:127 +0x661
github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress.(*converter).Sync(0xc420431730, 0xc4208048e0, 0x4, 0x4)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/converters/ingress/ingress.go:87 +0x46
github.com/jcmoraisjr/haproxy-ingress/pkg/controller.(*HAProxyController).SyncIngress(0xc4204be2a0, 0x11b0a00, 0xc4203aea40, 0xc42043d200, 0xc4206f7a00)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/controller/controller.go:300 +0x3fb
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).syncIngress(0xc42024c8c0, 0x11b0a00, 0xc4203aea40, 0xc41fe67067, 0x29a13b849)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:274 +0xf22
github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.syncIngress)-fm(0x11b0a00, 0xc4203aea40, 0xa, 0xc4206f7d68)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:182 +0x3e
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).worker(0xc4203f0b10)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:112 +0x35b
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).(github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.worker)-fm()
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x2a
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4204abfa8)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420783fa8, 0x3b9aca00, 0x0, 0xc42010b301, 0xc4201c6480)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4204abfa8, 0x3b9aca00, 0xc4201c6480)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/jcmoraisjr/haproxy-ingress/pkg/common/task.(*Queue).Run(0xc4203f0b10, 0x3b9aca00, 0xc4201c6480)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/task/queue.go:59 +0x55
created by github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller.(*GenericController).Start
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/pkg/common/ingress/controller/controller.go:1595 +0x3d9

**Comment by rossbeazley** [comment]
FYI 
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.13", GitCommit:"954ff68d59e9dc62fa8252ffa9023a90ff8a358c", GitTreeState:"clean", BuildDate:"2019-02-13T11:03:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}

I am running the ingress controller on an amd64 arch

**Comment by jcmoraisjr** [comment]
Hi thanks for the detailed backtrace and explanations. v0.8+ has a wrong assumption about endpoint data. #455 should fix this, you can check yourself or wait one or two days when snapshot.2 should be tagged.

Btw just to let you know about v0.9 stability: we also need h2 on the backend side and will start using v0.9 on an staging environment. We should partially upgrade prod in a week or so.

**Comment by jcmoraisjr** [comment]
Hi, v0.9-snapshot.2 was just released and should fix this issue. Closing. Any other v0.9 related issue is very welcome.
