### ISSUE TITLE
Provide request header with client's certificate fingerprint

### ISSUE THREAD

**Issue by Scukerman** [jcmoraisjr/haproxy-ingress#46]
What do you think on providing it if client certificates are allowed.
Quick workaround that I have used so far is:
```
frontend httpsfront-{{ $host }}
...
{{/* Client certificate SHA1 fingerprint */}}
{{ if ne $authSSLCert.CAFileName "" }}
    http-request set-header Cert-Fingerprint-Sha1 %[ssl_c_sha1,hex]
{{ end }}
...
{{ if eq $cfg.Forwardfor "add" }}
    reqidel ^X-Forwarded-For:.*
    option forwardfor
```

**Comment by jcmoraisjr** [comment]
Both fingerprint and DN are welcome headers. Perhaps also the whole x509 cert in PEM format behind an annotation and a configmap option. Couldn't find howerver in a fast sarching some naming pattern to be used on such header names.

**Comment by Scukerman** [comment]
I would suggest using `X-SSL-Client-DN` and `X-SSL-Client-SHA1`. I've seen these names a lot.

**Comment by Scukerman** [comment]
@jcmoraisjr  Could you start implementing at least one of custom annotations? I would look at it and made something useful. For instance, support of HTTP2.

**Comment by jcmoraisjr** [comment]
I'm planning to add SHA1, CN and DN headers without config before fork to the 0.4 release cycle, and will implement new annotations and configmap to all remaining options after that. SHA1, CN and DN only will meet your needs?

**Comment by Scukerman** [comment]
Sure. At the moment I need only SHA1.

**Comment by jcmoraisjr** [comment]
Implemented in dc1233e , please let me know if you have any problem.

**Comment by Scukerman** [comment]
Yep, it's all okay.

**Comment by jcmoraisjr** [comment]
@Scukerman I'm closing this issue and will add a complete solution - more headers, configmap options and annotations - in the backlog to be added to the next release. Feel free to update here if you find any problem or suggestion. Tks!
