### ISSUE TITLE
Update haproxy to version 1.8.23

### ISSUE THREAD

**Issue by pasikarkkainen** [jcmoraisjr/haproxy-ingress#462]
haproxy-ingress v0.7 and v0.8 branches should be updated to haproxy v1.8.23, as it fixes a security issue with http/2, and also contains bugfixes.

"[ANNOUNCE] haproxy-1.8.23":
https://www.mail-archive.com/haproxy@formilux.org/msg35490.html

**Comment by jcmoraisjr** [comment]
Hi, v0.7.5 tagged and v0.8 branch also updated! Closing.
