### ISSUE TITLE
Unnecessary http to https redirects without TLS host set in ingress object

### ISSUE THREAD

**Issue by cu12** [jcmoraisjr/haproxy-ingress#464]
Using `beta.5` I experienced a change in controllers behaviour, where plain http sites are redirected to https unless told otherwise with `ssl-redirect` annotations.

I understand that `ssl-redirect: true` is the default setting, but using `0.7.4` this wasn't happening. 

relevant configs from the controller:

```
  extraArgs:
    default-ssl-certificate: "ingress/default-tls"
```

a sample ingress object with TLS being empty, this should not be redirected:
```
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "annotations": {
            "kubernetes.io/ingress.class": "blahblah"
        },
        "name": "redacted",
        "namespace": "default",
    },
    "spec": {
        "rules": [
            {
                "host": "www.redacted.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "redacted",
                                "servicePort": 80
                            },
                            "path": "/"
                        }
                    ]
                }
            },
            {
                "host": "redacted.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "redacted",
                                "servicePort": 80
                            },
                            "path": "/"
                        }
                    ]
                }
            }
        ],
        "tls": [
            {}
        ]
    }
}
```

I can see that in `_global_https_redir.map` site has the redirect set.

```
/etc/haproxy/maps # grep redacted.com _global_https_redir.map
redacted.com/ yes
www.redacted.com/ yes
```

another object using the default TLS cert set in `extraArgs`, this is redirected to https correctly
```
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "annotations": {
            "kubernetes.io/ingress.class": "blahblah"
        }
        "name": "another_redacted",
        "namespace": "default",
    },
    "spec": {
        "rules": [
            {
                "host": "another_redacted.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "another_redacted",
                                "servicePort": 80
                            },
                            "path": "/"
                        }
                    ]
                }
            }
        ],
        "tls": [
            {
                "hosts": [
                    "another_redacted.com"
                ]
            }
        ]
    }
}
```

Is this the expected behaviour? I'd say the controller shall only set http to https redirect whenever the `tls[].hosts[]` is non-empty, otherwise it shouldn't.

ps: I must say that beta.5 already scales way better in handling thousands of sites (mixture of http/https) than 0.7.4 did, kudos!

**Comment by jcmoraisjr** [comment]
Hi thanks! v0.8+ is also flying on our environment as well. 3x less latency and about 20x max throughput.

Regarding your findings you're completely right. The tls config of the v0.8 controller is being used only to match the domains of a provided cert but ignored regarding ssl redirect.

Please just confirm if you reproduce the following behaviour on old/v0.7/other controllers: if https request is done to a domain without tls, it will also work instead of 404?

**Comment by prometherion** [comment]
@jcmoraisjr I could take care of this bug if you don't mind

**Comment by jcmoraisjr** [comment]
Hi @prometherion of course I don't mind, any help is very much appreciated. But this is already fixed #465

**Comment by cu12** [comment]
I can confirm that fix works fine 🙏

**Comment by alanpearce** [comment]
This was actually a breaking change for us. We didn't have `tls` configured for each ingress when we switched from an nginx ingress controller to haproxy-ingress and SSL redirection worked by default (since it is enabled by default). We had to add `tls` properties to all of our ingresses just because of this "bug". Just wanted to raise awareness for backwards compatibillty.

**Comment by jcmoraisjr** [comment]
Hi, I can confirm that backward compatibility is a first class citizen for us, we maintain compatibility as much as we can, when it's not possible changelog will say where and why, and usually there is a config option that can be used to not break deployments out there. Although backward compatibility to be maintained is between v0.7 and v0.8 (therefore "bug"), I'm sorry about any inconvenience. Perhaps it's a bit late but I'm fine with a config option that changes this behavior, let me know if this is still an option.

**Comment by alanpearce** [comment]
It's fine, we've updated our ingresses now. I just wanted to add the info in case anybody else encountered this issue.
