### ISSUE TITLE
Cen't get the real IP of the user

### ISSUE THREAD

**Issue by vitobotta** [jcmoraisjr/haproxy-ingress#485]
HI! I am struggling with a stupid problem.... In the haproxy logs I never see the actual IP of the client, but some internal IP, like 10.42.0.1. And of course my app sees the wrong IP as well.

I tried many different settings with the same result. I currently have haproxy installed with these settings:

```
    helm \
      upgrade --install \
      --namespace haproxy-ingress \
      --set controller.hostNetwork=false \
      --set controller.kind=DaemonSet \
      --set controller.daemonset.useHostPort=true \
      --set controller.stats.enabled=true \
      --set controller.stats.port=1936 \
      --set controller.metrics.enabled=true \
      --set controller.logs.enabled=true \
      --set defaultBackend.enabled=true \
      --set controller.service.type=NodePort \
      --set controller.service.externalTrafficPolicy=Local \
      haproxy-ingress \
      incubator/haproxy-ingress
```

I don't have a LoadBalancer service because my VPS provider doesn't offer that service. And there is nothing in front of haproxy now, all traffic goes directly to haproxy. Why is the IP of the client as reported wrong?

Thanks a lot in advance.

**Comment by jcmoraisjr** [comment]
Hi, you can try change `controller.hostNetwork` to `true`.

**Comment by vitobotta** [comment]
Hi @jcmoraisjr , that did the trick - thanks!
