### ISSUE TITLE
Unable to override ingress-class(?)

### ISSUE THREAD

**Issue by dhensen** [jcmoraisjr/haproxy-ingress#49]
Hi!
Current implementation looks like if you set `--ingress-class=to_some_value` it will always be overwritten to be set to `haproxy`:

https://github.com/jcmoraisjr/haproxy-ingress/blob/08740835e7ab26eea07b10e1a1b233aacdf124f8/pkg/controller/controller.go#L106-L110

Is this the correct behaviour? If so can you please explain why it needs to be fixed to haproxy? I need to have multiple haproxy ingress controllers deployed with different ingress class names.

If this is a bug/missing feature I would be happy to submit a PR.

**Comment by jcmoraisjr** [comment]
This is just the declaration of a default value and shouldn't override what
you declare in the command line.

Cannot test myself in the next few days, if you confirm something should be
fixed I'll be happy to revise and merge it.

--jm


Em 15/09/2017 00:00, "Dino Hensen" <notifications@github.com> escreveu:

**Comment by dhensen** [comment]
I just tested it, and it really does not work. See this gist: https://gist.github.com/dhensen/ab04e0804df655974064e461b6dfa3c0

Just submitted a PR

**Comment by jcmoraisjr** [comment]
The method on controller updates the flags before the parsing while your gist updates the after. I think this was tested on 0.3 releasing so I should check this before merge your PR. Please wait a few more time so I can check this.

**Comment by dhensen** [comment]
Oh I see what you mean.. you are right:
https://github.com/kubernetes/ingress/blob/cffeac0119128918a6453fec9296a6e2d644d3b2/core/pkg/ingress/controller/launch.go#L105-L108

Then I guess that functionallity should be added to OverrideFlags?

**Comment by dhensen** [comment]
Ok I see now that your code was working all along. I messed up in understanding the flags api: especially the call to Parse that happens after the ConfigureFlags. After that call the flag value will be overwritten if the user specifies it. Sorry for confusion!
