### ISSUE TITLE
Force SSL redirect with 301 code

### ISSUE THREAD

**Issue by vitobotta** [jcmoraisjr/haproxy-ingress#490]
Hi! I have configured the ingress so to enforce SSL, but the code is 302. I want a permanent redirect (301) instead.

I tried with this

```
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect-code: "301"
```

But the code is still 302. Thanks!

**Comment by vitobotta** [comment]
Fixed by adding the following to the config map. Would be nice to know if there's a better way though

```
  config-frontend: |
    http-request redirect scheme https code 301 if !{ ssl_fc }  
```

**Comment by vitobotta** [comment]
No, I can't do that because it interferes with http01 challenge with cert-manager...

**Comment by igoratencompass** [comment]
http-request redirect scheme https code 301 if !{ ssl_fc } !{path_beg -i
/.well-known/acme-challenge/}

**Comment by vitobotta** [comment]
@igoratencompass thanks!

**Comment by jcmoraisjr** [comment]
HI, since `v0.10-snapshot.3` you have also `ssl-redirect-code` config key, which can be used globally or per ingress resource as an annotation. Docs [here](https://haproxy-ingress.github.io/docs/configuration/keys/#ssl-redirect). Closing.
