### ISSUE TITLE
multibinder goes zombie

### ISSUE THREAD

**Issue by from-nibly** [jcmoraisjr/haproxy-ingress#51]
We have been noticing that after a while the `multi-binder` process goes `zombie` which seems to mean new haproxy processes cannot be started, which means new versions of the `haproxy.cfg` cannot be consumed. This causes config drift that is hard to track as it only causes problems when pods/services/ingresses change.

It looks like the reason it goes zombie (rather than just terminating) is because the bash script that starts multi-binder (`start.sh`) exits with an exec command to start `haproxy-ingress-controller` which does not listen for the multi binders exit code.

Is there maybe a way that haproxy-ingress-controller itself could start the multi-binder process instead of the bash script. That way haproxy-ingress-controller could detect when the multi-binder process exits and report itself as unhealty/not live.

**Comment by westse** [comment]
Yes, we have seen this as well. We believe this is the error that causes the `multibinder-hap` process to die and go zombie:

```
/usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:42:in `read': No such file or directory @ rb_sysopen - /var/run/haproxy.pid (Errno::ENOENT)
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:42:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:41:in `each'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:41:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:60:in `sleep'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:60:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:58:in `loop'
	from /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:58:in `<top (required)>'
	from /usr/bin/multibinder-haproxy-wrapper:22:in `load'
	from /usr/bin/multibinder-haproxy-wrapper:22:in `<main>'
```

**Comment by westse** [comment]
@jcmoraisjr , the bug in multibinder has been fixed and is in v `0.0.5`. Can you upgrade haproxy-ingress to use it?

**Comment by jcmoraisjr** [comment]
Sure! Updated on 645f39f . I'll provide a new image in the following days. Please let us know if this issue is gone.

A special thanks @westse for filling this issue on multibinder repo and sorry about the delay (vacation here).

**Comment by jcmoraisjr** [comment]
@from-nibly please report back - commenting and/or closing the issue - if the new multibinder version solves the issue. Btw the current canary tag was just updated.

**Comment by from-nibly** [comment]
@jcmoraisjr This is a hard issue to track but we have not seen any zombie processes in a while. I would say this issue is closed.
