### ISSUE TITLE
in v0.8, no frontend created if ingresses use the default host value of "*"

### ISSUE THREAD

**Issue by brianloss** [jcmoraisjr/haproxy-ingress#510]
In testing v0.8, my configuration loaded and I have backends in the generated haproxy config file for each of my ingress objects, but there are no frontends. Therefore, haproxy isn't listening on any ports and traffic will never get through to the backends. This same configuration worked fine in the 0.7 line.

I worked with the examples in the doc, and finally tracked it down to the fact that the example ingress object specifies a "host" value, whereas my ingress objects do not specify a host value and instead get the k8s default of "*" for every host. I do not need or want to specify a host on every ingress object (and doing so would complicate our deployments). Is there some other way to have the frontends generated without putting a host value in my ingress objects?

**Comment by jcmoraisjr** [comment]
Hi, this sounds to be another regression, thanks for the detailed description.

**Comment by brianloss** [comment]
No worries. I haven't fully tested, but it appears a work-around might be to create a single arbitrary ingress with a host mapping. It doesn't have to point to a valid service--there just has to be at least one ingress with a host mapping in order for frontends to be generated.

**Comment by jcmoraisjr** [comment]
Hi, perhaps you can have a look at #516 which should fix this issue. Below is the relevant diff which can be applied on top of v0.8:

```diff
diff --git a/pkg/haproxy/config.go b/pkg/haproxy/config.go
index 203e093..00e92aa 100644
--- a/pkg/haproxy/config.go
+++ b/pkg/haproxy/config.go
@@ -234,9 +234,6 @@ func (c *config) FrontendGroup() *hatypes.FrontendGroup {
 func (c *config) BuildFrontendGroup() error {
 	// tested thanks to instance_test templating tests
 	// ideas to make a nice test or a nice refactor are welcome
-	if len(c.hosts) == 0 {
-		return nil
-	}
 	frontends, sslpassthrough, defaultBind := hatypes.BuildRawFrontends(c.hosts)
 	fgroupMaps := hatypes.CreateMaps()
 	fgroup := &hatypes.FrontendGroup{
diff --git a/pkg/haproxy/types/frontend.go b/pkg/haproxy/types/frontend.go
index 41165b4..b26cb87 100644
--- a/pkg/haproxy/types/frontend.go
+++ b/pkg/haproxy/types/frontend.go
@@ -190,9 +190,6 @@ func (f *Frontend) HasMaxBody() bool {

 // BuildRawFrontends ...
 func BuildRawFrontends(hosts []*Host) (frontends []*Frontend, sslpassthrough []*Host, defaultBind *BindConfig) {
-	if len(hosts) == 0 {
-		return nil, nil, nil
-	}
 	// creating frontends and ssl-passthrough hosts
 	for _, host := range hosts {
 		if host.SSLPassthrough {
```

**Comment by brianloss** [comment]
As far as I can tell, the code changes look fine. I should be able to test it out first thing Monday.

**Comment by brianloss** [comment]
I tested these changes out, and they worked fine. Thanks!

**Comment by jcmoraisjr** [comment]
Hi, v0.8.1, v0.9-beta.2 and v0.10-snapshot.3 fixes this issue. Closing. Please update if you have any problem.
