### ISSUE TITLE
ignore ingresses without specified class

### ISSUE THREAD

**Issue by travisghansen** [jcmoraisjr/haproxy-ingress#522]
I'm not seeing this anywhere in the documentation...is there a flag to control whether the controller will handle ingresses without the the class annotation explicitly set?

Thanks!

**Comment by jcmoraisjr** [comment]
Hi, there is not a way to change this, currently a missing annotations means that the ingress object will always be included.

**Comment by travisghansen** [comment]
Yeah, thanks for considering the feature! When not using this as the default (or running multiple instances one as default the other as not) it would be incredibly helpful.

**Comment by dark-shade** [comment]
@jcmoraisjr 
if you want I can work on this. I also require this feature.

**Comment by dark-shade** [comment]
I submitted the pull request
#527
