### ISSUE TITLE
Support old clients without SNI

### ISSUE THREAD

**Issue by jvegcar** [jcmoraisjr/haproxy-ingress#530]
Hi,
I'm trying to send to my backend a client certifcate server. My restriction is that clients are old and it don't support SNI.

I tried to add the headers but always are empty to the backend.

I read this post: https://github.com/jcmoraisjr/haproxy-ingress/pull/470

    routing is always based on host header, except if the client certificate is mandatory or a client certificate is provided
    if a client certificate is provided, sni is mandatory and a http 421 is issued if it doesn't match the host header
    if sni is missing or doesn't match the host header, a client certificate should be optional or not requested at all, and if requested by the proxy, should not be provided by the client
    if the sni provided references a domain which doesn't request a certificate, or sni is not provided, the client certificate is ignored and the request will be routed as if it wasn't provided

I think my case is the last, sni is not provided so haproxy it's ignoring it. Is this behaviour as expected? Could I do my task with this ingress controller?

**Comment by jcmoraisjr** [comment]
Hi, client authentication with certificate cannot be done without SNI on a multi-site proxy. There are two configurations in place - CA bundle and verify optional/required - which happens during the TLS handshake and uses the SNI extension to discover if the request might use client cert or not.

A new configuration option could be added here, so you can use client cert auth even without SNI, but in this case all TLS handshakes will behave in the same way: you cannot use distinct CA bundles, you cannot also configure to never ask a certificate to the http agent. This would work for you if you have a single-site deploy or all of them uses client cert auth and the same CA bundle.

**Comment by jvegcar** [comment]
Hi, thanks for your reply.
It seems it won't work in my project, because I have two type of clients, and only one type needs client cert auth. 

Thanks for your reply.

**Comment by jvegcar** [comment]
Hi jcmoraisjr,

last question. When you said "new configuration option could be added here, so you can use client cert auth even without SNI", you said that is neccesary to implement this function on the controller or it is available now?

**Comment by jcmoraisjr** [comment]
Hi, this would be a new configuration option.
