### ISSUE TITLE
global maxconn should be tunable

### ISSUE THREAD

**Issue by cbonte** [jcmoraisjr/haproxy-ingress#54]
HAProxy has several `maxconn` keywords:
- a global one : http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#3.2-maxconn
- one for each proxy : http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-maxconn
- one for each bind keyword : http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.1-maxconn
- and one for each backend server : http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#5.2-maxconn

Currently, the Ingress Controller implements `max-connections` which sets the `maxconn` in the `defaults` section (applying to each proxy). The issue is that the `global` one can't be modified, leading to a limit (DEFAULT_MAXCONN) that can't be overrided.

btw, the link in [README.md](../blob/master/README.md#max-connections) redirects to the wrong `maxconn`

**Comment by jcmoraisjr** [comment]
Thanks for pointing this out. The idea of this configuration is to define a global maxconn, although now I see a default maxconn per proxy is also welcome.

Fixed template and readme in 34bcfa6 . Default and per proxy configuration moved to the next release.
