### ISSUE TITLE
Why using tools.cache.Store intead of tools.cache.Listers?

### ISSUE THREAD

**Issue by prometherion** [jcmoraisjr/haproxy-ingress#543]
I'm working on #541 and I'm digging further in the code and noticed this code snippet
https://github.com/jcmoraisjr/haproxy-ingress/blob/dc739f2c9f2a767defeb98f1b7ac0976808af179/pkg/common/ingress/store/main.go#L117-L127

I cannot understand why the project is relying on that not efficient object retrieval method when we could simply use the [`GenericLister`](https://github.com/kubernetes/client-go/blob/ed67da3a2364d34af5ea7b82fd8e88c2c6440a0b/tools/cache/listers.go#L111-L119) provided by `client-go.tools.cache` that is widely used also in other projects to don't waste CPU cycles on iterating over a slice.

With this implementation, we could minimize object lookup and speed up Kubernetes objects retrieval in a more efficient way.

**Comment by jcmoraisjr** [comment]
Hi, everything under `/common` is an inheritance of the old controller and is missing to be revisited, analyzed and eventually refactored. Listers, certs and status are currently missing.

I had a look at your PR, thanks for the proposal. I'll move everything from `/common` after being refactored if needed, or at least revisited. Feel free to move new code to `/controller`.

**Comment by prometherion** [comment]
Thanks for the feedback!

Actually I'm benchmarking the PR on our testing environment where we're handling ~20k Ingresses each one with a custom certificate: the goal is to decrease at least by 30% the `parse_ingress` time since `Lister` is basically using an `Indexer` that should provide a better algorithm to retrieve items in the cache rather than iterating over all of them.

Once I got real data, I'll update this PR, moving new code to `/controller` and updating the tests to let them pass.

**Comment by prometherion** [comment]
@jcmoraisjr moved code to the package `pkg/controller`: still need for refactoring to let tests pass, just double check if it's what you were expecting, otherwise, I could drop the _code moving_ commit.
