### ISSUE TITLE
how to enable health check in tcp service

### ISSUE THREAD

**Issue by Bobi-zhou** [jcmoraisjr/haproxy-ingress#544]
i see in the template  have a config

```
 {{- if $backend.CheckInterval }} check port {{ $ep.Port }} inter {{ $backend.CheckInterval }}{{ end }}
```

but how to enable it ?

**Comment by jcmoraisjr** [comment]
HI, I'm afraid you found an unreachable config. Thanks for point it out.

**Comment by jcmoraisjr** [comment]
Added in v0.10-beta.1, doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap). Closing.
