### ISSUE TITLE
Add ingress API support from k8s 1.18

### ISSUE THREAD

**Issue by jcmoraisjr** [jcmoraisjr/haproxy-ingress#548]
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

* [x] change to the networking api group
* [x] update to ~v1~ `networking.k8s.io` without breaking backward compatibility
* [x] add v1.18 features `pathType` field ~and `IngressClass` resource~

**Comment by rikatz** [comment]
Created the PR #613 for the docs and need to discuss if you want me to port the code to use the newer libs/references :)

**Comment by jcmoraisjr** [comment]
Hi there, be my guest! =)

**Comment by rikatz** [comment]
you can assign this to me :) 

As this is going to be on my issues lists it goes to my TODO ;)

**Comment by rikatz** [comment]
Putting some tests:

* Created two ingress objects: one with ``apiVersion: extensions/v1beta1`` and other with ``apiVersion: netwoking.k8s.io/v1beta1`` in Kubernetes 1.14

It seems that in Kubernetes 1.14 the ``extensions/v1beta1`` is preferred, so it's a good scenario to test with the new library using the ``networking.k8s.io`` apiVersion.

```
$ cat ../ing-new.yaml 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginxnew
spec:
  rules:
  - host: lalalanew.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
```
```
$ kubectl get ing nginxnew -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: "2020-07-09T18:42:29Z"
  generation: 1
  name: nginxnew
  namespace: default
  resourceVersion: "1792"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nginxnew
  uid: f14f236a-c213-11ea-9ced-0242ac130005
spec:
  rules:
  - host: lalalanew.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - {}
```
Deployed the ingress, adjusted the RBAC to allow also the new apiGroup and it seems everything is working fine:

```
curl --resolve lalalanew.com:80:127.0.0.1 http://lalalanew.com
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by rikatz** [comment]
There's also an object created with the old api as the following:

```
$ cat ../ing-old.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: lalalaold.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
```
* kubectl
```
$ kubectl get ing nginx -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: "2020-07-09T18:42:17Z"
  generation: 1
  name: nginx
  namespace: default
  resourceVersion: "1793"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/nginx
  uid: ea18dcb8-c213-11ea-9ced-0242ac130005
spec:
  rules:
  - host: lalalaold.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - {}
```

* Test
```
 curl --resolve lalalaold.com:80:127.0.0.1 http://lalalaold.com
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by rikatz** [comment]
And in the http front map:

```
cat /etc/haproxy/maps/_global_http_front.map
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
lalalanew.com/ default_nginx_80
lalalaold.com/ default_nginx_80
```

So it seems everything is working fine and we can say for sure that HAProxy Ingress will still support k8s 1.14 with the new API. I don't know if it's healthy for the project to keep compability with 1.13 and below, as those are pretty old and the newer k8s apis will remove the extensions/v1beta1

**Comment by rikatz** [comment]
Well, we can safely say that Kubernetes 1.12 wont be supported anymore if we merge the new API version:

```
E0710 17:14:13.443385       7 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource
E0710 17:14:14.445895       7 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191114101535-6c5935290e33/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource
```

So as a suggestion, when the PR gots merged I would say that the latest supported version is v1.14 (as Kubernetes supports only v 1.16).

Now I'll test with the latest version (v1.18) and provide some working matrix.

I would advise also that newer client-go updates verifies if 1.14 still works, as in my understanding they will remove all the references from extensions/v1beta1 also from the clients in some release coming soon

**Comment by rikatz** [comment]
* k8s 1.12 - Does not work
* k8s 1.14 - Works fine, uses the extensions/v1beta1 as preferred API but can resolve the networking.k8s.io/v1beta1 to Ingress
* k8s 1.18 - Works fine, networking.k8s.io/v1beta1 is preferred

**Comment by rikatz** [comment]
@jcmoraisjr do you want me to migrate the client-go lib to v0.19 and also use the new API? Can help with that without any problem et al :)

**Comment by jcmoraisjr** [comment]
Sure, lets update it. The scope of this issue was partially implemented, I'll update its description, close, and just added a new one with the missing pieces - #672 . I'll update that issue as soon as I start something, probably ingress class related. Thanks for the help so far.
