### ISSUE TITLE
Fix typos and import orders

### ISSUE THREAD

**Issue by prometherion** [jcmoraisjr/haproxy-ingress#549]
Although this can be considered just aesthetics fix, during my [PR](https://github.com/jcmoraisjr/haproxy-ingress/pull/545) I noticed there could be some [typos](https://github.com/jcmoraisjr/haproxy-ingress/blob/34c03d75a6bebd8b0d884cca3df3125f14805fac/pkg/common/ingress/controller/controller.go#L199) that should be fixed.

The same for the package import sorting: we should rely on `goimports` following the ecosystem order, as mentioned also [here](https://www.digitalocean.com/community/tutorials/importing-packages-in-go#formatting-imports):

```go
// before
import (
  "fmt"
  "os"
  "github.com/digital/ocean/godo"
  "github.com/sammy/foo"
  "math/rand"
  "github.com/sammy/bar"
)
```

```go
// after
import (
  "fmt"
  "math/rand"
  "os"

  "github.com/sammy/foo"
  "github.com/sammy/bar"

  "github.com/digital/ocean/godo"
)
```

The `goimports` lint check could be performed at `pre-commit hook` or, rather, at CI level for each new pull request.

**Comment by jcmoraisjr** [comment]
Hi, fix typos is very welcome as asked in #482 - which is also valid for comments in the code and log messages.

Regarding imports I'm already using goimports and following these rules:

* up to three blocks
* standard libraries as the first dependencies, following external dependencies, and internal dependencies as the last one

There should be some files breaking these rules and imho they should be fixed. The majority of changes you pointed out was just changing the order of blocks two and three, placing internal dependencies in front of the externals. My goimports didn't say a word about that.
