### ISSUE TITLE
How to route mysql connection over ingress.

### ISSUE THREAD

**Issue by pbabilas** [jcmoraisjr/haproxy-ingress#560]
Hi,
I'm trying and trying but can'nt connect to mysql via ingress. Is it even possible?

I've make my ingress:

```yaml
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/ssl-passthrough: "true"
      ingress.kubernetes.io/ssl-passthrough-http-port: "3306"
    name: mysql
  spec:
    rules:
    - host: mysql.example.com
      http:
        paths:
        - backend:
            serviceName: mysql
            servicePort: 3306
          path: /
```
service works fine over port-forward, but when trying to connect over mysql client, gets: 
```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```
All is done as tcp mode without redirect, any other configuration must be done to be able to routhe this connection to my mysql?

**Comment by jcmoraisjr** [comment]
Hi, never tried to speak with mysql in that way. Questions that comes to my mind: does mysql client send sni extension which is used on ssl-passthrough? Does mysql server have a server certificate and speak tls? Perhaps you should be trying [tcp-service](https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap) instead?

**Comment by pbabilas** [comment]
Hi, mysql server does not have ssl cert, but I tried to pass connection to ambasador which handles cert, then to mysql and it's not working as well.
 I guess that tcp-service would work, but then I need to add every mysql as other service on different port. I've got many domains at my ingress and it would be perfect to define tcp service per domain, not by port I'mean somethink like tcp service for domain1.com with port 3306.

**Comment by jcmoraisjr** [comment]
Hi, it sounds to me that you can do this in one (or both) of two ways: send the http header `host`, which is not an option because mysql doesn't speak http; and send the sni extension, which could be possible if the mysql client can connect over a tls connection. You can use tcp service and configure tls just to make the tls test, and log `%[req.ssl_sni]` which will say if the client send the sni extension. If everything goes well we can implement the "tcp service per domain" part which is not supported at this moment. Let me know about your tests.

**Comment by pbabilas** [comment]
OK I was not able to get tls connection work in mysql but without almost all working fine :D

```bash
 b-code@xps  ~/workspace/isklep/secrets  telnet pbabilas.dev.merce.com 3306                                                                                                                                  SIGINT(2) ↵  9490  13:24:26
Trying 185.157.236.15...
Connected to pbabilas.dev.merce.com.
Escape character is '^]'.
L
8.0.18-9��d>Q0CM��ob4@Kmysql_native_password!#08S01Got packets out of orderConnection closed by foreign host.
```

but still can not connect by client:

```bash
bash-4.2$ mysql -h pbabilas.dev.merce.com -uapp_user -pisklep
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2026 (HY000): SSL connection error: error:00000000:lib(0):func(0):reason(0)
```
so i gues without tls termination in mysql it will not work at all?

**Comment by pbabilas** [comment]
Also dunno how to log `%[req.ssl_sni]` :(

**Comment by jcmoraisjr** [comment]
Please paste your tcp-configmap input or the resulting haproxy.cfg.

Logs: you need [tcp-log-format](https://haproxy-ingress.github.io/docs/configuration/keys/#log-format) and a [syslog endpoint](https://haproxy-ingress.github.io/docs/configuration/keys/#syslog). [This sidecar](https://github.com/jcmoraisjr/udplog-d) should help.

**Comment by pbabilas** [comment]
```yaml
apiVersion: v1
data:
  "3306": pbabilas2/ambassador:3306
kind: ConfigMap
```
And it generate config:

```
/ # cat /etc/haproxy/haproxy.cfg 
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   HAProxy Ingress Controller
# #   --------------------------
# #   This file is automatically updated, do not edit
# #
#
global
    daemon
    unix-bind user haproxy group haproxy mode 0600
    nbthread 2
    cpu-map auto:1/1-2 0-1
    stats socket /var/run/haproxy-stats.sock level admin expose-fd listeners mode 600
    maxconn 2000
    hard-stop-after 10m
    log 10.244.1.112:514 len 1024 format rfc5424 local0
    log-tag ingress
    lua-load /usr/local/etc/haproxy/lua/auth-request.lua
    lua-load /usr/local/etc/haproxy/lua/services.lua
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ...
    ssl-default-bind-ciphersuites ...
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
    ssl-default-server-ciphers ...
    ssl-default-server-ciphersuites ...
    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

defaults
    log global
    maxconn 2000
    option redispatch
    option dontlognull
    option http-server-close
    option http-keep-alive
    timeout client          10s
    timeout client-fin      50s
    timeout connect         3s
    timeout http-keep-alive 1m
    timeout http-request    5s
    timeout queue           5s
    timeout server          40s
    timeout server-fin      50s
    timeout tunnel          28800s
    log global
    mode    http
    option  httplog
    option  dontlognull
    retries 2
    option http-keep-alive
    option http-pretend-keepalive
    option redispatch
    clitimeout      50000
    srvtimeout      50000


  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #
# #   TCP SERVICES
# #
#
listen _tcp_pbabilas2_ambassador_3306
    bind :3306
    mode tcp
    no log
    server srv001 10.244.4.135:3306
```

I tried tcp-log-format and syslog endpoint but after tcp-log-format you given haproxy crashed:

```[ALERT] 110/104644 (77) : Parsing [/etc/haproxy/haproxy.cfg:66]: failed to parse log-format : sample fetch <req.ssl_sni> may not be reliably used here because it needs 'request buffer' which is not available here.
[WARNING] 110/104644 (77) : config : 'option http-pretend-keepalive' ignored for proxy '_tcp_pbabilas2_ambassador_3306' as it requires HTTP mode.
[WARNING] 110/104644 (77) : config : log format ignored for proxy 'stats' since it has no log address.
[WARNING] 110/104644 (77) : config : log format ignored for frontend 'healthz' since it has no log address.
[ALERT] 110/104644 (77) : Fatal errors found in configuration.
E0420 10:46:44.266462       6 instance.go:317] error reloading server:
exit status 1
```

**Comment by jcmoraisjr** [comment]
I'll give this config a try. I'm not using tcp-services myself on a daily basis and perhaps I'm missing something here.

Regarding logs it sounds you added some logging stuff in the config-defaults which did a little mess in some of your frontends. Use the documented logging config instead of config-defaults and lets see if this solves the problem.

**Comment by pbabilas** [comment]
I'm affraid that it cant be enabled :(

```
[ALERT] 114/093537 (355) : Parsing [/etc/haproxy/haproxy.cfg:56]: failed to parse log-format : sample fetch <req.ssl_sni> may not be reliably used here because it needs 'request buffer' which is not available here.
```
every changes also clear configmap getst this error. I've added request buffer also and nothing changes.

**Comment by pbabilas** [comment]
Is there any progress with checking tcp services?

**Comment by jcmoraisjr** [comment]
Nope, sorry, couldn't take a minute in the past few days to have a look on it. Dedicating all the free time to finish and revise a new v0.11 code. I'll update you soon.

**Comment by pbabilas** [comment]
Thank you very much for information. So i will wait for updates.

**Comment by jcmoraisjr** [comment]
Hi, took the time to try mysql and haproxy ingress. It just works. `mysql:5` image, client from another container of the same image, `-h<ingress-ip>` and `show databases` listed the expected 4 databases of a clean install. No ssl/tls at all.

The generated config:

```
listen _tcp_default_mysql_3306
    bind :3306
    mode tcp
    no log
    server srv001 172.17.0.53:3306
```

The tls config and sni logging has however a number of issues. In fact sni cannot be logged due to the missing `inspect-delay` and `content accept` configs that cannot be added via annotations/k8s config. Sni routing couldn't also be used because current tcp-services config doesn't have options to configure it. You'd need to overwrite the template and add some hardcoded config which is far from an optimal approach. So it sounds that haproxy-ingress can help you if you can use one port per database but cannot help if you want to share the same :3306 port just like happens over :80 and :443.

**Comment by i-sklep** [comment]
OK, I've tried connection directly on ingress and indeed its working. Sad it's not able to dynamic configure it on one port or with different tcp-services. Or is it possible to add configuration to set configmap name and searching it in all namespaces? Then I'm able to append configuration dynamic per namespace.

**Comment by pbabilas** [comment]
OK, I've tried connection directly on ingress and indeed its working. Sad it's not able to dynamic configure it on one port or with different tcp-services. Or is it possible to add configuration to set configmap name and searching it in all namespaces? Then I'm able to append configuration dynamic per namespace.

**Comment by pbabilas** [comment]
I'm looking at this config autogenerated, and why it can't be build with bind host;3306 ?
I'd like to add configmap with tcp-service in any ns with host and this what you paste above would look like that:

```
listen _tcp_default_mysql_host_3306
    bind host:3306
    mode tcp
    no log
    server srv001 172.17.0.53:3306

listen _tcp_default_mysql_host2_3306
    bind host2:3306
    mode tcp
    no log
    server srv001 172.17.0.53:3306
```

**Comment by jcmoraisjr** [comment]
Hi, a L4/tcp proxy doesn't work like that. Binds are done to IPv4/6 numbers and any hostname would be translated to an IP. There is no info about host or domain in the incomming data, at least something haproxy could understand, to the best of my knowledge. The only chance here would be moving to L5/tls layer and route the requests using TLS's sni extension but, even if haproxy-ingress had such support (it doesn't have and no roadmap at this moment), the mysql client should also support connection over tls and should also use sni.
