### ISSUE TITLE
0.9-beta4 fails on startup with error in regex

### ISSUE THREAD

**Issue by damomurf** [jcmoraisjr/haproxy-ingress#567]
I have a custom built container running 0.9-beta4 of the controller with HAProxy 1.9.15. 

I've been able to happily run that version on one environment without any issue, but in a second, the ingress controller startup fails with the following errors:

```
[ALERT] 112/061215 (39) : parsing [/etc/haproxy/haproxy.cfg:221] : error in regex ':[0-9]+/' in arg 1 of conversion keyword 'regsub' for ACL keyword 'base' in proxy '_front_http' : regex ':[0-9]+/' jit compilation failed.
[ALERT] 112/061215 (39) : parsing [/etc/haproxy/haproxy.cfg:240] : error in regex ':[0-9]+/' in arg 1 of conversion keyword 'regsub' for ACL keyword 'base' in proxy '_front001' : regex ':[0-9]+/' jit compilation failed.
[ALERT] 112/061215 (39) : parsing [/etc/haproxy/haproxy.cfg:242] : error in regex ':[0-9]+$' in arg 1 of conversion keyword 'regsub' for ACL keyword 'hdr' in proxy '_front001' : regex ':[0-9]+$' jit compilation failed.
[ALERT] 112/061215 (39) : Fatal errors found in configuration.
E0422 06:12:15.641609       6 instance.go:281] error reloading server:
exit status 1
```

The relevant lines of the actual rendered haproxy.cfg file are below:

```
    http-request set-var(req.base) base,lower,regsub(:[0-9]+/,/)
```

```
    http-request set-var(req.base) base,lower,regsub(:[0-9]+/,/)
```

```
    http-request set-var(req.host) hdr(host),lower,regsub(:[0-9]+$,)
```
It seems like a syntax issue, but it's confusing to me that the same container image works fine elsewhere.

Is 0.9-beta4 the best version to be targetting?

**Comment by damomurf** [comment]
Ok, embarrassingly, this was a result of grsec killing off haproxy in the jit compilation phase. The environment that was working fine obviously didn't have it enabled.

Nothing to see here, move along!

**Comment by jcmoraisjr** [comment]
> Nothing to see here, move along!

Yup =)

> Is 0.9-beta4 the best version to be targetting?

v0.10 is pretty much v0.9 with haproxy lts (2.0) and metrics, it's now feature freeze and it's beta quality. We're using in production since snapshot.2, so I consider the last v0.10 the best version to be targeted. v0.9 should be tagged stable and v0.10 should be tagged beta a few days ago, it wasn't tagged yet due to v0.11 development which is taking all of my free time.
