### ISSUE TITLE
AWS ALB configuration

### ISSUE THREAD

**Issue by BASBK** [jcmoraisjr/haproxy-ingress#568]
Hello. I've just installed ingress controller via Helm chart with default values. In AWS the classic loadbalancer was created. But for my use case I need application loadbalancer. I've tried to adapt manually created ALB based on classic's balancer settings. The target group healthchecks are passing. But if I'm trying to access default backend through classic balancer DNS name - everything is cool, while accessing through ALB DNS name return ERR_NETWORK_CHANGED

UPD:
Miss to add proper security group for ALB. Now I'm getting ERR_CONNECTION_REFUSED

**Comment by s1rc** [comment]
@BASBK I am wondering if you managed to get the ALB working?
