### ISSUE TITLE
Prometheus listening port 10254 does not change 

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#569]
Hi,
I am using ingress haproxy version 0.8.3 in a multi ingress configuration(4 ingress separated by classes) . But when I use more than one, the prometheus port 10254 turns into a factor that blocks the others ingress to start up. The daemonset controllers are hostnetwork:true  because in my scenery I need no NAT. I tried changing the 10254 listening port of each ingress controller by passing this parameter in the configmap :  prometheus-port: "...."
But the listening port 10254 is still there. Is there a way to change this port ?

**Comment by jcmoraisjr** [comment]
Hi, are you trying to deploy more than one ingress into the same host with host network enabled? All the listening ports will become a problem, if you need host network you should isolate ingress into distinct hosts. Note also that prometheus-port is a v0.10 config option and won't change how v0.8 works. You can configure 10254 using [`--healthz-port`](https://haproxy-ingress.github.io/docs/configuration/command-line/#stats) command-line option.

**Comment by zbebeto** [comment]
I have a loadbalancer solution in front of them(the 4 ingress).. It will balance to them ... And I only need to put them to work in two nodes ... I changed all the ports for each one BUT I could not change the Port 10254 for any one of them ... What property has the Power to change that Port? Heathz is not  the one ... I have changed It... The port of heathz changed .. and It was ok...but in my host there is still the hell 10254 Port listening.

**Comment by zbebeto** [comment]
João
Meu nome é Roberto ... Fui eu quem fez o issue 569.... Trabalho no senado
federal na área de Ti e estamos tentando usar o haproxy ingress .
Posso explicar pra vc a situação via mail ou uso o Github mesmo e escrevo
em inglês ?

Cordialmente ,
Roberto.

Em qua, 29 de abr de 2020 22:31, Joao Morais <notifications@github.com>
escreveu:

**Comment by zbebeto** [comment]
Its very important for a system administrator the power to control all the listening ports... It would allow, as an example,  to use different ingress (different classes) in the same nodes with a load balancer in front of them according to a policy (internal or external traffic ... and other situations )...

**Comment by zbebeto** [comment]
The only port I could not control was the port 10254.... I tried to change this port with healtz-port.... using prometheus-port.... and the port was still there ... listening...

**Comment by zbebeto** [comment]
I have used the canary and v0.8.3 with the same results...

**Comment by jcmoraisjr** [comment]
Hi, I can confirm that `--healthz-port=10101` **command-line option** does change the listening port to `10101`. Unfortunately I can also confirm you cannot remove such service if you doesn't use it. You are apparently trying to configure via configmap option. Hth.

**Comment by zbebeto** [comment]
then....the listening  port 10254 cannot be changed or disabled ?

**Comment by jcmoraisjr** [comment]
> then....the listening port 10254 cannot be changed or disabled ?

No. The port number ***can*** be changed as said before:

> I can confirm that --healthz-port=10101 command-line option does change the listening port to 10101

Doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#stats).

**Comment by zbebeto** [comment]
Perfect... port changed and multi haproxy in the same nodes worked like a charm!

Thanks a lot !
