### ISSUE TITLE
Need no touch in headers X-Forwarded-For , X-Forwarded-Proto and X-Forwarded-Port

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#572]
Hi
Thanks in advance.... in my case I need the following headers to be untouched:
-X-Forwarded-For
-X-Forwarded-Proto
-X-Forwarded-Port

Is there a way ?

**Comment by zbebeto** [comment]
I realized that in the frontends there is an injection of the header X-Forwarded-Proto according to the port http or https. I did not found in the docs how to avoid the interference in this field.
In my case.... this field already comes and must be keept as it arrived. I do not use the https port. I only use the http port .... my https is served by a reverse-proxy in front  of ingress. So this proxy sets the necessary fields and serves https connections.

**Comment by zbebeto** [comment]
The others fields X-Forwarded-For(the behaviour can be controlled) and X-Forwarded-Port(no interference here) are not the problem.

**Comment by jcmoraisjr** [comment]
Perhaps you are looking for [fronting-proxy-port](https://haproxy-ingress.github.io/docs/configuration/keys/#fronting-proxy-port)?

**Comment by zbebeto** [comment]
I have seen fronting-proxy-port....
It takes action depending on the value of the header X-Forwarded-Proto... And I need the opposite ... No action in any case with this header ... Is a critical header for my case...
In this moment there ia an ingress nginx in the cluster  that have this property : use-forwarded-headers does the trick... It does not interfere in the forwarded headers .
I was working for three weeks in a project to replace the ingress nginx to the ingress haproxy.... 
It seems a dead end now...

**Comment by zbebeto** [comment]
The Proxy in front of ingress configures the headers (the 3 headers listed above)... And its a requirement to keep this headers untouched and proceed the request... It waa the last point to take off the ingress nginx ....

**Comment by zbebeto** [comment]
The ingress nginx is doing the job... But I would prefer haproxy as a reverse Proxy/ balancer  for a lot of reasons....

**Comment by jcmoraisjr** [comment]
> use-forwarded-headers does the trick

So lets build this one. This should be simple enough to be merged to v0.10. I'm finishing some v0.10 stuff now, give me a few more days.

**Comment by zbebeto** [comment]
I need some direction.... I was working with v0.8.3... What image should I use in the daemon set now ?

**Comment by jcmoraisjr** [comment]
Have a look on `v0.10-snapshot.5`. Although being a snapshot, we're using in production since snapshot.2, it's almost feature freeze and I'll promote it to beta within a few days from now.

**Comment by zbebeto** [comment]
ok! I will try..
Everything is working fine in the 0.8.3 except for the problems with headers that were forwarded.
I will wait for the enhancement...

**Comment by zbebeto** [comment]
please send me a warning when the enhancement becomes ready... I will test it as soon as possible...

**Comment by zbebeto** [comment]
and beat the ingress nginx....

**Comment by jcmoraisjr** [comment]
Hi, this feature couldn't be added as a skip-everything due to some backward compatibility issues. But since v0.10-beta.1 you can configure your controller like this:

* `fronting-proxy-port: "80"` this will tell haproxy-ingress that you have a lb in front of it doing ssl-offload
* `use-forwarded-proto: "false"` this will tell haproxy-ingress to not touch the fw-proto header
* `forwardfor: "ignore"` and finally this will tell haproxy-ingress to not touch the fw-for header

fw-port isn't used at all. Docs [here](https://haproxy-ingress.github.io/docs/configuration/keys/#fronting-proxy-port) and [here](https://haproxy-ingress.github.io/docs/configuration/keys/#forwardfor). Closing, and let me know if you still have any problem.

**Comment by zbebeto** [comment]
Hi .... my 4 ingress work each one in separate http ports : 8091 8092 8093 8094
I do not use the https port of none of them ... 
in front of them there is a varnish in the port 80
and an nginx in 443
the line fronting-proxy-port: "80" makes haproxy bind in port 80.... and varnish will be there ... 
It wont work ...

**Comment by zbebeto** [comment]
What I needed is very simple... each one in their own http port with no interference in the headers configured by the varnish (80) and nginx (443) in front of them ....
Thsi is a legacy environment .... there is an nginx ingress at the moment behind the varnish and the nginx .... I would love to change it for a
 haproxy

**Comment by jcmoraisjr** [comment]
Hi, it's just an example, do configure `fronting-proxy-port` as the same http port you are currently using on each controller.

**Comment by zbebeto** [comment]
hum
I got it

**Comment by zbebeto** [comment]
forget what I told you .. thanks .... I will probably make the operation to change the ingress nginx next friday (22/05
)

**Comment by zbebeto** [comment]
this was the last missing point ... thanks a lot jc 
!

**Comment by zbebeto** [comment]
any problem I
 will post here ok ?

**Comment by zbebeto** [comment]
my organization is SENADO FEDERAL - BRAZIL

**Comment by zbebeto** [comment]
if it works every web app in the future will be supoorted by the ingress haproxy .
Sorry about the misunderstand... I thought you were talking about something hard coded

**Comment by zbebeto** [comment]
We have put ingress haproxy in testing and acceptance environments  ... This week we had problems with the ingress nginx in production environment.... Best time to put the ingress haproxy to do the job...will be done today ... 29/05 ... This afternoon...
