### ISSUE TITLE
Host scoped bind options

### ISSUE THREAD

**Issue by Unichron** [jcmoraisjr/haproxy-ingress#573]
For my use-case, I need to configure different cipher suites and minimum tls versions for different hosts. This would be possible with host scoped ssl-options and ssl-ciphers/cipher-suites. If I'm correct I think that it would be also possible with just a host scoped bind-https, which would enable any bind related option to be host scoped, acting as a nice catch-all for edge-cases like mine.

What do you think?

**Comment by jcmoraisjr** [comment]
Hi, sure, missed moving such global config options when the frontend refactor was done on v0.9. Thanks for the record.

**Comment by Unichron** [comment]
@jcmoraisjr I would like to create a pull request for this because my company will need it soon-ish. Is there something design related that needs to be discussed or do you think it's straightforward enough?

**Comment by jcmoraisjr** [comment]
It seems to me straightforward enough although it isn't a trivial change. Ping here if you have any doubt.
