### ISSUE TITLE
Timeout in specific case

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#574]
It sometimes happen to need an especific "timeout server" for a specific backend ... different from the global "timeout server"
How it can be  done in ingress-haproxy?

**Comment by zbebeto** [comment]
For example... in my production the majority of the applications works well with 60 sec of "timeout server".... BUT... there are applications that neeed 300 sec of "timeout server"... legacy applications with some terrible reports that take to long to finish....

**Comment by jcmoraisjr** [comment]
Yup, [timeout server](https://haproxy-ingress.github.io/docs/configuration/keys/#timeout) is just another backend scoped config key that you can use as an annotation on services and ingress objects. Remember to add the [annotation prefix](https://haproxy-ingress.github.io/docs/configuration/keys/#ingress-and-services) which defaults to `ingress.kubernetes.io/`.

**Comment by zbebeto** [comment]
Thanks a lot !
