### ISSUE TITLE
Blue Green example does not work

### ISSUE THREAD

**Issue by kaceo** [jcmoraisjr/haproxy-ingress#584]
The example on this page https://haproxy-ingress.github.io/docs/examples/blue-green/ does not work in my cluster (1.17 linode kubernetes), (kubectl version 1.18.2)

After 
```
     kubectl run blue  --image=jcmoraisjr/whoami \
     --port=8000 --labels=run=bluegreen,group=blue
```
the response is Pod/blue created (not Deployment)

After
```
     kubectl expose deploy blue --name bluegreen --selector=run=bluegreen
```
error is no deployment blue found

**Comment by jcmoraisjr** [comment]
Hi, thanks for the feedback. Perhaps this is due to the deprecation of the default generator? What's the result of a `kubectl get deploy,svc,pod`?
