### ISSUE TITLE
Add config snippet on other haproxy sections

### ISSUE THREAD

**Issue by thyn** [jcmoraisjr/haproxy-ingress#587]
Currently it's possible to add custom logic to http frontend and backend

like

`{
	"config-frontend": "acl network_allowed src -f /etc/haproxy/lists/allowedips.lst
		http-request deny if !network_allowed
		"
}`

It works only for http(s).

But it's impossible to do it in stats and tcp frontends. Also if ssl pass through is enabled all such sites are not filtered.

Please, add such extensions points.

**Comment by jcmoraisjr** [comment]
Related with #581

**Comment by jcmoraisjr** [comment]
Implemented in `v0.13.0-snapshot.1` which was just released and adds lots of new custom configuration options. Closing.
