### ISSUE TITLE
Occasional client timeouts "cD--"

### ISSUE THREAD

**Issue by cjroebuck** [jcmoraisjr/haproxy-ingress#590]
Hi, I've been receving reports of occasional long requests i.e. > 5 minutes, followed by timeouts from users. I think it's something to do with haproxy. 

I have haproxy-ingress which proxies to nginx. I can see that the nginx log line returns 200 OK after my app sends the response.

After another 400 seconds (I have client and server timeout set to 400s) I then see the haproxy log line with the cD-- status.

Here's an example:

```
May 21 02:47:12 myapp Started new request
May 21 02:47:32 myapp OK - Closing request
May 21 02:47:32 nginx - - [21/May/2020:02:47:32 +0000] "GET /some/url" 200 619556 "-" "Apache-HttpClient/4.5.9 (Java/1.8.0_111)"
May 21 02:54:12 ingress haproxy-ingress [21/May/2020:02:47:12.224] _front001~ default_api-service_8080/srv001 0/0/1/20190/420426 200 201155 - - cD-- 153/153/12/3/0 0/0 "GET /some/url HTTP/1.1" 
```

Here is relevant config for haproxy ingress controller:
```
  timeout-client: "400s"
  timeout-client-fin: "400s"
  timeout-server: "400s"
  timeout-server-fin: "400s"
  timeout-keep-alive: "5m"
```

I would say that 99% of requests are working fine, but this 1% of requests are being dropped/timed out and for no obvious reason.

I don't understand why in these cases haproxy does not always return straight away after nginx has returned. Is there some level of debugging I can enable to look into what might be happening? Thank you!

**Comment by jcmoraisjr** [comment]
Hi, according to the [doc](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#8.5), `cD--` means that the client side timed out, so it sounds to me that the connection between your haproxy and the client who connected to it failed, which is causing the timeout in the haproxy side.
