### ISSUE TITLE
Is it possible a different configuration?

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#592]
Hi 
I have configured haproxy ingress with image v010-beta1 in my development environment with initial  success. I am using a daemonset configuration.
The ingress haproxy is running in two nodes. The daemonset spread in this two nodes due to a affinity configured in the daemonset.
I would like to change the configuration to two deployments. Each one to an speccific affinity with one os the two nodes. They would run with the same configurations.... but it will be not one deployment with scale 2.... it will be two deployments with scale one... is it possible ? Can it work well?

Id like this  configuration because I want  the chance to update half of my ingress haproxy in production to make some tests in production . I use a Vip (virtual IP) between the two nodes to decide which one will serve the requests... then I could switch with easy between different versions and it would help a lot.

**Comment by jcmoraisjr** [comment]
Hi, note that this is more a k8s workflow than an ingress controller one, you'll probably receive more and better opinions on k8s forums. That said, sharing how we deploy haproxy ingress, hth.

We use a similar configuration on our clusters: two daemonsets (blue and green) with two distinct nodeSelector (label=blue and label=green) referencing two distinct global options configmaps (blue and green again). Nodes starts eg with label=blue which deploys ingress from the blue daemonset. Whenever we want to start a rolling update, we start changing the node labels from blue to green.

**Comment by zbebeto** [comment]
OK ...I got it ...closing...

**Comment by zbebeto** [comment]
Thanks a lot
