### ISSUE TITLE
Partially enable Proxy Protocol

### ISSUE THREAD

**Issue by Starz0r** [jcmoraisjr/haproxy-ingress#593]
Right now I seem to be having this issue where "Proxy Protocol" related traffic is pass-through to ports 80, and 443, which is undesired. I'd like to partially enable the Proxy Protocol on only TCP Services, since they are the only ones that can truly benefit from it. Or more specifically, convert the Proxy Protocol request to an HTTP one with `X-Forwarded-For` header passed, although I think `forwardfor` would handle this already, it's that I can only have one or the other enabled. That being either Proxy Protocol or Forward For.

I know this can already be done if HAProxy was installed on a bare machine, but since it's behind a container, and limited to the Kubernetes resources as APIs to manipulate it, would be nice if I could do this natively without having to choose one or the other.

**Comment by jcmoraisjr** [comment]
Hi, if you are talking about tcp services configured via a config map, you should enable proxy protocol only in the tcp services configmap, doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap). Being a tcp proxy we cannot manipulate headers.

Regarding http services, proxy protocol (disabled by default) and x-forwarded-for header (enabled by default) have independent configurations, you can eg enable proxy protocol and disable x-forwarded-for header. Docs [here](https://haproxy-ingress.github.io/docs/configuration/keys/#proxy-protocol) and [here](https://haproxy-ingress.github.io/docs/configuration/keys/#forwardfor).

**Comment by Starz0r** [comment]
@jcmoraisjr My apologies, when I was talking about one or the other, I didn't only mean HAProxy. It's currently behind a load balancer where I can enable the Proxy Protocol, but it also sends HTTP requests through the same way, which means services that don't support HTTP + Proxy Protocol fail immediately. That's why I was wonder if it was possible to convert those back into regular HTTP requests with the `X-Forwarded-For` header applied.

Sorry for the confusion.

**Comment by jcmoraisjr** [comment]
What do you mean with `services that don't support HTTP`, other services outside haproxy ingress or http services behind haproxy:80? Under haproxy ingress you control proxy protocol enabled on both sides of the connection: `use-proxy-protocol` controls between your fronting load balancer and haproxy, and `proxy-protocol` controls between haproxy and your backends (I know bad names). If you leave forwardfor enabled, haproxy will create the header using the real ip if `use-proxy-protocol` is enabled, and without using proxy-protocol to your backends if `proxy-protocol` is disabled. Perhaps I'm missing something here, if so please clarify a bit more.

**Comment by Starz0r** [comment]
The issue is with having Proxy Protocol enabled on my fronting load balancer which is also load balancing HTTP applications. When the Proxy Protocol is enabled on the load balancer anything sent to port `80` and `443`, don't work since it just forwards packets to the applications that are encoded with the Proxy Protocol and not HTTP. I'm wondering if there is a way to enable the Proxy Protocol on every port that isn't `80` and `443`, or just having those requests converted back into HTTP packets with `X-Forwarded-For` filled, so I can avoid having this issue.

I hope that has clarified things a bit more @jcmoraisjr. If not let me know.

**Comment by jcmoraisjr** [comment]
Hi, I'm still missing something here. haproxy should listen only 80/443 and you can configure proxy-protocol on/off using the provided config keys (from my last comment). Any other listening port should be tcp-services, stats, etc and most of them has their own proxy-protocol on/off. Your apps behind haproxy has also their own proxy-protocol on/off as well that can be configured on a per backend basis. Don't hesitate to send a small image with a topology (draw.io) that explains your scenario.

**Comment by Starz0r** [comment]
@jcmoraisjr Apologies for responding so late.

Are you saying that enabling proxy protocol will only enable it on ports that are not `80` and `443`? If so, this is the desired behavior I'd like to achieve.

**Comment by jcmoraisjr** [comment]
You can enable proxy protocol by service type, naming:

* Default http/s frontend which defaults to 80/443 port number, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#proxy-protocol)
* Stats which defaults to 1936 port number, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#stats)
* TCP services, that one you declare using a configmap and `--tcp-services-configmap` command-line option, you choose the ports, doc [here](https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap)

So if you enabled proxy protocol only on tcp services and/or stats, and you didn't change default listening ports, and you of course didn't configure any tcp service to listen to 80 or 443, you will only have configured proxy protocol on ports that are not 80 or 443.
