### ISSUE TITLE
quay.io down

### ISSUE THREAD

**Issue by adrianlyjak** [jcmoraisjr/haproxy-ingress#595]
Seems that the public docker image is unavailable as quay.io is going through an outage. Are there any mirrors available?

**Comment by jcmoraisjr** [comment]
ow s*, pushing backup images to docker hub in a few minutes, I'll notify shortly.

**Comment by jcmoraisjr** [comment]
Uploaded the same images generated by travis:

* `jcmoraisjr/haproxy-ingress:v0.10-beta.1` (also `canary` and `snapshot`)
* `jcmoraisjr/haproxy-ingress:v0.9` (also `latest`)
* `jcmoraisjr/haproxy-ingress:v0.8.4`

Thanks for the report. Let me know if you have any problem.

**Comment by jcmoraisjr** [comment]
Issue solved, closing, thanks for the report!
