### ISSUE TITLE
when server hope get client IP ,how configure the haproxy-ingress for ?

### ISSUE THREAD

**Issue by sober-wang** [jcmoraisjr/haproxy-ingress#596]
My tenant have a server ,It want get http/tcp client IP . 
What should I do configure the haproxy-ingress?

**Comment by Unichron** [comment]
In my experience you don't need to configure anything special in the ingress, you although need to set  externalTrafficPolicy: Local in your kubernetes service resource if you want to read the client ip in your backend.

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
