### ISSUE TITLE
Haproxy ingress http/https log format  

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#605]
I have configured haproxy ingress with the default haproxy http/https log format ... but even after that my (filebeat -> logstash -> grafana) sequence was still broken ... it happened because there are some fields(7) that appeared before the fields defined in the "http/https log format" and I do not know how to disable this fields. An example:

<134>1 2020-06-15T02:58:18+00:00 xxx.senado ingress 40 - - [15/Jun/2020:02:58:18.042] _front_http _default_backend/srv001 0/0/0/14/14 200 246 - - ---- 1/1/0/0/0 0/0 "POST /VirtualHostBase/https/www12.senado.leg.br:443/ecidadania/ajaxportaluser HTTP/1.1"

these initial fields are not defined in the http/https log format :
<134>1 2020-06-15T02:58:18+00:00 xxx.senado ingress 40 - - 

Is there a way to disable them ?

**Comment by jcmoraisjr** [comment]
Hi, this is the syslog header, you should configure a collector which parses this properly. Have a look at the [rfc](https://tools.ietf.org/html/rfc5424#section-6.2.1).

**Comment by zbebeto** [comment]
thanks a lot  .. closing the issue....

**Comment by jcmoraisjr** [comment]
Update: you can also use a global config option `syslog-format: raw`, doc [here](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#log) (look for `<format>`) if not using a syslog collector.

**Comment by zbebeto** [comment]
OK!

**Comment by zbebeto** [comment]
The project here is working good and going on properly....
