### ISSUE TITLE
Nab deployment instructions

### ISSUE THREAD

**Issue by cringdahl** [jcmoraisjr/haproxy-ingress#61]
CoreOS has removed the deployment instructions and example YAML from their master branch. Please nab them from their [history](https://github.com/kubernetes/ingress-nginx/tree/2139ee85e7a70d141c0b82035f3153d9d9f0b6fb/examples/deployment/haproxy) and include them in this repo.

**Comment by jcmoraisjr** [comment]
Yep, known issue, now took the time to fix this. Tks for reporting.
