### ISSUE TITLE
Versions roadmap

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#610]
Hi,
In the present moment I am using in production the version v0.10-beta.1.
The project here is in production initial weeks . Is it the recommended version at the moment for an initial project ?
What is the planning for near future?
Thanks in advance.

**Comment by jcmoraisjr** [comment]
Hi, we do a long staging process, deploying new versions on a very early stage in our own production environment. The result is beta versions almost as good as the final versions. So I'd say v0.10 is the recommended version, which is btw pretty much the v0.9 with haproxy 2.0 (instead 1.9) and metrics. You need to do of course your own validation process.

Near future has, at least, 1) improvements on cpu usage and processing time on big clusters (thousands of ingress and services), there is a pr running with such improvements; 2) improvements in the conf building which will improve maximum rps and reduce latency; 3) improvements in the dynamic update, avoiding to reload haproxy as much as possible; 4) examples, doc improvement, articles, use cases and so on (help wanted btw).

**Comment by zbebeto** [comment]
I am using the right version then .... Thanks a lot for the "vision" of  near future
more confident now...
