### ISSUE TITLE
Create a Github action to close stale issues

### ISSUE THREAD

**Issue by rikatz** [jcmoraisjr/haproxy-ingress#614]
On a mood trying to help you to close older issues:

https://github.com/actions/stale

This GH action can close old and stale issues, that might be already solved or got no response from users in a period of time.

My suggestion is to create a GH account as a bot, with permission to only close issues and some labels that define stale and wip issues, and let the bot do its job :)

**Comment by jcmoraisjr** [comment]
I'll have a try with the default account provided with the `GITHUB_TOKEN` secret. PR just merged, closing this one by hand =)
