### ISSUE TITLE
Need x-forwarded-for and x-forwarded-proto headers in haproxy log

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#616]
Hi
I need the http headers x-forwarded-for and x-forwarded-proto as  fields in the log format  of my ingress haproxy .
To make it work ... I need to specify the capture of this headers and put them in the log format.
How to achieve that with haproxy ingress ?

**Comment by jcmoraisjr** [comment]
Hi, capture headers using `config-frontend` ([doc](https://haproxy-ingress.github.io/docs/configuration/keys/#configuration-snippet)) and log format using `http-log-format` ([doc](https://haproxy-ingress.github.io/docs/configuration/keys/#log-format)).

**Comment by zbebeto** [comment]
Thanks for the support !
I put that in my haproxy ingress configmap and worked immediately:
  config-frontend: |
      capture request header X-FORWARDED-FOR len 32
      capture request header X-FORWARDED-PROTO len 32
I was using the custom http log and it needed no touch because it is already prepared to show capture request headers.
Thanks a lot.

**Comment by zbebeto** [comment]
Can be closed this issue?

**Comment by jcmoraisjr** [comment]
Yup, closing.
