### ISSUE TITLE
Send http 421 when using SNI Routing ( ssl passthrough ) and HOST header does not match SNI request

### ISSUE THREAD

**Issue by primeroz** [jcmoraisjr/haproxy-ingress#619]
In the template the `send-421` is currently only used when tls client certificates are used. 

The same problem that we try to address there can exist for simple SNI routing when the ssl passthrough is used on an Ingress. 

For example in my test i currently have 

```
listen _front__tls
    mode tcp         
    bind *:443        
    option tcplog
    tcp-request inspect-delay 5s                                             
    tcp-request content set-var(req.sslpassback) req.ssl_sni,lower,map(/etc/haproxy/maps/_global_sslpassthrough.map)
    tcp-request content accept if { req.ssl_hello_type 1 }
    use_backend %[var(req.sslpassback)] if { var(req.sslpassback) -m found }
    ## _front001_socket
    use-server _server_front001_socket if { req.ssl_sni -i -f /etc/haproxy/maps/_front001_use_server.list }
    server _server_front001_socket unix@/var/run/_front001_socket.sock send-proxy-v2 weight 0
    # default backend   
    server _default_server_front001_socket unix@/var/run/_front001_socket.sock send-proxy-v2
```

This can fail if an http2 connection was reused with the _wrong_ sni so that instead of routing to the sslpassthrough backends it still gets routed to the front001 backend.

should we add something similar to https://github.com/jcmoraisjr/haproxy-ingress/blob/v0.9/rootfs/etc/haproxy/template/haproxy.tmpl#L988 before the _use\_backend sslpassback_ to send a 421 back to the client when host and sni do not match ?

**Comment by jcmoraisjr** [comment]
Hi, this is a problem as reported in https://github.com/jcmoraisjr/haproxy-ingress/issues/523#issuecomment-590892469 . This cannot be done because we cannot inspect http headers on a ssl-passthrough connection - a tcp proxy is used here and the tls handshake is done by the backend.

**Comment by primeroz** [comment]
make sense.

thanks you
