### ISSUE TITLE
Redirecting to other vhost while scaling down pods

### ISSUE THREAD

**Issue by prometherion** [jcmoraisjr/haproxy-ingress#620]
We're running the pre-release `v0.10-beta.2` and we noticed this weird behavior:

1. got an Ingress (`ingress-foo`) serving for the vhost `foo.domain.tld`, backed by a Service (`service-foo`) for Deployment `deployment-foo` which pods are serving a simple HTML page (`Hello foo`)
2. another similar application, but with `bar`: so Ingress, Service and Deployment returning `Hello bar`
2. scaling to zero the `deployment-foo` Deployment
3. visiting `foo.domain.tld` the HAProxy Ingress Controller redirects for a certain period of time towards `bar.domain.tld`
4. after a second reconciliation, finally I get the expected `503 Service Unavailable`

**Comment by jcmoraisjr** [comment]
Hi, is this a new behavior on a recent version which doesn't happen on an old one? Perhaps this is related with an IP address serving `foo` which was released and now serving `bar`, and the ingress didn't have the time to update the endpoints? Otherwise if you can confirm that all `bar` endpoints and pods are older than scaling `foo` to zero, we'd have apparently a new and unknown problem.

v0.11 has some new features that should improve this scenario: 1) fast partial parsing of changed objects; 2) wait a bit (default 500ms) before start object parsing, giving the time to a group of related changes being reflected in the listers; 3) always apply all possible dynamic changes (currently update endpoints) even if a full reload is needed. The first snapshot is very close to be issued.

**Comment by prometherion** [comment]
Reverting to `v0.9-beta.4` solved the issue, or rather: we didn't notice.

> Perhaps this is related with an IP address serving foo which was released and now serving bar, and the ingress didn't have the time to update the endpoints?

That's not the case: no Service updates, just EndpointList update with a Deployment scale down

**Comment by jcmoraisjr** [comment]
How did you find this behavior? Only production or you can reproduce on a staging env as well? Can you reproduce it again? foo and bar shares the same wildcard cert? Any other info about the environment and the test will be very much appreciated.

**Comment by prometherion** [comment]
We find this behavior on our production cluster with ~20k resource between distinct Ingress, Service, Secret, and Endpoint resources.
We're not able to reproduce on smaller clusters, so guessing it's a sort of transactional issue but absolutely non-flaky.

Each Ingress got its own certificate, so not sharing any wildcard.

The configuration reload takes ~4 minutes, as you could recall.

**Comment by jcmoraisjr** [comment]
I've revisited all the backend and endpoint building code a couple of times, I cannot see a way a backend could point to an endpoint of another backend ... yet. Following a few more questions: Can you deploy a new controller version on a node outside of your incoming traffic (we don't want to break the site of your clients)? Is this a reproducible behavior or do you have some time to reproduce it again? Do you use `--v=2` (or higher) command-line option and have logs just before, during and just after the time frame of the faulty configuration? HAProxy was reloaded just before/during/just after or config was dynamically applied all the time? `foo.domain.tld` and `bar.domain.tld` are completely distinct hostnames or are there some sort of wildcard or regex alias which could cause some collision?

These are the logs I'm interested in:

https://github.com/jcmoraisjr/haproxy-ingress/blob/8dd387a39085e2a371b7add7a64e8db4b7481eed/pkg/haproxy/dynupdate.go#L297-L300

https://github.com/jcmoraisjr/haproxy-ingress/blob/8dd387a39085e2a371b7add7a64e8db4b7481eed/pkg/haproxy/dynupdate.go#L318-L322

> The configuration reload takes ~4 minutes, as you could recall.

Let us know the new numbers as soon as you can run v0.11

**Comment by prometherion** [comment]
> foo.domain.tld and bar.domain.tld are completely distinct hostnames or are there some sort of wildcard or regex alias which could cause some collision?

I just redacted hostnames with dummy ones: domains were totally different, so no regex or wildcard could be the root cause.

> Can you deploy a new controller version on a node outside of your incoming traffic (we don't want to break the site of your clients)?

To avoid issues on the end-users side we rollbacked to`v0.9-beta.4` so I'm no more able to replicate it.

--

The next step is to test 0.11 to find if the issue is also there, or not: I'll keep you updated.

**Comment by Sea-you** [comment]
@jcmoraisjr fyi, it does not happen with 0.11, and performance improvements are immense, great job!
@prometherion you can close the issue ;)

**Comment by jcmoraisjr** [comment]
Great news, thanks for sharing! Would you mind to share some numbers? Before and after v0.11.

**Comment by jcmoraisjr** [comment]
Just for the record, this was apparently https://github.com/haproxy/haproxy/issues/717 which impacts only v0.10-beta.2.
