### ISSUE TITLE
haproxy-ingress/examples/auth/client-certs/ not working

### ISSUE THREAD

**Issue by peterhaaf** [jcmoraisjr/haproxy-ingress#624]
Hi,

i am sorry if this is a beginner issue, i am not too familar with haproxy config, but my googling did not point me anywhere to a solution...

I am trying to get client-ca auth working and followed the example jcmoraisjr/haproxy-ingress/examples/auth/client-certs/
I created the ca.cert ( i used the same /CN which i a, using for the default server cert), created the k8s secret and added the annotation to one of my ingress definitions.

Here is the error-log of haproxy:

parsing [/etc/haproxy/haproxy.cfg:592] : 'bind unix@/var/run/haproxy-https-prometheus.<domain>.sock' : unable to load SSL certificate file 'ca-file' file does not exist.
[ALERT] 201/114108 (2593) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 201/114108 (2593) : Fatal errors found in configuration.
E0720 11:41:08.195784       7 controller.go:316] unexpected failure restarting the backend: 
exit status 1

within haproxy.cfg, line592:
bind unix@/var/run/haproxy-https-prometheus.<domain>.sock ssl alpn h2,http/1.1 crt  ca-file /ingress-controller/cacerts/ca-prometheus-prometheus-ingress-client.pem verify

now checking on filesystem level:
ls -l /ingress-controller/cacerts/ca-prometheus-prometheus-ingress-client.pem
-rw-r--r--    1 root     root          1034 Jul 20 11:43 /ingress-controller/cacerts/ca-prometheus-prometheus-ingress-client.pem

file exists and is excessable:
cat  /ingress-controller/cacerts/ca-prometheus-prometheus-ingress-client.pem
-----BEGIN CERTIFICATE-----
MIICz…..
-----END CERTIFICATE-----

#note that i removed the real domain name by <domain>

What is going wrong, why does haproxy report a missing file, that does exist ? 

Thanx for your help
Peter

**Comment by jcmoraisjr** [comment]
Hi, please provide the config options you are using.

**Comment by peterhaaf** [comment]
Hi,

sorry for the delay...

haproxy deployment important details
    spec:
      containers:
      - args:
        - --default-backend-service=default/ingress-default-backend
        - --default-ssl-certificate=default/ingress
        - --configmap=$(POD_NAMESPACE)/haproxy-configmap
        - --reload-strategy=native
        image: haproxy-ingress:latest 
we run an older version ( from Jan 9, 2019 ) please let me know, if an update is mandatory here..

haproxy-configmap:
apiVersion: v1
data:
  backend-server-slots-increment: "4"
  dynamic-scaling: "true"
  hsts: "false"
  timeout-server: 2m
kind: ConfigMap

Thanx
Peter

**Comment by peterhaaf** [comment]
It was the old haproxy image, preventing client Certs from working. 
Please appologize, that i did not realise and test this earlier..
