### ISSUE TITLE
hsts annotations

### ISSUE THREAD

**Issue by abh** [jcmoraisjr/haproxy-ingress#63]
It'd be nice to be able to configure the hsts configuration in annotations (for example some ingress'es might want to specify subdomains, others not, etc).

**Comment by jcmoraisjr** [comment]
Implemented in the current snapshot. Docs are also updated. Let me know if everything is working as expected closing this issue, otherwise let me know if you have any problem.

**Comment by jcmoraisjr** [comment]
f8fb0dc implements this. Closing. Feel free to update this same issue if you have any problem.

**Comment by abh** [comment]
Thank you!
