### ISSUE TITLE
question/feature request: Affinity based on deployment version

### ISSUE THREAD

**Issue by Janpot** [jcmoraisjr/haproxy-ingress#632]
Having this case where a CDN is setup with a custom origin server pointing to a kubernetes deployment routed by haproxy. During rolling updates, requests for HTML assets should end up on instances of the same version that served the HTML. a CDN like cloudfront can forward and cache versions based on a cookie. Standard sticky sessions as they exist now would result in the CDN fetching and caching an asset for each pod. It would be great if I could implement affinity that only makes sure requests end up on the same version as the originator, stickier is not necesessary (and results in overfetching). Is something like this even possible with haproxy?

**Comment by jcmoraisjr** [comment]
Hi, would be some sort of a blue/green deployment you're looking for? You can have a look if blue/green selector (example page [here](https://haproxy-ingress.github.io/docs/examples/blue-green/#test-blue-green-selector)) is what you're looking for, or do you need something even more specialized? Please have a look also in the blue/green selector limitations, doc starts [here](https://haproxy-ingress.github.io/docs/configuration/keys/#blue-green).

**Comment by Janpot** [comment]
@jcmoraisjr 🤔  It looks like I can use `blue-green-cookie` to point to a "version" label that exists on pods. Am I right in my understanding that I can use that option to create "group affinity", even without using `blue-green-balance`?

**Comment by jcmoraisjr** [comment]
Yup, that's it. The idea behind the functionality is the ability to deploy a new version of the app/site that the user can choose to use instead of being chosen by the load balancer. Configure weight=0 and you have a version that can only be used via cookie or http header.

**Comment by Janpot** [comment]
What happens with requests that have a cookie that can't be matched with any healthy backend server?
Also, the consequence of using this is that it wouldn't load balance between those selected backends anymore, right?

**Comment by jcmoraisjr** [comment]
If the header or cookie cannot match, either to a wrong value or no healthy backend, the request will be handled as if no cookie or header was provided. Backend servers will only be removed from the formal load balance if weight=0. Choose weight=1 and mode=pod if you want a fair load balance between all your servers if no cookie/header selector is in place.
