### ISSUE TITLE
Cannot get X-SSl-* HTTP headers in PHP

### ISSUE THREAD

**Issue by sousarmb** [jcmoraisjr/haproxy-ingress#636]
Hi, 

I'm running "haproxytech/kubernetes-ingress" on local/development kubernetes cluster (Docker For Desktop). I have setup TLS termination and client certificates as per the docs but still cannot get `X-SSL-Client-SHA1`, `X-SSL-Client-DN` and `X-SSL-Client-CN` HTTP headers in PHP.

I have the following annotations on my ingress:

- `ingress.kubernetes.io/auth-tls-secret: namespace/mycompany-ca-ingress`

- `ingress.kubernetes.io/auth-tls-cert-header: "true"`

- `ingress.kubernetes.io/auth-tls-verify-client: "on"`

The `tls`spec is configured to the site TLS certificate and the secrets are also created. I'm using postman to make the requests and have configured the client certificate, signed by the CA created as per the docs and the requests are going to port 443. The service also has a port 443 and when i allow `ssl-passthrough`, apache validates the certificate. When i terminate TLS on the haproxy the request is forwarded to port 80 but no HTTP headers.

I'm quite sure this  is a configuration issue but i can't put my finger on it. Can you help?

BR,

**Comment by jcmoraisjr** [comment]
Hi, it seems you're using HAProxy Technologies implementation, please fill an issue in their [issue tracker](https://github.com/haproxytech/kubernetes-ingress/issues).

**Comment by sousarmb** [comment]
Most questions / google queries seem to come to you :). I'll bug go them. Thank you.
