### ISSUE TITLE
Getting below error message 

### ISSUE THREAD

**Issue by sid-lumina** [jcmoraisjr/haproxy-ingress#639]
kubectl expose deploy blue --name bluegreen --selector=run=bluegreen
Error from server (NotFound): deployments.apps "blue" not found

**Comment by Unichron** [comment]
So I assume you are trying out the blue/green example. Did you run the command in this previous section https://haproxy-ingress.github.io/docs/examples/blue-green/#deploying-applications ?

**Comment by jcmoraisjr** [comment]
Closing due to the lack of feedback. Please find us on slack or any other [community option](https://haproxy-ingress.github.io/community/) if you couldn't run the example.
