### ISSUE TITLE
HAProxy 2.2

### ISSUE THREAD

**Issue by Unichron** [jcmoraisjr/haproxy-ingress#652]
Hi,

any chance the haproxy version can be bumped to 2.2, either in 0.11 (preferably) or the next version? It's the next LTS release, 2.1 is going EOL next year Q1, and I would really like to have the http-after-response directive :)

I can also invest some time into making a PR for it.

**Comment by jcmoraisjr** [comment]
Hi, the current plan is to release v0.11 with 2.1 and a short v0.12 release (after a month or so) with 2.2 and an option to run haproxy as a sidecar. Such option may be backported to v0.11 as well, it depends on the amount of the changes needed, so haproxy ingress starts to be less opinionated about the haproxy version.

**Comment by jcmoraisjr** [comment]
Some update on this. Following the plan to release one HAProxy Ingress version with one haproxy version, v0.11 is going GA shortly with haproxy 2.1, and controller v0.12 will have haproxy 2.2.

v0.12 will have the ability to run an external haproxy so this controller version => haproxy version coupling will not be an issue anymore. v0.12 was a little bigger than the original plan so I'm considering to postpone some k8s 1.19 stuff to v0.13 and start stabilizing v0.12 now - so we'll have haproxy 2.2 earlier without affecting any roadmap.
