### ISSUE TITLE
Changing SSL/TLS headers

### ISSUE THREAD

**Issue by jcmoraisjr** [jcmoraisjr/haproxy-ingress#66]
On #46 some SSL/TLS headers was added following the `X-SSL-etc` convention. However [RFC 6648](http://tools.ietf.org/html/rfc6648) deprecated the recommendation of the `X-` prefix. A little few words on this subject [here](https://stackoverflow.com/q/3561381).

Because of that I'm changing these headers on `beta.3` that should be tagged and deployed later today. I'd follow the **change** route (breaking actual code) instead of duplicating/depreciating now (0.4) and only remove the `X-` on 0.5. Please leave your comment if the first (breaking now) option doesn't sound good.

/cc @Scukerman

**Comment by Scukerman** [comment]
Oh wow.

> this document deprecates the convention for newly defined parameters

I'm not sure whether they are new or not.
I googled and I have found that even haproxy.com blog uses the same headers as an example.
https://www.haproxy.com/blog/ssl-client-certificate-information-in-http-headers-and-logs/

Anyway, I haven't found any other names for these headers.
So here we have two ways of solving this issue:
1. We strictly follow the standards and all the headers, which we didn't find in RFCs, has to be renamed.
2. We keep these headers as a de-facto standard. I'm pretty sure that those headers were used even before this RFC.

So it just depends on what you think the standard is.

All that I know for sure, I have to rewrite some components I use alongside haproxy-ingress if I want to use vanilla docker image.

**Comment by jcmoraisjr** [comment]
I also have some compatibility issues to be addressed and this RFC was just a way to see "who is right, who is wrong" on this subject. Anyway I agree with your comments - one simply can choose what he want to be the standard because there is no standard.

I'll follow the 'choose your standard on configmap' route and probably leave the `X-` as the default behaviour so we don't have to break compatibility. Thank you very much for sharing your thoughts.
