### ISSUE TITLE
use TLS secrets from other namespaces

### ISSUE THREAD

**Issue by javipolo** [jcmoraisjr/haproxy-ingress#67]
It would be cool that I can specify the namespace in the secretName, so I can store TLS credentials separate from the applications

It would be handy to hide the certificate keys from developers

example:
secretName: kube-system/foobar-tls

**Comment by jcmoraisjr** [comment]
Sure. Need to change a dependency, so will **try** to include in the next release.

**Comment by javipolo** [comment]
super cool, thank you very much! :)

**Comment by jcmoraisjr** [comment]
Since the current snapshot there is a new command-line argument you can use to reference secrets from other namespaces. Closing, let me know if you have any problem updating this same issue (even closed, no problem).
