### ISSUE TITLE
ssl termination VS  ssl-redirect

### ISSUE THREAD

**Issue by zbebeto** [jcmoraisjr/haproxy-ingress#671]
Hi
If the ssl termination is provided by another software ... The annotation ingress.kubernetes.io/ssl-redirect: true does not work.
Is there any workaround ?

**Comment by jcmoraisjr** [comment]
Hi, please edit the issue following the template, I need at least your actual configuration and controller version to check if we have a bug here. If you're in doubt, send a hello in slack.

**Comment by zbebeto** [comment]
Should I follow the template for bug report then ?

**Comment by jcmoraisjr** [comment]
Hi, as stated in the [new issue selector](https://github.com/jcmoraisjr/haproxy-ingress/issues/new/choose) we kindly ask to choose between feature request or a bug report whose template should be read and filled. This changed a few weeks ago, we're moving support and QA related issues to other [community](https://haproxy-ingress.github.io/community/) places.

I'm closing this issue. Please feel free to open another one filling one of the templates if you know you found a bug or you want to request a new feature, and in the case of any doubt lets chat in slack, here is the [link](http://jitec.com.br/slack/) to the invite.
