### ISSUE TITLE
Haproxy persistence cookie attr support to append SameSite attributes

### ISSUE THREAD

**Issue by thyn** [jcmoraisjr/haproxy-ingress#674]
I need to add attributes in persistence  cookie SameSite=None, Secure. How can I do it?

Also it should be used if request support ssl

Please review

https://github.com/haproxy/haproxy/issues/361

https://web.dev/samesite-cookie-recipes/

**Comment by jcmoraisjr** [comment]
Thanks for the link. Starting on v0.11 you can workaround this using `session-cookie-keywords`, doc [here](https://haproxy-ingress.github.io/v0.11/docs/configuration/keys/#affinity). If you configure ssl-redirect as true, this will never be used on http requests.

**Comment by jcmoraisjr** [comment]
Added in `v0.12-snapshot.3`. Closing.
