### ISSUE TITLE
interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret

### ISSUE THREAD

**Issue by lumeche** [jcmoraisjr/haproxy-ingress#68]
After running some load for some time my proxy died with the following exception. It seems to me that k8s was suppoed to return something but the ingress-controller got something that he didn't expected. 

`
W1106 15:35:39.450232       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:36:09.397685       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:36:09.448310       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:37:01.749835       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:38:37.652810       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:38:42.755545       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
I1106 15:40:07.222551       7 controller.go:184] ignoring delete for ingress gwing based on annotation kubernetes.io/ingress.class
I1106 15:40:07.228940       7 controller.go:184] ignoring delete for ingress pcsproxying based on annotation kubernetes.io/ingress.class
I1106 15:40:07.234685       7 controller.go:184] ignoring delete for ingress websocketsproxying based on annotation kubernetes.io/ingress.class
W1106 15:40:07.271407       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:40:07.418308       7 controller.go:1016] ssl certificate ntg6-coreload-core/ingress-gw-cert-secret does not contain a common name for host ntg6-coreload-haproxy.eastus2.cloudapp.azure.com
W1106 15:40:07.460991       7 reflector.go:323] github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1155: watch of *v1.Secret ended with: too old resource version: 11259959 (39003766)
E1106 15:40:08.561235       7 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*v1.Secret", missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret)
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/iface.go:172
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:219
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:56
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:276
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:147
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_amd64.s:2197
E1106 15:40:08.561359       7 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*v1.Secret", missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret)
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/iface.go:172
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:219
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:56
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:276
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:147
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/asm_amd64.s:2197
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Secret

goroutine 86 [running]:
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1387e40, 0xc420d02340)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1387e40, 0xc420d02340)
	/home/travis/.gimme/versions/go1.8.1.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller.newIngressController.func5(0x13cd720, 0xc420e01140)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:219 +0x199
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0x0, 0xc4201adda0, 0xc4201addb0, 0x13cd720, 0xc420e01140)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:206 +0x49
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete(0xc420184680, 0x13cd720, 0xc420e01140)
	<autogenerated>:56 +0x73
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x1397520, 0xc4212ee300, 0x1397520, 0xc4212ee300)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:276 +0x516
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc420586300, 0xc4202b8f00, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x27e
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc4204eb700)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x40
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2a
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42057dfb0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420c3bfb0, 0x3b9aca00, 0x0, 0x12efb01, 0xc4204085a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42057dfb0, 0x3b9aca00, 0xc4204085a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc4204eb700, 0xc4204085a0)
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x237
created by github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/travis/gopath/src/github.com/jcmoraisjr/haproxy-ingress/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1155 +0x1c1
`

**Comment by jcmoraisjr** [comment]
You are apparently using v0.3. This sounds a race condition listening
delete events from secrets. This approach was changed on 0.4 and this panic
shouldn't happen anymore.

v0.4-beta.2 will probably be tagged as v0.4 without changes, please verify
if this version works fine on your cluster.

**Comment by lumeche** [comment]
Hello. You are actually correct. I was using the v 0.3. I will change the version to 0.4 and try. As you said this looks like a race condition very hard to reproduce. I'll close this ticket and if I see this again, I'll open it again.

Thank you very much for the quick answer. You saved my week.

I1103 21:09:55.401026       7 launch.go:101] &{**HAProxy v0.3** git-d118743 https://github.com/jcmoraisjr/haproxy-ingress}
