### ISSUE TITLE
How to use profiling url?

### ISSUE THREAD

**Issue by pbabilas** [jcmoraisjr/haproxy-ingress#682]
Hi, I have no more idea how to use stats uris?
As shown in docu profiling should be enabled in default but dunno how to call /debug/pprof path?
Tried at every port available but still geting 404, any hint how to use uris given here:

https://haproxy-ingress.github.io/docs/configuration/command-line/#stats

Once that works is healthz (port is given).

**Comment by jcmoraisjr** [comment]
This should work with `:10254`. I can successfully profile the controller using `go tools` like this:

```
$ go tool pprof 'http://<ingress>:10254/debug/pprof/profile?seconds=30'
$ go tool pprof -http=:8000 ~/pprof/pprof.haproxy-ingress-controller.samples.cpu.XXX.pb.gz
```

A port-forward can be configured like this (and `<ingress>` above becomes `localhost`):

```
$ kubectl -n ingress-controller port-forward pod/<haproxy-ingress-pod> 10254:10254
```

**Comment by pbabilas** [comment]
Hi, thanks for answear. its working now. dunno why I can't get it to work before. Thanks
