### ISSUE TITLE
ingress namespace/ingress for host example.org contains a TLS section but none of the host match

### ISSUE THREAD

**Issue by abh** [jcmoraisjr/haproxy-ingress#69]
For an ingress with TLS certificates on some hosts, the haproxy-ingress logs a bazillion messages about the ingress containing a TLS section, but not for host X, Y, Z.

(see also https://github.com/kubernetes/ingress-nginx/issues/1274 )

**Comment by abh** [comment]
Looks like this was fixed in  d2f0e162a496d312 (thanks!)

**Comment by jcmoraisjr** [comment]
Yup, and now this is part of the current snapshot version. Thanks for pointing this out.
