### ISSUE TITLE
Allow basic authentication customization

### ISSUE THREAD

**Issue by tomaszszlek** [jcmoraisjr/haproxy-ingress#691]
**What are you trying to do**

I would like to enable basic authentication only for specific users and url's.

**What HAProxy Ingress should do or how it should behave differently**

HaProxy ingress allows to enable basic authentication for all paths only, it doesn't allow to enable basic auth for specific URL's only. I have tried to workaround this by defining secret (which is converted then to HaProxy userlist) however it doesn't work without enabling `auth-type: basic`.

**Comment by jcmoraisjr** [comment]
HAProxy Ingress uses native ingress resource which doesn't allow to make per path customization, but you can however create two or more ingress resources for distinct paths, with distinct annotations and share the same hostname. Did you try to configure paths that need distinct configurations using two distinct ingress?

**Comment by tomaszszlek** [comment]
Thanks @jcmoraisjr for quick reply. I know its possible however in my scenario I have two kind of path:
First ingresss: /api/secure/* - I want to have basic auth there
Second ingress: /api/* - for everything else I do not want basic auth
I don't think it will work if I will create two ingress because paths covered by first ingress are subset of paths covered by second ingress. I think it would work if I will provide full path explicitly like:
First ingresss: /api/secure/* - I want to have basic auth there
Second ingress: /api/path1/, /api/path2/, /api/path3.json etc
however in my case there are hundreds of paths and would be hard for me to create two ingress with mutually exclusive paths.

My proposal of haproxy-ingress improvement is:
If in Ingress configuration you provide `ingress.kubernetes.io/auth-secret` then let's create a userlist in generated haproxy.cfg (currently it doesn't generate anything if you don't provide `auth-type: basic`).
Then you will be able to use this userlist (for example SiteUsers) in `config-backend` section and add authentication only for specific paths:

`   
  acl url_static secure_path /path
  acl AuthOkay_Web http_auth(SiteUsers)
  http-request auth realm auth_me if !url_static !AuthOkay_Web
`

**Comment by jcmoraisjr** [comment]
It doesn't matter if you configure paths in the same ingress resource or different ones, everything will be grouped by hostnames and sorted by path length (longer has higher priority) after parsed. Give this strategy a try.

**Comment by tomaszszlek** [comment]
Hi @jcmoraisjr, 

sorry for late answer,I had a long break with this and now I have implemented solution that you proposed.
I have created second ingress with basic authentication enabled. Both ingress controllers have the same backend, host but different paths. Ingress #1 refers to path "/" while ingress #2 refers to path "/my-path/resource"
The good news is that when in a browser I try to go to "/my-path/resource" then I see basic-auth window.
The bad news is that my #1 ingress doesn't fully works. What doesn't work is ACL.
I have some defined in #1 ingress that allow access to specific endpoints only from certain IP addresses.
Right now when go to /under/access then I can access it even if my IP is blacklisted.
I am investigating right now what could cause that issue and will respond as soon as I will find something.

**Comment by jcmoraisjr** [comment]
How did you configure the ACL? Some annotations doesn't work well if they conflict between distinct ingress and the same service resource. In this case you should see a warning in the log. You probably can work around this creating a new service resource (hence a new haproxy backend) that shares the same selector - so the same pods.

**Comment by tomaszszlek** [comment]
I managed to resolve my issue. After @jcmoraisjr suggestion I realized that I am using deprecated annotation `block` while the newer is `http-request deny`. After I switched to the new one everything started working as expected so I have ingress, one with some block rules and the other one with basic auth. Thank you @jcmoraisjr for help ❤️
