### ISSUE TITLE
Support arm64 - raspberry pi

### ISSUE THREAD

**Issue by ieugen** [jcmoraisjr/haproxy-ingress#709]
I tried deploy haproxy ingress chart on a raspberry pi cluster for demos and I got 

```
exec user process caused: exec format error
```
It would be nice if there are instructions on how to use this chart with arm systems.
I believe just the right image is required.

**Comment by nicolass67** [comment]
Hi ieugen,

I had the same issue. 
The haproxy ingress can be build on raspberry pi. I'm doing it on rpi4. It takes around 5-10 minutes of build time. 

My procedure: 
`https://github.com/jcmoraisjr/haproxy-ingress/releases/tag/v0.13.3`
`git checkout tags/v0.13.3 && cd haproxy-ingress`
`docker build -f builder/Dockerfile -t haproxy-ingress-arm:v0.13.3 .`

For the moment I didn't had time to test the image, but it's already a good beginning that it builds. 

Regards,

**Comment by jcmoraisjr** [comment]
arm64 is supported since v0.13, please let me know if you can use the generated image.

**Comment by nicolass67** [comment]
Hi Joao, 
I use a RPi 4 with the official Raspberry Pi OS (based on debian + update to deb 11). Kubernetes is 1.22.2. 
It seems that this OS is this arch : `Linux XXXXXX armv7l GNU/Linux`

When using the Helm Chart for haproxy-ingress, the pod doesnt start : 
`haproxy-ingress   haproxy-ingress-tg9s9                   0/1     ImagePullBackOff `

Looking at the events : 
`Failed to pull image "quay.io/jcmoraisjr/haproxy-ingress:v0.13.3": rpc error: code = Unknown desc = no matching manifest for linux/arm/v7 in the manifest list entries`

Maybe a simple retag of arm64 could do the trick ? 
As said I manage to build the docker file on this machine. I just need time to test it. 

Regards,

**Comment by jcmoraisjr** [comment]
Ah ok this doesn't seem to be supported yet, we actually only build arm/v8:

https://github.com/jcmoraisjr/haproxy-ingress/blob/420969f1065f97468f26d0ad8c8cb542e36db9f0/.github/workflows/image.yaml#L37-L42

Every new platform takes about 10 minutes to generate the image, but I'll evaluate to add some other widely used ones.

**Comment by nicolass67** [comment]
@jcmoraisjr : I built the image on the rpi4, pushed it into a private registry and used the helm chart to use this image : it works (tests: ingresses/ingressClases etc ...). 
So simply building on armv7l like rpi4 (and rpi3) solves the problem. No patching seems needed

I'll look forward for the v0.14 :-)

Thanks 

Regards,

**Comment by jcmoraisjr** [comment]
Added arm/v6 and arm/v7 support in v0.13.5, let me know if you have any problem with these platforms.
