### ISSUE TITLE
Provide redirection to primary hostname when server-aliases are defined

### ISSUE THREAD

**Issue by technicalguru** [jcmoraisjr/haproxy-ingress#715]
**What are you trying to do**

I want to provide canonical URIs. That means that different server aliases will automatically redirect to the primary hostname. 

**What HAProxy Ingress should do or how it should behave differently**

Mark one hostname as the primary hostname, e.g. via annotation, and redirect all clients to this hostname when they request one of the defined server aliases.

**Comment by jcmoraisjr** [comment]
Implemented in `v0.13.0-snapshot.1` which was just released. Closing.
