### ISSUE TITLE
Routing based on Path without host

### ISSUE THREAD

**Issue by lumeche** [jcmoraisjr/haproxy-ingress#73]
I'm trying to use an Ingress like this without the host element 

  spec:
    rules:
    -  http:
        paths:
        - backend:
            serviceName: gateway
            servicePort: myport
          path: /MyPath

And this is not creating a rule in the haproxy.cfg file to route my request to the service gateway. If I change this ingress to something like this it will work

...
spec:
  rules:
  -  host: hostname
     http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: myport
        path: /MyPath

The question here is If I absolutely have to have the host element in the ingress object. My problem is that I have some legacy clients that are not sending the Host header as part of their request so I would like to rely only in the Path to route the request from them.

**Comment by jcmoraisjr** [comment]
According to the [doc](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource) this is a feature and should be implemented. Need to fix this in upstream ingress which haproxy ingress uses as a dependency.

**Comment by jcmoraisjr** [comment]
Implemented on 6d136e8 and already on `v0.5-snapshot.3` tag.

**Comment by jcmoraisjr** [comment]
Closing. Feel free to update this same issue if you have any problem regarding default backend.
