### ISSUE TITLE
haproxy-ingress is support s390x  CRI-O runtime?

### ISSUE THREAD

**Issue by Erick-shi** [jcmoraisjr/haproxy-ingress#744]
[root@rhel8 haproxy-ingress]# kubectl  logs haproxy-ingress-7fdc9cb7f7-trl56     -n haproxy-controller
/haproxy-ingress-controller: line 1: syntax error: unexpected "("
[root@rhel8 haproxy-ingress]#

**Comment by jcmoraisjr** [comment]
Yep, currently unsupported.

**Comment by jcmoraisjr** [comment]
v0.13.5 has now a s390x image, let me know if you have any problem with this platform.

**Comment by Erick-shi** [comment]
> v0.13.5 has now a s390x image, let me know if you have any problem with this platform.

thanks, I would test it recently
