### ISSUE TITLE
www/non-www redirect missing

### ISSUE THREAD

**Issue by pbabilas** [jcmoraisjr/haproxy-ingress#747]
**www/non-www redirect**

I'd like to set automatic global www/non-www (and reverse) redirect by ingress.
Prefer annotation www-redirect and www-redirect-reverse to control which ingress should has that redirect.

Is there any way to get this? or maybe it's already under construction? :)

**Comment by jcmoraisjr** [comment]
Currently unsupported but it should be pretty simple add something like "redirect-from" with a comma-separated list of domains from where you want a redirect. Feel free to link other controllers that already implement so we can choose a better approach.

**Comment by jcmoraisjr** [comment]
Actually this is a dupe of #715 , closing this on behalf of the other.
