### ISSUE TITLE
Inconsistent backend (and cookie) names when using "backend-server-naming: pod"

### ISSUE THREAD

**Issue by MartinKirchner** [jcmoraisjr/haproxy-ingress#759]
**Description of the problem**

We use this image: `quay.io/jcmoraisjr/haproxy-ingress:v0.11`

My service is annotated with these options:
```
ingress.kubernetes.io/affinity: cookie 
ingress.kubernetes.io/backend-server-naming: pod 
ingress.kubernetes.io/config-backend: 
  hash-type consistent 
  option httpchk GET /mycontextpath/check 
  http-check disable-on-404 
  http-check expect status 200 
  http-request set-header X-CAS-PROTOCOL-SCHEME https:443 
  acl is_root path -i / 
  redirect code 301 location https://mydomain.com/mycontextpath if is_root 
ingress.kubernetes.io/session-cookie-dynamic: "false" 
ingress.kubernetes.io/session-cookie-keywords: nocache 
ingress.kubernetes.io/session-cookie-name: lb_server_used 
```

After several `helm upgrade` my pods are currently named like this:
```
$ kubectl --context live -n live get po
NAME                                                              READY   STATUS      RESTARTS   AGE
live-smartwe-application-main-ingress-6f9b6d9bf9-dpnr4            2/2     Running     1          20d
live-smartwe-application-main-ingress-6f9b6d9bf9-pnbq8            2/2     Running     1          20d
live-smartwe-application-main-ingress-6f9b6d9bf9-t4q8d            2/2     Running     0          8d
```

Now I noticed that the cookie in my browser does not match any of these pod names.

When I checked the generated `haproxy.cfg` I then saw that it is different on several of my four `haproxy-ingress`-instances:

`haproxy.cfg` from `haproxy-ingress-n74w2`:
```
backend live_live-smartwe-application-main-ingress_http-port
    ...
    server live-smartwe-application-main-ingress-77d8b487b8-7wzpc 192.168.243.121:8080 weight 1 cookie live-smartwe-application-main-ingress-77d8b487b8-7wzpc check inter 2s
    server live-smartwe-application-main-ingress-77d8b487b8-bbj2g 192.168.80.194:8080 weight 1 cookie live-smartwe-application-main-ingress-77d8b487b8-bbj2g check inter 2s
    server live-smartwe-application-main-ingress-77d8b487b8-vb24d 192.168.120.23:8080 weight 1 cookie live-smartwe-application-main-ingress-77d8b487b8-vb24d check inter 2s
```

Example from `haproxy-ingress-jbk98`:
```
backend live_live-smartwe-application-main-ingress_http-port
    ...
    server live-smartwe-application-main-ingress-678f6784f8-66dq9 192.168.80.194:8080 weight 1 cookie live-smartwe-application-main-ingress-678f6784f8-66dq9 check inter 2s
    server live-smartwe-application-main-ingress-678f6784f8-cdmwj 192.168.120.23:8080 weight 1 cookie live-smartwe-application-main-ingress-678f6784f8-cdmwj check inter 2s
    server live-smartwe-application-main-ingress-678f6784f8-vjc7b 192.168.243.121:8080 weight 1 cookie live-smartwe-application-main-ingress-678f6784f8-vjc7b check inter 2s
```
However, the IPs are correct.

The result is that *sticky* sessions are only sticky as long as the request are routed through the same ingress controller instance.

**Expected behavior**

All haproxy-ingress instances use the same pod names as backend names.

**Steps to reproduce the problem**

1. Annotate service with `backend-server-naming: pod`
2. Deploy application
3. Upgrade application with `helm upgrade` --> pod names change
4. Check haproxy.cfg on several instances of haproxy

**Environment information**

HAProxy Ingress version: `v0.11`

Installation was done like this with attached [values.yml](https://github.com/jcmoraisjr/haproxy-ingress/files/6170064/values.yml.txt):
```
helm repo add haproxy-ingress https://haproxy-ingress.github.io/charts
helm install haproxy-ingress haproxy-ingress/haproxy-ingress --create-namespace --namespace=ingress-controller --values values.yml
```

**Comment by jcmoraisjr** [comment]
If I understood you correctly, this is an expected behavior when you use a backend server naming other than `sequence` (the default), dynamic update and sticky sessions, as stated in the [doc](https://haproxy-ingress.github.io/docs/configuration/keys/#backend-server-naming). If you cannot use `sequence` naming, you can try to disable dinamic update.

**Comment by MartinKirchner** [comment]
Thanks for your answer. But isn't that the idea of using `pod` as naming strategy to get deterministic cookie values through out all instances of the ingress controller?
My expectation would be that all instances notice changes in the deployments and update their backend section with the available pod names accordingly and not that one haproxy pod has three week old pod names, the other six week old pod names.
I want requests to be routed to e.g. `live-smartwe-application-main-ingress-6f9b6d9bf9-dpnr4` as long as it's up and running and that's why I use it as backend name AND cookie value. If the pod is replaced/deleted the session lost and a new backend has to be assigned.

**Comment by jcmoraisjr** [comment]
You can have deterministic values using dynamic cookies, which uses the backend server ip:port to calculate its value. This works with any backend server naming.

At this moment backend server names are immutable, cannot be updated using the runtime api and need haproxy to reload a new configuration in order to update it. Because of this lack of support the doc states that naming other than sequential does not work well with dynamic updates.

**Comment by MartinKirchner** [comment]
@jcmoraisjr I now see that haproxy supports the feature of dynamically editing of backend server via runtime api since version 2.6. Is this now also supported by the ingress controller?
I couldn't find anything in the changelog.

**Comment by jcmoraisjr** [comment]
Hi Martin, I think I missed this one.

Yes this is part of the v0.17 changelog - https://github.com/jcmoraisjr/haproxy-ingress/blob/master/CHANGELOG/CHANGELOG-v0.17.md#major-improvements
