### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by tacerus** [jcmoraisjr/haproxy-ingress#762]
Hi,
the helm installation command will get stuck creating clusters. It was necessary not to specify a version for the initial install in order for my system to complete the installation.

`helm install haproxy-ingress haproxy-ingress/haproxy-ingress --namespace ingress-controller -f haproxy-ingress-values.yaml --debug`

**Comment by jcmoraisjr** [comment]
Cannot reproduce this. Please reach us on slack and describe a bit more about your env, the pending resources and so forth. We're using github issues exclusively for error tracking, features and prs.
