### ISSUE TITLE
Echoserver Deployment

### ISSUE THREAD

**Issue by tacerus** [jcmoraisjr/haproxy-ingress#763]
Hi,

The
`kubectl create deployment echoserver --image k8s.gcr.io/echoserver:1.3`
example does not run. The deployment gets stuck 
`kubectl get deployments

NAME             READY   UP-TO-DATE   AVAILABLE   AGE

echoserver       0/1     0            0           4m27s`

`kubectl describe deployment/echoserver
Name:                   echoserver
Namespace:              default
CreationTimestamp:      Sat, 10 Apr 2021 21:05:59 +0200
Labels:                 app=echoserver
Annotations:            <none>
Selector:               app=echoserver
Replicas:               1 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=echoserver
  Containers:
   echoserver:
    Image:        k8s.gcr.io/echoserver
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
OldReplicaSets:   <none>
NewReplicaSet:    <none>
Events:           <none>
`

I assume the image link is faulty. Could an updated one be provided?

**Comment by jcmoraisjr** [comment]
Cannot reproduce this. Please lets move the discussion to slack since we're using github issues exclusively for error tracking and feature requests.
