### ISSUE TITLE
unknown controller argument : --log

### ISSUE THREAD

**Issue by sunnie324** [jcmoraisjr/haproxy-ingress#771]
**Description of the problem**
Added the following controller arguments in HAProxy deployment
```
- args:
    - --default-backend-service=$(POD_NAMESPACE)/svc-dbe
    - --default-ssl-certificate=default/tls-secret
    - --configmap=$(POD_NAMESPACE)/ic-config-params
    - --allow-cross-namespace=true
    - --log=debug
```
Haproxy image: quay.io/jcmoraisjr/haproxy-ingress:v0.12.1

**Expected behavior**

Debug logs should be enabled

**Actual behavior**

Container is unable to start with the error - 2021-04-23T16:13:25.592345642Zunknown flag: --log

**Environment information**

HAProxy Ingress version: `v0.12.1`

**Comment by jcmoraisjr** [comment]
This is an expected error, the controller doesn't support such command-line option. Use `--v=2` instead.

**Comment by sunnie324** [comment]
Thanks for your reply. 
Can elaborate on the arg : --v . I did not find any documentation on the same.

**Comment by jcmoraisjr** [comment]
Command line options need some update for sure. `--v` changes the default verbosity from 1 to another level. 2 is good enough to be a default where you have a few more info without flooding your log stream. 3 and higher is verbose and only used in the remaining code of the old controller, so currently isn't useful at all. In short, add `--v=2` to your command-line options and you'll be fine.
