### ISSUE TITLE
console logs and logs persisting to a file

### ISSUE THREAD

**Issue by sunnie324** [jcmoraisjr/haproxy-ingress#781]
Enabled debug level 3 (--v=3). 

Actual Result: Debug logs are enabled and visible only on container console.
Expected Result: Debug logs should be visible on console or can be persisted to a file or both.

Our idea is to persist the log file for further triaging and debugging.

'syslog-endpoint' only captures HAProxy access logs and  not the admin debug logs. Correct me if I am wrong.

**Comment by jcmoraisjr** [comment]
HAProxy can currently generate logs in two distinct ways: syslog or stdout. syslog is the way that always work, just configure an endpoint that does what you need to be done. HAProxy itself can send also to the stdout but it need to be configured as a sidecar, doc [here](https://haproxy-ingress.github.io/docs/examples/external-haproxy/). The helm chart can also help you to configure an access-logs sidecar that receives the logs via syslog and sends it to the stdout, and after that is up to you and your infrastructure configuration.

Feel free to continue the discussion in our slack channel - I saw you've already started it there.
