### ISSUE TITLE
Domain name validation regex not allowing "-"

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#790]
**Description of the problem**

I tried to use the `secure-sni` configuration key and set it to `data-graph.azurewebsites.net`. I got an error 

```
W0601 09:49:40.915372       6 backend.go:646] skipping invalid domain (SNI) on service 'core/data-graph': data-graph.azurewebsites.net
```

I believe the error is that this [line](https://github.com/jcmoraisjr/haproxy-ingress/blob/613f22728d798691fa2e83a7cc5e7145a116870a/pkg/converters/ingress/annotations/backend.go#L750): 

```golang
var validDomainRegex = regexp.MustCompile(`^[A-Za-z0-9.]*$`)
```

does not allow "-" in domain names.

**Environment information**

HAProxy Ingress version: `v0.12.2`

**Comment by jcmoraisjr** [comment]
Fixed in v0.12.4! Closing.
