### ISSUE TITLE
HAProxy web interface access

### ISSUE THREAD

**Issue by guillermocol** [jcmoraisjr/haproxy-ingress#792]
**Description of the problem**
Dear Team,

I have installed haproxy and all seems fine with the service and the processes, however I am not able to reach the web interface. It seems it can't connect, but I don't have any firewall restrictions on my side.

This is my current configuration: I cannot really see anything wrong with it.

global
log /dev/log local0
log /dev/log local1 notice
chroot /var/lib/haproxy
stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
stats timeout 30s
user haproxy
group haproxy
daemon

# Default SSL material locations
ca-base /etc/ssl/certs
crt-base /etc/ssl/private

# Default ciphers to use on SSL-enabled listening sockets.
# For more information, see ciphers(1SSL). This list is from:
#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
# An alternative list with additional directives can be obtained from
#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
ssl-default-bind-options no-sslv3
defaults
log global
mode http
option httplog
option dontlognull
timeout connect 5000
timeout client 50000
timeout server 50000
errorfile 400 /etc/haproxy/errors/400.http
errorfile 403 /etc/haproxy/errors/403.http
errorfile 408 /etc/haproxy/errors/408.http
errorfile 500 /etc/haproxy/errors/500.http
errorfile 502 /etc/haproxy/errors/502.http
errorfile 503 /etc/haproxy/errors/503.http
errorfile 504 /etc/haproxy/errors/504.http

listen stats
mode http
bind *:7000
stats enable
stats uri /

listen postgres
bind *:5000
option httpchk
http-check expect status 200
default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions

Thank you for your help,
Gcol

**Expected behavior**

**Steps to reproduce the problem**

1. 
2. 
3. 

**Environment information**

HAProxy Ingress version: `v0.xx`

Command-line options:

```
(paste command-line options here)
```

Global options:

```
(paste global configmap options here)
```

Ingress objects:

```
(paste ingress objects here)
```

**Comment by jcmoraisjr** [comment]
It seems you're not using HAProxy Ingress? We don't have a web interface and you didn't also complete the whole template file.

**Comment by guillermocol** [comment]
Hi jcmoraisjr, thank you for your message. I didn't use yet the haproxy ingress kubernetes set up, I was testing to use it first in the server itself, but I cannot manage to make it work 100% I think.

**My version is:** HA-Proxy version 1.8.19-1+deb10u3 2020/08/01
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

**Steps to reproduce the issue:**

1. Install haproxy in linux debian10
2. systemctl status haproxy > it appears running
3. check web interface http://x.x.x.x:7000 
4. Not able to get web interface access. Something got configured wrongly or something is missing.

Thank you for your help,
gcol

**Comment by jcmoraisjr** [comment]
> My version is: HA-Proxy version 1.8.19-1+deb10u3 2020/08/01

Hi, so please report in the haproxy channels. They don't use github issues as a support channel to users, so I suggest you to write to the mailing list or to [discourse](https://discourse.haproxy.org/).
