### ISSUE TITLE
Stable server IDs for consistent-hash balancing

### ISSUE THREAD

**Issue by arodland** [jcmoraisjr/haproxy-ingress#798]
**What are you trying to do**

I have a service that I'm migrating to k8s. It currently uses haproxy with `balance uri` and `hash-type consistent` to distribute traffic in a way that sends requests for related pieces of content to the same backend server, which increases cache performance by a lot. This mapping should remain stable across reloads and when servers are added and removed (only the portion of the hash ring corresponding to the new/removed server should change, the whole list shouldn't shuffle).

For this, it's not good enough just to sort the list and let haproxy assign sequential IDs, because an addition or removal in the middle of the list disturbs everything after it. So, our existing system assigns a unique ID to each server and passes that as the `id` in the `server` line, which haproxy uses as that server's hash seed.

I'd like to be able to do something similar with haproxy-ingress.

**What HAProxy Ingress should do or how it should behave differently**

Provide a way to set the `id` field of a `server` based on some stable property of the pod backing it (UUID, or name, or IP). HAProxy `id` is a 32-bit value, so a hash truncated to 32 bits would seem to be appropriate.

Since the `id` must be unique, in the case of a collision, I would suggest using a stable [open-addressing](https://en.wikipedia.org/wiki/Open_addressing) technique by taking the servers in lexicographic order, and if a slot is already taken, rehashing or probing forward until a free slot is found. For reasonable numbers of servers, collisions should happen extremely rarely (<0.1% chance of a collision for up to 2900 servers), so this technique is only a *tiny* bit less stable than one that uses persistent unique IDs.

**Comment by jcmoraisjr** [comment]
Added in `v0.13.0-beta.2`. Closing.
