### ISSUE TITLE
Q: Support for keepalived to enable HA

### ISSUE THREAD

**Issue by thekalinga** [jcmoraisjr/haproxy-ingress#8]
I see that there is a project that enables keep alived within kubernetes.
https://github.com/kubernetes/contrib/tree/master/keepalived-vip

Just wanted to check if the following topology for high available load balancer configuration is supported with floating ips

![ha proxy high avaiability](https://cloud.githubusercontent.com/assets/452518/24512810/33e3d9ec-158d-11e7-837c-7bb8579ddcd1.png)

**Comment by rikatz** [comment]
@jcmoraisjr You could use the same stickness session implemented in NGINX, with the first set cookie containing the route that the Frontend took to the pod.

https://github.com/kubernetes/ingress/blob/master/examples/affinity/cookie/nginx/README.md

Anyway don't know if HAProxy supports this kind of affinity :)

**Comment by jcmoraisjr** [comment]
Closing this issue. You can add a new comment if you have any doubt.

**Comment by guptaarvindk** [comment]
best solution is to run keepliaved as side care container to HAPROXY.
