### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by karstensi** [jcmoraisjr/haproxy-ingress#80]
Hi,

I have tried to add websockets and use ssl termination in haproxy-ingress.
From what I can read in the docs I need to set a Upgrade header. 

Is this supported ?

**Comment by jcmoraisjr** [comment]
Hi, HAProxy does support websockets out of the box. Have a look at the `timeout-tunnel` configmap option, which defaults to `1h`, and also [HAProxy doc](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-timeout%20tunnel) about this timeout.

**Comment by Scukerman** [comment]
Currently I'm using websockets. All is ok.

**Comment by karstensi** [comment]
I will dig some more into this.
The web sockets works, if I do not use ssl-termination and just regular http.

Thanks for your feedback.

**Comment by coelh0** [comment]
Hi guys, any documentation regarding ingress usage with kubernetes and websockets? Thanks!

**Comment by jcmoraisjr** [comment]
If you're talking about haproxy ingress, websocket just work out of the box as I've stated [almost 4 years ago](https://github.com/jcmoraisjr/haproxy-ingress/issues/80#issuecomment-350721519) in this same issue. Maybe you want to tune timeout-tunnel which haproxy will use to close inactive connections, and also timeout-stop used to close active connections after a reload event.
