### ISSUE TITLE
haproxy-ingress controller with port 9443

### ISSUE THREAD

**Issue by shzshi** [jcmoraisjr/haproxy-ingress#808]
Hi 

I am new to haproxy-ingress controller our application always look for port 9443 , i have setup haproxy-ingress controller in front of app & service and currently haproxy just support port 443 and 80 , how do I make it to expose 9443 , something like below. 

https://haproxy-ingress-endpoint:9443 -> service:9443 -> app:9443

I also read through this , but not sure how to implement it. 

https://haproxy-ingress.github.io/docs/configuration/keys/#bind

Your help would be really appreciated 

Cheers,
Shashi

**Comment by jcmoraisjr** [comment]
Have a look at the bind port config keys, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#bind-port). Please as stated in the issue template use the slack or the mailing list for support requests, this issue tracker is used only for bugs and feature requests.
