### ISSUE TITLE
Configuration not reloaded when basic auth secret is changed

### ISSUE THREAD

**Issue by changwuf31** [jcmoraisjr/haproxy-ingress#81]
Right now, the only way to reload the changes, is by deleting and re-applying the ingress that use the updated secret.

Is this a known issue ?
I'm using the snapshot version.

**Comment by jcmoraisjr** [comment]
This wasn't known, thanks for reporting. Already fixed on `v0.5-beta.1`. Both `canary` and `snapshot` tags was updated.

@aledbf @rikatz FYI this should be broken on nginx as well.

Closing, just update this same issue if you still have any problem regarding basic authentication.
