### ISSUE TITLE
Support adding custom rules to backend

### ISSUE THREAD

**Issue by javipolo** [jcmoraisjr/haproxy-ingress#82]
In several cases I need to set up some rewrites with requirep and for that I have to modify the template and those rewrites are applied to every backend

It would be cool to be able to specify custom haproxy code

Here's the documentation of "voyager" that is doing that already in case I did not explain myself properly:
https://github.com/appscode/voyager/blob/master/docs/user-guide/ingress/backend-rule.md

PD: Thanks A LOT for haproxy-ingress

**Comment by jcmoraisjr** [comment]
Already in the roadmap of the next release!

> PD: Thanks A LOT for haproxy-ingress

Thanks for evaluating it!

**Comment by jcmoraisjr** [comment]
A couple of months later ... I've just released the first beta of v0.6 which implements backend config snippet. [Docs](https://github.com/jcmoraisjr/haproxy-ingress#configuration-snippet) updated as well. Closing.
