### ISSUE TITLE
Allow configuring Cache-Control header in autogenerated responses

### ISSUE THREAD

**Issue by Cynocracy** [jcmoraisjr/haproxy-ingress#823]
**What are you trying to do**

Hi! First off, thanks for the solution, we're using it to great success!

In our setup, we're using CloudFlare cache on top of HAProxy -> backend, and we have browser caching enabled.
The issue, aiui, with sending no-cache, is that this doesn't impact the browser cache, which will treat the request as valid (and storeable).

**What HAProxy Ingress should do or how it should behave differently**
Given that a change from no-cache -> no-store could be backward incompatible, it would be nice to have a config option that allows for changing the cache control header on HAProxy generated responses (lua and non-lua ones even, using error_pages, would be even better!)

Happy to brainstorm about how to expose that option, but to me it seems like a per-frontend option (or global).
Also happy to help contribute the feat :)

**Comment by Cynocracy** [comment]
We're successfully working around this by volume mounting an alternative services.lua, fwiw, but that feels fragile (we might not keep up with the status codes, or the interaction between files might change)

**Comment by jcmoraisjr** [comment]
Hi, thanks for the fr and sorry about taking so long to comment. Yes, lets make it happen, I'm already planning to implement a simple way to override the default response data for all possible http status code we manage, which I think will somewhat help in this issue. I'll draw a bit more the solution as soon as I have more details, but should be something like a new configmap entry per status code, configured as a multi-line content with the raw http output. Does it seem to help on your use case?

**Comment by Cynocracy** [comment]
That sounds like it would work for our use case, thank you!

**Comment by jcmoraisjr** [comment]
Finally added to v0.14.0-alpha.2. Closing.
