### ISSUE TITLE
sending header "Connection: close" when syscall.SIGTERM is received

### ISSUE THREAD

**Issue by lumeche** [jcmoraisjr/haproxy-ingress#83]
First of all I give you some context.
Our clients have a connection pool for performance reasons and sends all the request through them.
I know that during the rolling update, haproxy-ingress-controller will receive a sigterm message from k8s. What I presume it happens is that no new connections will be opened with the haproxy that received the sigTerm and instead they will be opened with the new haproxy created during the rolling update. 
Since our clients don't close the connections when they got the response and instead continue sending to the same ones I may have a problem.

 My question is if part of this gracefully shutdown haproxy will also send the Connection:close header to the client so the clients close that connection and open a new one?

**Comment by jcmoraisjr** [comment]
Perhaps this recent [post](https://www.mail-archive.com/haproxy@formilux.org/msg28508.html) from Willy on HAProxy mailing list might help. Regarding `hard-stop-after` this is a 1.8 feature and will be added to the 0.6 version of the controller.
