### ISSUE TITLE
helm install command is wrong

### ISSUE THREAD

**Issue by jhughes2112** [jcmoraisjr/haproxy-ingress#834]
`helm search repo` shows that there are only two charts available:
```
haproxytech/haproxy                             1.5.1           2.4.2           A Helm chart for HAProxy on Kubernetes
haproxytech/kubernetes-ingress                  1.16.2          1.6.5           A Helm chart for HAProxy Kubernetes Ingress Con...
```

However, the helm install command on the [Getting Started](https://haproxy-ingress.github.io/docs/getting-started/) page shows `haproxy-ingress` which is bit of a stumbling block if you don't know how to dig through helm.  (I don't very well, at least.)

**Comment by jhughes2112** [comment]
Looks like there are two different helm repos.  It's really easy to get this crosswired if you go to more than one page in the documentation.

**Comment by jcmoraisjr** [comment]
Yep, and just to clarify, HAProxy Ingress (this repo and the getting started guide you linked above) and HAProxy Tech's Kubernetes Ingress are two distinct controllers.
