### ISSUE TITLE
oauth2-proxy configuration insecure

### ISSUE THREAD

**Issue by mkkot-onegini** [jcmoraisjr/haproxy-ingress#838]
The configuration provided here:
https://github.com/jcmoraisjr/haproxy-ingress/blob/master/examples/auth/oauth/app.yaml

works as expected when oauth2-proxy service is available on the cluster. If it gets removed for some reason (human error, misconfiguration), the haproxy will allow connection to secured service without any authentication and authorization.

```
I0812 14:22:10.153076       7 controller.go:281] Starting HAProxy update id=436
W0812 14:22:10.153561       7 ingress.go:143] skipping backend config of ingress 'app': service namespace/oauth2-proxy was not found
```

The haproxy should not allow unauthenticated traffic to the service.

**Steps to reproduce the problem**

1. Deploy the example configuration from https://github.com/jcmoraisjr/haproxy-ingress/tree/master/examples/auth/oauth
2. Remove oauth2-proxy service
3. Try to reach the echoservice via ingress

**Environment information**

HAProxy Ingress version: v0.10.9

**Comment by jcmoraisjr** [comment]
v0.13 has a new auth external and oauth implementation that doesn't have this issue. v0.12 and olders were already fixed and a new release should be issued shortly.

**Comment by jcmoraisjr** [comment]
All supported versions updated. Closing.
