### ISSUE TITLE
The default backend /metrics path is exposed externally

### ISSUE THREAD

**Issue by mhyllander** [jcmoraisjr/haproxy-ingress#839]
**Description of the problem**

If you send a request like http://mydomain.example.com/metrics to the ingress port, and there are no ingress rules that match this request, the request is forwarded to the default backend. The default backend normally returns a 404 for all requests, except when it actually implements that path. And in this case the /metrics endpoint returns the Prometheus metrics for the default backend to the client.

**Expected behavior**

I would prefer that a 404 is returned whenever no ingress rules match the request. I think any paths that the default backend handles should be blocked for external access. 

**Steps to reproduce the problem**

**Environment information**

HAProxy Ingress version: `v0.12.3`

Command-line options:

```
(paste command-line options here)
```

Global options:

```
(paste global configmap options here)
```

Ingress objects:

```
(paste ingress objects here)
```

**Comment by jcmoraisjr** [comment]
Helm chart 0.13.2 has a new default backend which doesn't have the /metrics issue. Branch of older versions has also this update and they are just waiting a new controller tag to be updated as well. Closing.
