### ISSUE TITLE
FullSlots BackendEndpoint is incorrect

### ISSUE THREAD

**Issue by EmpireJones** [jcmoraisjr/haproxy-ingress#84]
I believe in [stats_socket.go:201](https://github.com/jcmoraisjr/haproxy-ingress/blob/939bd129c86d9b27b12e6d7a50c799d8496ab8f3/pkg/controller/stats_socket.go#L201) BackendEndpoint is getting a local memory address for endpoint, which is re-used for each iteration of the loop, meaning that all of the BackendEndpoints in FullSlots are set to the last of the list of endpoints:

    // use addr:port as BackendServerName, don't generate empty slots
    for _, endpoint := range updBackendsMap[backendName].Endpoints {
    	target := fmt.Sprintf("%s:%s", endpoint.Address, endpoint.Port)
    	newBackend.FullSlots[target] = types.HAProxyBackendSlot{
    		BackendServerName: target,
    		BackendEndpoint:   &endpoint,
    	}
    }

To fix this, you should be able to make a local copy of the object, and then take the address of that.

**Comment by jcmoraisjr** [comment]
Fixed on #85
