### ISSUE TITLE
Support wildcards in `ingress.kubernetes.io/cors-allow-origin`

### ISSUE THREAD

**Issue by nabadger** [jcmoraisjr/haproxy-ingress#853]
**What are you trying to do**

I'm making use of `ingress.kubernetes.io/cors-allow-origin` across multiple-domains and it would handy if we could support something like:

`ingress.kubernetes.io/cors-allow-origin: "*.example.com, *.example2.com"`

I think perhaps the current option of `*` is not restrictive enough for my needs...but at the same time being able to use wildcards for different domains would save a lot of management overhead (we have lots of hosts...).

Related: https://github.com/jcmoraisjr/haproxy-ingress/issues/477

**Comment by wolf-cosmose** [comment]
I need a similar feature, though for my usecase it'd be best to support regexes.
From what I've seen, it'd be simple to implement in haproxy config, just a matter of adding `-m reg` to the ACLs in the template. However, haproxy-ingress's validation of the cors-allow-origin annotation doesn't allow regexes.

Currently I'm working it around using `haproxy-ingress.github.io/config-backend` with a copy of the CORS logic from the template, except with `acl my_cors_allow_origin var(txn.my_hdr_origin) -m reg ^http://localhost:.*$ ...`

Would a pull request adding sth like `cors-allow-origin-regex` be accepted?

**Comment by jcmoraisjr** [comment]
Hi, thanks for the proposal, sure it'd be a welcome contribution.
