### ISSUE TITLE
Gateway APIs: Default path '/' only routes to '/' and no matches behind it

### ISSUE THREAD

**Issue by jkotalik** [jcmoraisjr/haproxy-ingress#866]
**Description of the problem**

I'm trying out the new Gateway API support and hit some snags that seem like unexpected behavior around default paths.

I followed https://haproxy-ingress.github.io/docs/configuration/gateway-api/ and realized that if I navigate to http://hostname/, the site loads the sample correctly, but if I goto http://hostname/foo, I get a 404. This is surprised me as I would expect the route to be catch all for any path to http://hostname.

I then added a match to the configuration:
```
    Matches:
      Path:
        Type:   Prefix
        Value:  /foo
```

And I started seeing different behavior, where http://hostname/foo routed successfully, but http://hostname/foo/bar also routed to the service successfully as well.

**Steps to reproduce the problem**

1. Deploy tutorial for gateway api https://haproxy-ingress.github.io/docs/configuration/gateway-api/
2. Try navigating to the controller normally, see it routes successfully
3. Try navigating to the controller with something after '/', see 404.

**Comment by jcmoraisjr** [comment]
Hi, couldn't reproduce this. What controller version? Maybe you have ingress objects sharing the same hostname? I can however reproduce some issues because echoserver always redirect to https due to the missing of the x-forwarded-proto as https, but this apparently isn't related with your description.

**Comment by jkotalik** [comment]
I think this may be a misunderstanding on haproxy. What's the difference between Prefix vs ImplementationSpecific for matching '/'?

**Comment by jcmoraisjr** [comment]
Prefix and ImplementationSpecific match `/` in the same way. Please configure in a way that the requests doesn't work as expected and send the content of all the `/etc/haproxy/maps/_front_http*.map` files.
