### ISSUE TITLE
add SHA-2 to ingress.kubernetes.io/auth-tls-cert-header

### ISSUE THREAD

**Issue by Yosique** [jcmoraisjr/haproxy-ingress#881]
According to https://www.ietf.org/rfc/rfc9155.txt SHA1 and MD5 should no longer be used.
In https://github.com/haproxy/haproxy/issues/123 support for SHA-2 was added for haproxy.
Please add `X-SSL-Client` headers for the SHA-2 family.

**Comment by jcmoraisjr** [comment]
Added to v0.14.0-alpha.2, thanks for the suggestion. Closing.
