### ISSUE TITLE
Domain attribute in Set-Cookie header should not have multiple possible values

### ISSUE THREAD

**Issue by hbobenicio** [jcmoraisjr/haproxy-ingress#888]
Hi, @jcmoraisjr . Hope you're doing well!

**Description of the problem**

Sorry if not very descriptive or precise, I'm not an k8s/ingress expert. I'll try my best.

https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/rootfs/etc/templates/haproxy/haproxy.tmpl#L676

[haproxy.tmpl](https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/rootfs/etc/templates/haproxy/haproxy.tmpl#L676) is rendering multiple values for the domain attribute, which results in multiple domain attributes set for the Set-Cookie response header, when using *Session Cookies* and trying to *share* them. Headers like this may then be returned by the ingress:

```
set-cookie: INGRESSCOOKIE=2efcdeadcafe287c; path=/; domain=foo.org; domain=foo.com; domain=www.foo.com; HttpOnly
```

The thing is that multiple attributes with the same key (in this case, "domain"), happens to *just override* previous values. Servers should not rely on this either. This is what I found about it:

> "[...] To maximize compatibility with user agents, servers SHOULD NOT produce two attributes with the same name in the
   same set-cookie-string. [...]"
>
> https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1

> "[...] If the cookie-attribute-list contains an attribute with an
>        attribute-name of "Domain":
>
>           Let the domain-attribute be the attribute-value of the last
>           attribute in the cookie-attribute-list with an attribute-name
>           of "Domain".
>
> https://datatracker.ietf.org/doc/html/rfc6265#section-5.3

In the above example, user agents should then only send INGRESSCOOKIE to the last value, www.foo.com.

If accessing "foo.org" or "foo.com" with Google Chrome it warns us about this response header defect like this:

```
"This attempt to set a cookie via a Set-Cookie header was blocked because its Domain attribute was invalid with regards to the current host url"
```

Then the Cookie Sharing between multiple domains does not work.

In fact, the correct way if one wants to define the *domain* Set-Cookie attribute is giving just one value. And in the context of sharing it to different domains, only subdomains (in my understanding) are allowed. This is what I found.

> "The Domain attribute specifies those hosts to which the cookie will
>   be sent.  For example, if the value of the Domain attribute is
>   "example.com", the user agent will include the cookie in the Cookie
>   header when making HTTP requests to example.com, www.example.com, and
>   www.corp.example.com.  (Note that a leading %x2E ("."), if present,
>   is ignored even though that character is not permitted, but a
>   trailing %x2E ("."), if present, will cause the user agent to ignore
>   the attribute.)  If the server omits the Domain attribute, the user
>   agent will return the cookie only to the origin server."
>
> "The user agent will reject cookies unless the Domain attribute
>   specifies a scope for the cookie that would include the origin
>   server.  For example, the user agent will accept a cookie with a
>   Domain attribute of "example.com" or of "foo.example.com" from
>   foo.example.com, but the user agent will not accept a cookie with a
>   Domain attribute of "bar.example.com" or of "baz.foo.example.com".
>
>   NOTE: For security reasons, many user agents are configured to reject
>   Domain attributes that correspond to "public suffixes".  For example,
>   some user agents will reject Domain attributes of "com" or "co.uk".
>   (See Section 5.3 for more information.)"
>
> - https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.3

Relevant Code Sites:

- Backend Annotation: BackSessionCookieShared = "session-cookie-shared": https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/pkg/converters/ingress/types/annotations.go#L161
- https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/pkg/converters/ingress/annotations/backend.go#L74
- https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/rootfs/etc/templates/haproxy/haproxy.tmpl#L676

Other References:

- https://datatracker.ietf.org/doc/html/rfc6265

**Expected behavior**

Only one value for the Domain attribute for Set-Cookie must be produced by the server.

If sharing cookies beetwen host domains is intended, only subdomains must be allowed. The haproxy-ingress controller could maybe get the common root domain from all hostnames and set only one domain attribute or maybe delegate this to the final user (letting him pick the correct value for his sharing use case).

**Steps to reproduce the problem**

1. Configuration: Use Backend Annotation: [BackSessionCookieShared = "session-cookie-shared"](https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/pkg/converters/ingress/types/annotations.go#L161). It will set [this](https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/pkg/converters/ingress/annotations/backend.go#L74) and trigger [this condition](https://github.com/jcmoraisjr/haproxy-ingress/blob/5887cc3aeb9682668f0b241a9b0b14375ab4c844/rootfs/etc/templates/haproxy/haproxy.tmpl#L675) on the haproxy.tmpl
2. `$backend.Hostnames` must have multiple values

**Environment information**

HAProxy Ingress version: Not sure... I'm not the Op guy from our cluster =P. But I think this affects versions up to master by the time I'm writting this.

*Sorry, I don't have those*

Command-line options:

```
(paste command-line options here)
```

Global options:

```
(paste global configmap options here)
```

Ingress objects:

```
(paste ingress objects here)
```

**Comment by jcmoraisjr** [comment]
Hi thanks for reporting this. I can reproduce the issue but unfortunately this is how this option was designed to work, and there isn't a safe way to look into the list of hostnames that shares the same backend and derive the correct one that should be used in the persistence cookie. Btw the correct one could be none of them. So it seems better to deprecate it and create a new configuration that allows the user to define what's the domain that should be configured in the persistence cookie. The new option `session-cookie-domain` should be added in the next v0.13 tag, to be issued later this week.

**Comment by jcmoraisjr** [comment]
v0.13.6 released with the new config option. Closing.
