### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by felixPG** [jcmoraisjr/haproxy-ingress#90]
Hi:

Please, when you specify the use of RBAC, you need to put in your ingress.yaml the service account that the ingress controller will use:

spec.spec
**serviceAccountName: haproxy-ingress-controller**

if not, this cause your pod exiting with NO RBAC RULES DEFINED!

Regards

**Comment by jcmoraisjr** [comment]
Hi, this is what the [doc](https://github.com/jcmoraisjr/haproxy-ingress/blob/master/examples/rbac/README.md#usage) says you should do. Anyway following the deployment docs are error prone regarding rbac, they need a refactor.

**Comment by felixPG** [comment]
thank you!
