### ISSUE TITLE
Support  externalTrafficPolicy Local in services 

### ISSUE THREAD

**Issue by thyn** [jcmoraisjr/haproxy-ingress#901]
We have external load balancer and ingress on nodes (daemonset). It would be interesting to keep traffic and load balance inside node. Currently NodePort is not a good solution. It's difficult to debug, no logs, kube-proxy

**Comment by jcmoraisjr** [comment]
Hi, sorry, I don't think I got your point. How is your actual topology and how do you like it to be? What kind of change do you suggest to be made in the controller?
