### ISSUE TITLE
ingress does not configure host, Unable to access files in the underlying directory

### ISSUE THREAD

**Issue by wcsceshi** [jcmoraisjr/haproxy-ingress#918]
**Description of the problem**

I created an ingress of haproxy type, I don't want to configure the domain name, and I don't configure the host. The path configuration is "/".  I can access the pod through ingress, but  cannot access the next-level directory files; if I want to access the next-level directory files,  need to configure the directory address as the context

**Expected behavior**

the pod image is tomcat , the ingress  pathis "/" , I want to access /docs/index.html, get the result is default backend - 404;
when i set the ingress  path is "/docs" , return right result.

**Environment information**

HAProxy Ingress version: `v0.13`

**Comment by jcmoraisjr** [comment]
Hi, what's the exact v0.13 version that you're using? A similar issue was already reported for v0.13.6 in #906 which was fixed in v0.13.7. Try the update if you're not with the latest version and let us know if the problem was fixed.
