### ISSUE TITLE
no haproxyingress_cert_signing_count in Prometheus

### ISSUE THREAD

**Issue by maxisam** [jcmoraisjr/haproxy-ingress#923]
**Description of the problem**

Most of the dashboard work fine but certificate row 

There is no haproxyingress_cert_signing_count in Prometheus

**Expected behavior**

It should work like others.

**Environment information**

HAProxy Ingress version: `v0.13.7'

**Comment by jcmoraisjr** [comment]
Hi, couldn't reproduce here. Are you using HAProxy Ingress' internal acme signer? Can you see in the logs that new certs are being signed? How did you test it, e.g. `curl -s <haproxy-host>:10254/metrics` and couldn't find any entry? At least one cert was issued after the last controller start?

**Comment by maxisam** [comment]
is it only for internal acme signer? if so, that might be why it doesn't work for me

**Comment by jcmoraisjr** [comment]
yep, using internal acme is the only way the controller has to infer about crt renewal. crt expiration however is easier because we have the secret with it and can extract the NotAfter field.
