### ISSUE TITLE
Seeing lots of "-1" for http status_code and response time in haproxy logs

### ISSUE THREAD

**Issue by kutsav** [jcmoraisjr/haproxy-ingress#924]
**Description of the problem**
For a lot of requests I see "-1" in logs for status code and upstream response time and everything looks fine in terms of app resources. Last time I faced this issue, upgrading to latest HAProxy helped(Not ingress, HAProxy hosted on server), not sure what to do here, since i am on latest version

Example Log:
```
{"haproxy_timestamp":"29/May/2022:17:43:23 +0000","http_status":-1,"host":"redacted","client_ip":"redacted","user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mo","http_request":"GET redacted HTTP/1.1","bytes_read":0,"upstream_addr":"redacted","backend_name":"redacted","retries":0,"bytes_uploaded":703,"upstream_response_time":-1,"upstream_connect_time":0,"session_duration":"273","active_time":273,"termination_state":"SD"}
```
You can see the "upstream_response_time" and "http_status" field has -1 as value

The log format used for same was:
```
'{"haproxy_timestamp":"%Tl","http_status":%ST,"host":"%[capture.req.hdr(0)]","client_ip":"%ci","user_agent":"%[capture.req.hdr(3)]","http_request":"%r","bytes_read":%B,"upstream_addr":"%si","backend_name":"%b","retries":%rc,"bytes_uploaded":%U,"upstream_response_time":%Tr,"upstream_connect_time":%Tc,"session_duration":"%Tt","active_time":%Ta,"termination_state":"%ts"}'
```

**Environment information**

HAProxy Ingress version: `v0.13`

Global options:

config used for controller:
```
    balance-algorithm: roundrobin
    max-connections: "10000"
    timeout-keep-alive: 10s
    timeout-connect: 10s
    timeout-server: 65s
    timeout-client: 65s
```

**Comment by jcmoraisjr** [comment]
Hi, in fact it seems more a haproxy or backend issue. As you can see in your log, the termination status is "SD", which means that, from the haproxy point of view, the connection was unexpectedly aborted by the server or by a network component between haproxy and your backend. Relevant haproxy doc [here](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#8.5).

Regarding haproxy update, you can use external haproxy configuration, which allows you to update haproxy independent of the controller update, doc [here](https://haproxy-ingress.github.io/docs/examples/external-haproxy/).

Maybe you have a few more data, e.g. a correlation with conn/s or req/s spike, error from the server side, issue in the network, bunch of processing in the controller, controller isssuing haproxy restart, etc.
