### ISSUE TITLE
difference between this haproxy-ingress and haproxytech one?

### ISSUE THREAD

**Issue by KlavsKlavsen** [jcmoraisjr/haproxy-ingress#949]
I cannot find any comparison or reasoning about the pro and cons, over https://github.com/haproxytech/kubernetes-ingress ?
I would prefer not to have to read all the code to figure it out - this should be in readme IMHO

**Comment by jcmoraisjr** [comment]
Hi, we do not compare HAProxy Ingress with other controller implementations, but I'd be glad to see any comparison out there and have the chance to comment about it from the HAProxy Ingress perspective - in the case the comparison isn't being fair with our controller. Besides that we use this tracker for bugs or feature request, so feel free to continue this talk in the slack channel in the case you have a more specific doubt or concern.

**Comment by KlavsKlavsen** [comment]
I opened a bug, as I would consider it a bug, that you don't really help potential users, in initial readme, to see what makes this haproxy ingress controller different, than the official one. I assume you have differing goals, or something?
All I can do, as a user wanting to see which to choose - I can only try and read through changelog, to guess the state and features of each, to try and compare to my needs for using it.
f.ex. Do you have support for adding custom lua plugins, via Helm chart (I want to use lua jwt plugin that we are using in our existing haproxy outside k8s)?

But if you do not feel that way, that is ofcourse completely up to you.

**Comment by KlavsKlavsen** [comment]
From reading https://haproxy-ingress.github.io/docs/configuration/keys/ and the rest of the docs, which are very good, it seems this project is focused highly on flexibility, by allowing injection of specific haproxy config (and files such as lua plugins) - but that in turn ofcourse means you need an indepth knowledge of haproxy (which to me is fine - but haproxytech ingress seems to me to be more focused on not requiring users to know haproxy to do more advanced things - which does mean it does not offer the same flexibility currently).

**Comment by jcmoraisjr** [comment]
I see your point. From one side I didn't take the time to realize how to make it in a clear, useful and unbiased way, but instead I prefer to invest time improving code and doc quality. I agree that this might help potential users to choose this controller, but honestly I'm not worried about that. I do prefer to improve the experience of users that have chosen HAProxy Ingress instead, this seems more important to me. Note that I wouldn't deny adding such info in the doc or readme, provided that a volunteer propose one as a pr. Regarding usability I wouldn't say one need more haproxy experience to use this controller, however some more advanced features require that.
