### ISSUE TITLE
E1021 

### ISSUE THREAD

**Issue by fmelon2** [jcmoraisjr/haproxy-ingress#953]
hello！
   Has anyone encountered this problem? My environment is kubeadm1.23. I am using the yaml file of version 0.13.9. The yaml only modifies the version of the mirror.

E1021 09:14:04.293365       7 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.15/tools/cache/reflector.go:167: Failed to watch *v1.IngressClass: failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:ingress-controller:ingress-controller" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**Comment by jcmoraisjr** [comment]
Does it sound a permission issue? Please reach us on slack so we can provide a better support. Github issues are dedicated to feature requests and bugs.
