### ISSUE TITLE
This isn't a bug with this image but a bug I am getting with HaproxyTech and wondering if this image would better servce my usecase

### ISSUE THREAD

**Issue by xtianus79** [jcmoraisjr/haproxy-ingress#956]
I'm using currently 1.9 helm install of haproxytech

My usecase is I am terminating a cert at the load balancer with this notation. 

```
data:
  8883:
    ingress-name/mqtt:1883:ssl
```

The issue I am seeing is this error when I use `ssl-certificate: namespace/secret-tls`

```
 ERROR   handler/tcp-services.go:41 incorrect format namespace/secret-tls', 'ServiceName:ServicePort' is required
```
From my understanding (something found in searching github issues @ haproxytech) is that you can't use ssl for TCP backends. 

Can you use ssl certs with tcp backends with this controller?

**Comment by jcmoraisjr** [comment]
Yes you can, as stated in the item 5 from the [tcp-services documentation](https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap).

Note that this tracker is used for bugs and feature requests, so please reach us on slack if you still have any issue.
