### ISSUE TITLE
Variable substitution  doesn't work in configuration snippets

### ISSUE THREAD

**Issue by am813nt** [jcmoraisjr/haproxy-ingress#969]
Sorry if I'm wrong but to me it looks like a bug.
I've got k8s cluster with haproxy ingress behind another (bare-metal) haproxy. That external haproxy does SSL termination (no https on ingress). I want to pass X-Forwarded-Proto header set by external haproxy to services in k8s. To do that I add backend configuration snippet like that:

```
haproxy-ingress.github.io/config-backend: |-
    acl is_https_proxied hdr(X-Forwarded-Proto) -m found
    http-request set-header X-Forwarded-Proto %[hdr(X-Forwarded-Proto)] if is_https_proxied
``` 

But that doesn't work: X-Forwarded-Proto is still set to http. ACL is executed correctly, but the value of the header is missing.

And this configuration works:

```
haproxy-ingress.github.io/config-backend: |-
    acl is_https_proxied hdr(X-Forwarded-Proto) -m found
    http-request set-header X-Forwarded-Proto https if is_https_proxied
``` 

But this way is unacceptable because external haproxy may forward http as well. 

I test it like that:

```
curl -H 'X-Forwarded-Proto: https' -H 'Host: myservice.k8s' http://<myk8sip>/
```

What's wrong? Maybe am I missing something?

**Comment by jcmoraisjr** [comment]
Try just adding `fronting-proxy-port: 80` in the global ConfigMap, doc [here](https://haproxy-ingress.github.io/v0.14/docs/configuration/keys/#fronting-proxy-port). Let us know if it works.

**Comment by am813nt** [comment]
No, still doesn't work.

**Comment by jcmoraisjr** [comment]
Hi, in that case please fill all the issue template, provide all the asked info along with your rendered haproxy.cfg file, so that we can start to understand what's happening.
