### ISSUE TITLE
Documentation/support for running in custom containers.

### ISSUE THREAD

**Issue by dElogics** [jcmoraisjr/haproxy-ingress#97]
Hi.
I would like to run your application in a custom container with system haproxy (as installed in the container).

I would request documenting on how this application (which manages haproxy) works so it can be ported to other containers.

**Comment by jcmoraisjr** [comment]
Hi, [rootfs](https://github.com/jcmoraisjr/haproxy-ingress/tree/master/rootfs) should have everything you need. Follow `Dockerfile` on how to bootstrap the service, change `haproxy-reload.sh` to fit your needs.
