### ISSUE TITLE
Support routing for other headers than Host header

### ISSUE THREAD

**Issue by nlighten** [jcmoraisjr/haproxy-ingress#973]
First of all, thank you for your effort maintaining this great product. 

**What are you trying to do**
My client is a corporate that requires a separate proxy in front of haproxy-ingress:

```
User ---> Reverse Proxy --> Ingress 
```

They also require HTTPS between Reverse Proxy and Ingress.  Since the client has applications with hundreds of domains and the Reverse Proxy does strict TLS hostname validation this would require many (duplicated) certificates on haproxy-ingress side.

Instead of having to configure many certificates on haproxy-ingress side, we would like to use a single global certificate and set `ssl-always-add-https` to `true`. The Reverse Proxy would override the `Host` header  used to forward traffic to haproxy-ingress to the hostname matching the global certificate. The original host header would be forwarded as e.g. `X-Forwarded-Host` header.

For this to work haproxy-ingress should be able to use other headers than only `Host` for ingress routing.

**What HAProxy Ingress should do or how it should behave differently**
Ideally we would like to haproxy-ingress to accept a global configuration parameter as Host name source. This parameter would default to using `host` E.g.:

```
host-name-source: host
```

Then the `haproxy.tmpl` file could be changed to something like below to allow routing on other headers then only the host header. Note that another source than `host` is used, the `host` header on backend side should be replaced as well.  

```
git diff
diff --git a/rootfs/etc/templates/haproxy/haproxy.tmpl b/rootfs/etc/templates/haproxy/haproxy.tmpl
index fbfaa03f..48b8b6e8 100644
--- a/rootfs/etc/templates/haproxy/haproxy.tmpl
+++ b/rootfs/etc/templates/haproxy/haproxy.tmpl
@@ -618,6 +618,9 @@ backend {{ $backend.ID }}
 {{- end }}

 {{- /*------------------------------------*/}}
+{{- if ne $global.HostNameSource "host" }}
+    http-request set-header Host %[hdr({{ $global.HostNameSource }})]
+{{- end }}
 {{- if eq $global.ForwardFor "add" }}
     http-request set-header X-Original-Forwarded-For %[hdr(x-forwarded-for)] if { hdr(x-forwarded-for) -m found }
     http-request del-header x-forwarded-for
@@ -1142,7 +1145,7 @@ frontend {{ $proxy__front_http }}

 {{- /*------------------------------------*/}}
     http-request set-var(req.path) path
-    http-request set-var(req.host) hdr(host),field(1,:),lower
+    http-request set-var(req.host) hdr({{ $global.HostNameSource }}),field(1,:),lower
     http-request set-var(req.base) var(req.host),concat(\#,req.path)

 {{- /*------------------------------------*/}}
@@ -1258,7 +1261,7 @@ frontend {{ $proxy__front_https }}

 {{- /*------------------------------------*/}}
     http-request set-var(req.path) path
-    http-request set-var(req.host) hdr(host),field(1,:),lower
+    http-request set-var(req.host) hdr({{ $global.HostNameSource }}),field(1,:),lower
     http-request set-var(req.base) var(req.host),concat(\#,req.path)

 {{- /*------------------------------------*/}}
```

Would you consider something like this to fit your vision for haproxy-ingress? If needed, I would be more than happy to prepare a PR.

**Comment by jcmoraisjr** [comment]
Hi, if I'm not mistaken you can `set-header host %[hdr(source-hdr)]` before the keywords used to route the incoming request. This isn't possible in the current versions because `config-frontend` acts a bit late, but since #951 you can use `config-frontend-early` to do that. We don't have any tag with that functionality, it'll be added in the first v0.15 snapshot. So if using a snippet like your own proposal:

```
global-cm:
  config-frontend-early: |
    http-request set-header Host %[hdr(x-forwarded-host)]
```

.. you'll have the ability to define the host header to whatever value you need, without the need to change the other configs. Did I miss something here?

**Comment by nlighten** [comment]
I just tested this and overriding host header before its value is copied to `req.host` works fine. Looking at #951 that is indeed the case for  `config-frontend-early` so that would be a perfect solution for us.

If I understand correctly this feature will not make it for v0.14. Any guestimate on the v0.15 release timeline? Would that be still be first half of 2023 or is that not realistic?

**Comment by jcmoraisjr** [comment]
Great, so better to use a generic config options instead of maintaining another specific one. Btw it seems it's your lucky day, #951 is an improvement of another feature added in v0.14 and I just tagged it to that branch as well. We'll have v0.14.0 during this week with this feature included.

**Comment by nlighten** [comment]
Awesome. I'll close this issue and wait for the release.

Thanks again!
