### ISSUE TITLE
PROXY protocol version switch

### ISSUE THREAD

**Issue by IvanovOleg** [jcmoraisjr/haproxy-ingress#99]
Postfix mail server doesn't support PROXY protocol V2. So it's a good idea to implement some kind of switch between PROXY V1 and PROXY V2 fe:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp
  namespace: default
data:
  "25": "default/mailserver:25"
  "587": "default/mailserver:587::PROXY"
  "993": "default/mailserver:993::PROXY2"
```

**Comment by jcmoraisjr** [comment]
Added in the current snapshot of v0.6. Closing. Update this same issue if you have any problem.

Doc updated, the syntax is `<ns>/<svc>:<port>::PROXY-V1`.
